### ISSUE TITLE
Need to specify PDSE and data set characteristics for authlib

### ISSUE THREAD

**Issue by Tam-Lin** [zowe/docs-site#1067]
In https://github.com/zowe/docs-site/blob/Release-Notes-1.9/docs/user-guide/install-zowe-smpe.md, you explicitly say that the authorized load library dataset dataset needs to be a PDSE, of a certain size and characteristics.  On https://github.com/zowe/docs-site/blob/Release-Notes-1.9/docs/user-guide/install-zowe-zos-convenience-build.md, you say that the authorized load library is a PDS, and don't give any size/characteristic information.  I believe the two should match.

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, any comments on this issue?

**Comment by Joe-Winchester** [comment]
@Tam-Lin - tks for finding this inconsistency.  I'll create a PR to fix it.  I think what you're referring to is that the Table in SMP/E should have the values used for the convenience build also, e.g. 
![image](https://user-images.githubusercontent.com/28100302/77054597-e3d4bd80-69c7-11ea-8c04-0588b6ba13f9.png)
