### ISSUE TITLE
Missing quotation mark on shell command

### ISSUE THREAD

**Issue by Tam-Lin** [zowe/docs-site#1074]
## Description
Missing a quotation mark on a command

## Pages to Update
https://docs.zowe.org/stable/troubleshoot/troubleshoot-zos-services.html#z-os-services-are-unavailable

## Expected behavior
curl --user <username>:<password> -k -X GET --header 'Accept: application/json' --header 'X-CSRF-ZOSMF-HEADER: true' "https://<z/os host name>:<securezosmfport>/zosmf/restjobs/jobs?prefix=*&owner=*

needs a closing quotation mark.

**Comment by nannanli** [comment]
Thank you for catching this issue! It has been fixed now via PR https://github.com/zowe/docs-site/pull/1082. Any further feedback or suggestions on Zowe docs are appreciated.
