### ISSUE TITLE
Create a Medium blog that explains ICSF configuration for Zowe

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1148]
ICSF configuration information has been removed from Zowe docs because it's not required for Zowe. However, for users who want to generate symmetric keys, it would still be useful content. Therefore, a blog will be created to talk about ICSF for Zowe. 

Issue https://github.com/zowe/docs-site/issues/1073 provides relevant information. The following section pulls together all ICSF-related information (including what's removed from docs) as input. 

==============================>
Here is the basic information about ICSF and why it should be available for Zowe in Z/OS:

* ICSF is a base element of z/OS and is included in z/OS package. It is not a Priced Feature. Each release of z/OS includes a particular ICSF FMID level as part of its base. For example, ICSF with FMID HCR77C0 is the base element of z/OS V2R3. 
* By default its SMP/E installed data sets has HLQ: CSF
* ICSF is not a prerequisite for Zowe, It is a prerequisite for IBM SDK for Node.js - z/OS. Since Zowe Application Framework requires Node.js, ICSF is a must.
* ICSF for Node.js requires neither Cryptographic Hardware nor Crypto cards.

Generating symmetric keys (Symmetric Encryption) is required if we want to have cryptography services such as Data Confidentiality to protect data from disclosure to unauthorized parties, so it is not a requirement for Zowe.

### Configuring ICSF for Zowe

This section summarizes the high-level steps that you can follow to configure and start ICSF. For more information, refer to [ICSF System Programmer's Guide](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.csfb200/in2.htm) and [ICSF Administrator's Guide](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.csfb300/abstract.htm).

1. Add `CSF.SCSFMOD0` to the LNKLST concatenation.
2. APF authorize `CSF.SCSFMOD0`.
3. Modify `IKJTSOxx` to add `CSFDAUTH` and `CSFDPKDS` in the `AUTHPGM` parameter list and in the `AUTHTSF` parameter list.
4. Create the following ICSF Key Data Sets:
    - Cryptographic Key Data Set (CKDS) 

      Sample JCL: `SYS1.SAMPLIB(CSFCKDS)`

    - Public Key Data Set (PKDS)

      Sample JCL: `SYS1.SAMPLIB(CSFPKDS)`

    - (Optional) If you want to have PKCS#11 support through ICSF, you should create Token Key Data Set (TKDS) 

      Sample JCL: `SYS1.SAMPLIB(CSFTKDS)`

5. Copy ICSF Installation Options sample (`SYS1.SAMPLIB(CSFPRM00)`) to the system PARMLIB data set, and change the name of the data set on the CKDSN and PKDSN statements to the name of data sets you created previously.
6. Create ICSF startup procedure. Copy `SYS1.SAMPLIB(CSF)` to the system PROCLIB and change the data set name in the `CSFPARM DD` statement to the name of the installation options data set you provided previously.
7. (Optional) Define a RACF Started Procedure profile for CSF procedure in `CLASS(STARTED)`.
8. Start ICSF (`S CSF`).

**Note:** You might need IPL before starting ICSF.

### Configure an ICSF cryptographic services environment

To generate symmetric keys, the `ZWESVUSR` user who runs `ZWESVSTC` requires READ access to `CSFRNGL` in the `CSFSERV` class.

Define or check the following configurations depending on whether ICSF is already installed:

- The ICSF or CSF job that runs on your z/OS system.
- The configuration of ICSF options in `SYS1.PARMLIB(CSFPRM00)`, `SYS1.SAMPLIB`, `SYS1.PROCLIB`.
- Create CKDS, PKDS, TKDS VSAM data sets.
- Define and activate the CSFSERV class:

    - If you use RACF, issue the following commands:
        ```
        RDEFINE CSFSERV profile-name UACC(NONE)
        ```
        ```
        PERMIT profile-name CLASS(CSFSERV) ID(tcpip-stackname) ACCESS(READ)
        ```
        ```
        PERMIT profile-name CLASS(CSFSERV) ID(userid-list)   ... [for 
        userids IKED, NSSD, and Policy Agent]
        ```
        ```
        SETROPTS CLASSACT(CSFSERV)
        ```
        ```
        SETROPTS RACLIST(CSFSERV) REFRESH
        ```
    - If you use CA ACF2, issue the following commands (note that `profile-prefix` and `profile-suffix` are user-defined):
        ```
        SET CONTROL(GSO)
        ```
        ```
        INSERT CLASMAP.CSFSERV RESOURCE(CSFSERV) RSRCTYPE(CSF)  
        ```
        ```
        F ACF2,REFRESH(CLASMAP)
        ```
        ```
        SET RESOURCE(CSF)
        ```
        ```
        RECKEY profile-prefix ADD(profile-suffix uid(UID string for tcpip-stackname) SERVICE(READ) ALLOW)   
        ```
        ```
        RECKEY profile-prefix ADD(profile-suffix uid(UID string for IZUSVR) SERVICE(READ) ALLOW)
        ```
        (repeat for userids IKED, NSSD, and Policy Agent)

        ```
        F ACF2,REBUILD(CSF)
        ```
    - If you use CA Top Secret, issue the following command (note that `profile-prefix` and `profile-suffix` are user defined):
        ```
        TSS ADDTO(owner-acid) RESCLASS(CSFSERV)              
        ```
        ```                  
        TSS ADD(owner-acid) CSFSERV(profile-prefix.)
        ```
        ```
        TSS PERMIT(tcpip-stackname) CSFSERV(profile-prefix.profile-suffix) ACCESS(READ)
        ```
        ```
        TSS PERMIT(user-acid) CSFSERV(profile-prefix.profile-suffix) ACCESS(READ)
        ```
        (repeat for user-acids IKED, NSSD, and Policy Agent)

**Notes:**

- Determine whether you want SAF authorization checks against `CSFSERV` and set `CSF.CSFSERV.AUTH.CSFRNG.DISABLE` accordingly.
- Refer to the [z/OS 2.3.0 z/OS Cryptographic Services ICSF System Programmer's Guide: Installation, initialization, and customization](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.csfb200/iandi.htm).
- CCA and/or PKCS #11 coprocessor for random number generation.
- Enable `FACILITY IRR.PROGRAM.SIGNATURE.VERIFICATION` and `RDEFINE CSFINPV2` if required.

**Comment by Joe-Winchester** [comment]
Closing this as issue as it was covered with https://github.com/zowe/docs-site/issues/1073 where the chapter had the ICSF section put back
