### ISSUE TITLE
Document changes to zowe-setup-certificates.sh for SSO

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/docs-site#1162]
@timgerstel commented on [Tue Apr 28 2020](https://github.com/zowe/zowe-install-packaging/issues/1318)

**Describe the bug**

zowe-setup-certificates.sh will need re-running during the upgrade process. This requirement is due to the automatic setup of SSO, requiring users to input new values in zowe-setup-certificates.env. This doc will be a requirement for the following pull request: https://github.com/zowe/zowe-install-packaging/pull/1291

**Comment by timgerstel** [comment]
https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/systemrequirements.md

**Comment by stevenhorsman** [comment]
As mentioned on slack this needs to go into the doc section related to that script as well as/instead of the system requirements: https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/configure-certificates.md

**Comment by travatine** [comment]
Hi, 

I just upgraded from zowe 1.9 to 1.13 .

Now when I try to login to zowe desktop, I get this message:

Authentication failed for 3 types. Types: ["saf","apiml","zss"]

Do I need to rerun "zowe-setup-certificates.sh " ?

Thanks,

**Comment by stevenhorsman** [comment]
@travatine - yes, moving between 1.9 and 1.13 it is advisable that you re-run zowe-setup-certificates to take advantage fo the single sign on capabilities
