### ISSUE TITLE
[Troubleshooting tip] zss unable to connect to zlux - logon problem - localhost not defined

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1163]
### 2. Choose a title

Working with a customer who was unable to log into the desktop.  The problem was zss unable to connect to zlux because localhost wasn't mapped in etc/.hosts file

### 3. Symptom

Desktop unable to logon.

**Comment by John-A-Davies** [comment]
The message you get on the MVD logon screen is
```
Authentication failed for 1 types, Types: ["zss"]
```
which is documented in the Zowe User Guide under the heading `Cannot log in to the Zowe Desktop`, but the `localhost` failure cause is not included there.
