### ISSUE TITLE
[Troubleshooting tip] - node cluster timeout - spotted in slack

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/docs-site#1164]
### 1. Slack conversation link (if any)
https://openmainframeproject.slack.com/archives/CC08782AG/p1588083435121600

### 2. Choose a title
Node cluster storage timeout

### 3. Symptom
When starting the Zowe server the node address spaces don't start

### 4. Solution
edit $INSTANCE_DIR/instance.env to add ZWED_node_cluster_storageTimeout=30000 or some other number.

**Comment by 1000TurquoisePogs** [comment]
In 1.11, the default has been set to 30000 (was 5000). That SHOULD be good for everyone, but in the case that it fails, this number can be set higher. It's in milliseconds.
