### ISSUE TITLE
v1.11.LTS does not describe PTFs

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#1193]
## Description

The user guide for v1.11.LTS on zowe.org still says
```
Since this is the first release of the SMP/E package, no PTFs have been created.
```

## Pages to Update

User guide PDF and zowe.org web page

## Expected behavior

Doc should list PTFs by release and describe how to apply them using SMP/E

## Additional context

The zowe.org downloads page does not explicitly say that users who do not already have the FMID must download and install it before installing the PTF - although any sysprog will know that.  
So a new user will have to click two separate buttons.

It might also be useful to add a brief note that any Zowe PTF rolls up all the previous ones, so users should install the latest one and older ones are not needed.

**Comment by John-A-Davies** [comment]
@nannanli FYI as mentioned on Slack.

**Comment by nannanli** [comment]
Doc has been updated. In the middle of updating the zowe.org download section to clarify this.

**Comment by nannanli** [comment]
Both docs and zowe.org are updated now to clarify the use of PTFs. Closing. 
- On Zowe.org, it now says `Download the base FMID AZWE001 (based on v1.9.0) first and then apply the PTFs to get the latest version. ` in the **Download** section. 
- In zowe docs, the list of PTFs for each release is added. See https://docs.zowe.org/stable/user-guide/install-zowe-smpe.html#service-level-information.
