### ISSUE TITLE
[Troubleshooting tip] Document general USS topics for teams not fluent with unix side

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/docs-site#1195]
Did some education session for Zowe, one of the major feedback is to not having familiarity with USS side of z/OS

Would be great if we can document some common topics like
**networking commands**  -  list TCP/IP ports - `onetstat -a`, network access
**environment variables** - `hostname`, java_home, node_home, .profile
**general navigation techniques** search - `cd`, `find`, `grep`
**process list**  - `ps -elf`
**shell scripting** - `source variable`, instance.env
**folder permissions, file tags** - `chmod`, `chtag` - read only directory, ISO 8559 files

**Comment by NakulManchanda** [comment]
@Joe-Winchester feel free to add edit this topic, thanks!

**Comment by John-A-Davies** [comment]
Our mission has been to open up the mainframe to web, internet and Unix users on distributed systems.  We have assumed they are most familiar with Linux, Windows or Mac.  Further, we have written our install process on that premise, although SMP/E can be used as the install vehicle.  Therefore I would assume they have enough knowledge to readily use USS.        

However that may not be their background, but some basic USS knowledge is required (kind of a pre-requisite), so they need to get up to speed.  

But I don't think we should create that material.  You only have to Google "unix system services primer" to find videos, Redbooks and the IBM Knowledge Center material on the topic.

However, some documentation of environment variables - hostname, java_home, node_home, .profile as used by Zowe would be useful, although I'd hope these were already covered in the Zowe User Guide.

**Comment by solsu01** [comment]
Here's thread on reddit with some concerns about the USS install portions:
https://www.reddit.com/r/mainframe/comments/gf9svf/on_the_rise_of_zowe_and_nodejs_and_other/

**Comment by Joe-Winchester** [comment]
The Segus webinar at https://www.segus.com/events/webinars/webinar-what-is-zowe-going-to-do-for-me/ has a slide that talks about the steps they had to perform to get USS working.
- In Language Environment we found out that we had to raise the HEAP64 quite a bit: 
  - HEAP64(512M,4M,KEEP,256M,4M,KEEP,OK,FREE)
- The MEMLIMIT of the OMVS users must also be raised
- As extenders of Zowe they changed their .profiles to support ASCII encoding with
```
export_BPXK_AUTOCVT=ON
export_CEE_RUNOPTS='FILETAG(AUTOCVT,,AUTOTAG) POSIX(ON)'
export_TAG_REDIR_ERR=txt
export_TAG_REDIR_IN=txt
export_TAG_REDIR_OUT=txt
```
I've created a branch `/user/winchj/uss-overview` to begin writing a chapter **Zowe and Unix System Services**

**Comment by John-A-Davies** [comment]
The format of the export commands should be `export _BPXK_AUTOCVT=ON` etc.  I.e. you need one space after `export`

**Comment by NakulManchanda** [comment]
https://www.reddit.com/r/mainframe/comments/gf9svf/on_the_rise_of_zowe_and_nodejs_and_other/frf0tq6/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by nannanli** [comment]
The Zowe USS chapter is available on the doc site now to address USS related questions. See [UNIX System Services considerations for Zowe](https://docs.zowe.org/stable/user-guide/configure-uss). Closing.
