### ISSUE TITLE
Pre-install information worksheet recommended in Documentation

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/docs-site#1201]
@xwu0226 commented on [Tue May 12 2020](https://github.com/zowe/zowe-install-packaging/issues/1358)

*Customer content*

Pre-install information worksheet would be useful. Even better if the pre-install worksheet would carry across product installs.

**Comment by nannanli** [comment]
Good suggestion! The pre-Installation worksheet identifies all the information required by the installer. Filling out the worksheet prior to installation will help the installation process run smoothly and provide a record of the settings used for ease of replication across multiple servers.Investigated and found some example installation worksheets: 

**Example 1**
https://docs.bmc.com/docs/digitalworkplaceadvance/33/installation-worksheets-718093048.html

**Example 2**
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/14340789/82280726-1730ca00-99c2-11ea-8518-ec5be9a80238.png">

**Comment by Joe-Winchester** [comment]
@sn666239 and @vit-tomica and @uzust01.  It sounds like this would be great for us to create to shadow the z/OSMF workflow install and configure templates you created.  A few folks are very keen to see the templates in action - is this something that any/all of you would be able to do to the community ?  Perhaps at the end of a scrum or the Tuesday architecture call next week or an ad-hoc presentation where we can all see the workflows in action and understand them ?  cc:  @stevenhorsman

**Comment by samanthasusu** [comment]
Close with existing checklists for installation. Thanks
