### ISSUE TITLE
READ access to the STC user under which the ZWESASTC

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/docs-site#1206]
The manual https://docs.zowe.org/stable/user-guide/configure-xmem-server.html#step-4-configure-saf states that 

> "It is recommended that you also grant READ access to the STC user under which the ZWESASTC started task runs which is ZWESIUSR."

This is actually a requirement.
I suggest updating the text to:

> Those callers include the STC user ZWESVUSR under which the ZWESVSTC started task runs and the STC user under which the ZWESASTC started task runs which is ZWESIUSR.

See also https://github.com/zowe/zowe-install-packaging/issues/1361 for the related change to the ZWESECUR security job.

**Comment by samanthasusu** [comment]
Closed because it has been updated. Thanks
