### ISSUE TITLE
 Improve the search engine for the docs site

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#122]
Currently, the search only supports scanning headings. We need to provide an enhanced search experience by supporting searching keywords in the whole docs site.

**Comment by adambattenburg** [comment]
[Documentation on Search in Vuepress](https://vuepress.vuejs.org/default-theme-config/#search-box) for Jack to look at it. Basically they recommend using a paid service Algolia to improve the search. We could probably create our own solution as well if Jack wants to take that on.

**Comment by jackjia-ibm** [comment]
Thanks @adambattenburg for the info. I checked Algolia and think DocSearch is open source and free to use. They even provide search hosting but need to apply (for free). Here is related link https://community.algolia.com/docsearch/who-can-apply.html. I will continue to test out this solution.

**Comment by nannanli** [comment]
It's great to have an open source solution! Thanks Jack. @jackjia-ibm I read the instructions in the cited link and we fully meet their criteria to apply.

**Comment by jackjia-ibm** [comment]
@nannanli @PlutoZhang  @adambattenburg I've added a preview Algolia search box to the test docs site: https://jackjia-ibm.github.io/docs-site/. The UI is the default theme. Please take a look and let me know how you thinking. I have meeting with UI/UX team, will also ask their opinions.

_Please note it shares same search indexes Algolia put on https://zowe.github.io/docs-site/. So every time if you click on the search result, it will lead you back to https://zowe.github.io/docs-site/ official website._

There are few things in my mind:

* The search result should be limited to the version currently on. It should only has documentation from "latest" version folder. This is done.
* Archiving documentation version now requires a manual step to create pull request to update the crawler configuration (https://github.com/algolia/docsearch-configs/blob/master/configs/zowe.json#L7)
*  The crawler is configured to run in daily basis. So it may not affect the most recent updates on the documentation website. We don't have control on their crawler. If we want to update the search indexes more frequently, we may run our own crawler, or maybe move to paid version.

Thanks!

**Comment by nannanli** [comment]
I just tried the search and it works great. Thanks @jackjia-ibm!  For the second bullet point, when we go to 1.0 and have an archived version of 0.9 (which is now the latest version), users will be able to select which version to view. In this case, will users still be able to search the 0.9 version?

**Comment by jackjia-ibm** [comment]
@nannanli yes they can. If they choose to view 0.9 version documentation, the search result will only show documentations in /v0-9-x folder, so everything in /latest (which is 1.0) won't show up.

**Comment by jackjia-ibm** [comment]
This should be fixed with https://github.com/zowe/docs-site/pull/200.
