### ISSUE TITLE
[Troubleshooting tip]

### ISSUE THREAD

**Issue by jandadav** [zowe/docs-site#1223]
### 1. Slack conversation link (if any)

There is a github issue that should go to troubleshooting:
https://github.com/zowe/api-layer/issues/272

### 2. Choose a title

API Mediation Layer throwing `I/O error on GET request` : `java.net.UnknownHostException` or `java.net.NoRouteToHostException`

### 3. Symptom

There is great description in the linked GitHub issue.

### 4. Solution

Solution is also outlined in the github issue. It can be lifted.

**Comment by jandadav** [comment]
@nannanli  Can you please guide me what are the next steps to get this troubleshooting tip created?

**Comment by nannanli** [comment]
@jandadav Hi David, I'll add this to the doc today for you to review. Or you could create a PR directly if you prefer.
