### ISSUE TITLE
Make clear to use when node versions on z/OS go out of support to allow them to plan accordingly

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1238]
## Is your request for enhancement related to a problem? Please describe.
Node.js on z/OS is a pre-requisite for the App Framework.
Doc chapter calls out supported releases
https://docs.zowe.org/stable/user-guide/install-nodejs-zos.html#supported-node-js-versions
Each  node release 6, 8, 12, ... has an end of support timeframe
This issue is to provide a way users reading Zowe doc can see when the end of support is with links to the node.js sites and plan accordingly

## Describe the solution you'd like
Doc chapter https://docs.zowe.org/stable/user-guide/install-nodejs-zos.html#supported-node-js-versions calling out node releases and their support timeframes

**Comment by nannanli** [comment]
Doc has been updated and published. Closing.
