### ISSUE TITLE
Add Z Tech U videos youtube OMP channel and from there into the docs

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1239]
## Is your request for enhancement related to a problem? Please describe.
Add more videos to the Zowe docs https://docs.zowe.org/stable/getting-started/zowe-resources.html#videos-webinars

## Describe the solution you'd like
@jordanCain has created some great videos that demo Zowe functionality across the different components.  It'd be great if they were on the OMP youtube channel and then in the Zowe docs.

## Related doc pages
https://docs.zowe.org/stable/getting-started/zowe-resources.html#videos-webinars

**Comment by jordanCain** [comment]
@nannanli I will be looking to re record the videos using the Zowe 1.12.0 version which has slightly updated interfaces. There were 3 demos, one for the Zowe Desktop/App framework, one for the Zowe CLI and then one for the Zowe Explorer VS Code plugin. I would like to have each one as a separate video on the OMP Youtube. 

Do we know what the process for uploading videos to the OMP youtube channel is?

**Comment by nannanli** [comment]
@jordanCain That sounds great! Here is the OMP Youtube process: [https://github.com/zowe/community/tree/master/videos](https://github.com/zowe/community/tree/master/videos).

**Comment by jordanCain** [comment]
The first of the videos have been published to the OMP YouTube channel here: https://www.youtube.com/watch?v=azwwBi1ZUu8 covering using the Zowe Desktop
