### ISSUE TITLE
Update documentation regarding API ML encoded slashes

### ISSUE THREAD

**Issue by awharn** [zowe/docs-site#1272]
## Is your request for enhancement related to a problem? Please describe.
Zowe-CLI now integrates with the API Mediation Layer to provide support for token based authentication and Single Sign On. However, the CLI sanitizes user input before creating REST requests in order to handle special characters that were passed in. This is done by performing URI encoding. Therefore, when attempting to do anything regarding USS paths, an encoded slash is used. Attempting to change this functionality may be considered breaking.

The API ML setup documentation states that it is recommended to leave the allowEncodedSlashes option off. This means the CLI cannot route a considerable number of requests through the APIML.

## Describe the solution you'd like
Documentation to be updated, noting that allowEncodedSlashes will need to be enabled on both the API ML gateway and the z/OSMF service in order to allow Zowe-CLI to issue REST requests to the z/OSMF endpoint.

## Related doc pages
https://github.com/zowe/docs-site/blob/7c6928087c5513e6b7ecff61bce74180c5dd66ac/docs/user-guide/install-zos.md
https://docs.zowe.org/stable/user-guide/install-zos.html#stage-3-configure-the-zowe-runtime

**Comment by nannanli** [comment]
Validated that the doc updates are live now. See [this commit](https://github.com/zowe/docs-site/commit/589e9ff4c3340cfd53f950b6a9fff5aeb32b0e3f) and the [published documentation](https://docs.zowe.org/stable/user-guide/install-zos.html#stage-3-configure-the-zowe-runtime) on the doc site. Closing but feel free to reopen if any issue persists. @janan07
