### ISSUE TITLE
[Troubleshooting tip] Cannot start ZWESAUX

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#1289]
### 1. Slack conversation link (if any)

https://openmainframeproject.slack.com/archives/CC08782AG/p1593531399284800

### 2. Choose a title

Cannot start ZWESAUX

### 3. Symptom

 when I try and start ZWESAUX task it falls over with the following...
ZWES0058E Communication area failure - master comm area parm not found.

### 4. Solution

You're not supposed to start up ZWESAUX, it's started up by ZWESIS on an as-needed basis

**Comment by John-A-Davies** [comment]
The user guide already says
```
You do not start or stop the ZWESASTC manually
```

**Comment by pdbossman** [comment]
In this case, I think less is better.  There is so much text on the screen using AUX, people are conflating it with the started task name which is ZWESASTC.

**Comment by F-LEMANER** [comment]
Hello,
Can you correct the documentation, User's Guide page 120 : a A is missing in the STC name

![image](https://user-images.githubusercontent.com/63342548/86493907-a2e49700-bd73-11ea-8206-36b4f1881c5f.png)

**Comment by nannanli** [comment]
@F-LEMANER Thank you for raising this defect! It's fixed in this PR #1292 . Docs will be updated upon merge.
