### ISSUE TITLE
v1.12 install-app.sh not found

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/docs-site#1297]
Hello,
In DD STDERR of STC ZWESVTC I have : 
/SYSTEM/var/ZWE/inst_01/bin/install-app.sh: /var/ZWE/bin/utils/zowe-install-iframe-plugin.sh 97: FSUM7351 not found 

Im' upgrading from 1.9 to 1.12

In 1.9 install-app.sh was in /var/ZWE/instance_dir/bin/

In 1.12, I look in all dir and subdir and don't find it

![image](https://user-images.githubusercontent.com/63342548/86493743-fefaeb80-bd72-11ea-84c5-036695e33f40.png)

**Comment by nannanli** [comment]
Issue moved to [zowe/zlux #495](https://github.com/zowe/zlux/issues/495) via [**ZenHub**](https://www.zenhub.com/)
