### ISSUE TITLE
faulty location in sample command

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#1300]
## Description

in step 1 the sample command tells you to copy to a relative location (should be absolute), which seems to match with the a path of the installed binaries (which are off limits for updating as everything is wiped and replaced on upgrade)
```
cp "//'[output_dataset_name]'" 'zlux-app-server/deploy/instance/ZLUX/serverConfig/[ca_cert]'
```
in step 3 the actual location of the file is referenced, here a proper path is used
```
"certificateAuthorities": ["[INSTANCE_DIR]/workspace/app-server/serverConfig/[ca_cert]"]
```
## Pages to Update

https://docs.zowe.org/stable/user-guide/mvd-configuration.html#configuring-zss-for-https

## Expected behavior

step 1 should use the same sample path as step 3

**Comment by ShellShockQ** [comment]
Is this issue still unaddressed? It appears to be, but I'm confirming.

**Comment by OnnoVdT** [comment]
correct, still unaddressed
