### ISSUE TITLE
workflows are in a different location

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#1325]
## Description

The config pages document that customization workflows are in files/workflows.  However, they are installed in $ZOWE_ROOT_DIR/workflows, not $ZOWE_ROOT_DIR/files/workflows.

## Pages to Update

https://docs.zowe.org/stable/user-guide/install-zos.html
multiple laces and likely sub-documents

## Screenshots

none

## Expected behavior

mention correct location

## Additional context

none

**Comment by nannanli** [comment]
@sn666239
