### ISSUE TITLE
Update location of fingerprint.pax file

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#1343]
## Description

The doc points to the fingerprint.pax file, but in BOX.  The pax file has now moved to GitHub, here:
zowe/zowe-install-packaging/files/fingerprint.pax

## Pages to Update

https://github.com/zowe/docs-site/blob/fingerprint/docs/troubleshoot/verify-fingerprint.md

## Additional context

https://github.com/zowe/zowe-install-packaging/pull/1553

**Comment by nannanli** [comment]
The link is updated to `https://github.com/zowe/zowe-install-packaging/blob/staging/files/fingerprint.pax` at this point (see [the verify fingerprint topic](https://github.com/zowe/docs-site/blob/docs-staging/docs/troubleshoot/verify-fingerprint.md)). Need to update it to `https://github.com/zowe/zowe-install-packaging/blob/master/files/fingerprint.pax` when v1.14 is released.
