### ISSUE TITLE
Enhance Zowe doc SEO 

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1374]
To make the docs more discoverable for users, the docs should be optimized to be more crawler friendly. When a user types a question into a search engine that is answerable by Zowe documentation, it is expected that Zowe docs appear in the results. Also when a user looks for some related technology or keywords, it would be ideal that Zowe sites or content can be discovered ti increase traffic to the sites. 

This issue tracks the Search Engine Optimization (SEO) work for Zowe docs.

**Comment by nannanli** [comment]
@Danieldong1 @Kittyzzq Daniel and Ziqi are looking to contribute to Zowe docs in this aspect. Adding them here to provide best practices and some progress that has been made.

**Comment by Danieldong1** [comment]
The overall goal is to utilize SEO practices that are customized for technical content to improve the organic discoverability of the Zowe documentation site (https://docs.zowe.org/). Discoverability can be measured by the amount and trend of organic traffic. 
As mainstream search engines, primarily Google, focuses on the user's search experience, to make content more friendly to search engines will improve content overall UX.

We will do optimizations from the following aspects to achieve this goal:
1. Keyword research and on-page SEO: Find out the keywords that are used by the target users to find Zowe and deploy them to the content. 
2. Technical SEO: Inspect the technical details of the website to find potential optimization area.
3. Backlink building: Promote Zowe doc by building more outbound links through social sharing.

Currently, we have created a sorted keyword list that contains all the key data to help determine the value of each keyword. We are working on deploying the first 20 keywords to the corresponding pages and HTML tags.

When the keywords are deployed, we will observe the change of the target pages' search performance.

We will keep the SEO efforts on track in this issue. If you are interested in reading more about SEO for tech content, check out our [SEO for Technical Content Site](https://w3.ibm.com/w3publisher/seo-for-technical-content) on W3 Publisher:)

**Comment by samanthasusu** [comment]
Close as #1423 is merged.
