### ISSUE TITLE
Add Zowe Explorer to zowe.org landing page

### ISSUE THREAD

**Issue by zdmullen** [zowe/docs-site#1432]
As someone interested in Zowe and working in modern IDEs, I would like to know about Zowe Explorer immediately upon entry to the zowe.org site. 

## Is your request for enhancement related to a problem? Please describe.
Currently Zowe Explorer is not listed among the "main components" of Zowe on the zowe.org landing page. With over 15,000 downloads and a great deal of use in several COBOL training courses, I think that Zowe Explorer qualifies as a particularly significant component to Zowe. 

## Describe the solution you'd like
Add Zowe Explorer with a brief overview of its functionality to the list of main components.

## Related doc pages
zowe.org main page

**Comment by nannanli** [comment]
+1 to this enhancement. Thank you for raising this issue! Also the demo video should be updated at the same time to show the Zowe Explorer UI. 
adding @IgorCATech here

**Comment by IgorCATech** [comment]
@nannanli Very true. We should prioritize this work in the future @zdmullen
