### ISSUE TITLE
Move 'software agreements' from 'Overview' to 'Appendix'

### ISSUE THREAD

**Issue by chentingcathy** [zowe/docs-site#144]
In section 'Overview': 
Shall we put topic [Zowe CLI Third-Party software agreements](https://zowe.github.io/docs-site/user-guide/overview.html#zowe-cli-third-party-software-agreements) and topic
[ Zowe API Mediation Layer Third-Party software agreements](https://zowe.github.io/docs-site/user-guide/overview.html#zowe-api-mediation-layer-third-party-software-agreements) into a new section like 'Appendix'? I suppose we could put the 'not that important' information to an inconspicuous place like appendix.

**Comment by janan07** [comment]
I agree. An appendix seems like an appropriate place to move the TPSRs.

**Comment by JamesBauman** [comment]
OK by me - we're not bound by our internal rules (attached to Rel Notes) so lets do what makes sense and enhances UX. However, i do suggest that we mention them where they currently reside link to the appendix that contains the TPSRs....

**Comment by MarkAckert** [comment]
I'll get back to you on this for GA 1.0.0, but for all Open Betas until 1.0.0 - we should keep them in as part of the existing license.

**Comment by nannanli** [comment]
This is done in 1.0. Closing. @BrandonJenkins14 @JamesBauman Feel free to reopen if any work remains.
