### ISSUE TITLE
references to old names in "Installing and configuring the Zowe cross memory server (ZWESISTC)"

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#1450]
## Description
In one of the previous releases we stopped using SISLOAD, and some doc updates were done for that, but there are still some references to it in the docs.

## Pages to Update
https://docs.zowe.org/stable/user-guide/configure-xmem-server.html#load-module

## Expected behavior
changes remaining references to use correct name (SZWEAUTH)

[configure-xmem-server.txt](https://github.com/zowe/docs-site/files/5387190/configure-xmem-server.txt)

**Comment by nannanli** [comment]
This has been fixed. See https://github.com/zowe/docs-site/pull/1457/files. Closing.
