### ISSUE TITLE
Update the Zowe overview video on zowe.org

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1538]
The Zowe overview video on the Zowe website is out-of-date. It does not reflect the latest Zowe components and functionalities. 

Need to create a new one to replace it.

**Comment by nannanli** [comment]
A new video created by Joe @Joe-Winchester  is now available for review: https://ibm.box.com/s/n2rge00886etr5fy1pfkf1xch2obs04x 

Please send feedback on this video draft as a comment on this issue.

**Comment by Joe-Winchester** [comment]
FYI @armstro, @ilkinabdullayev, @RASakach.  This is the first pass at a shorter and more current video for zowe.org.  All feedback welcome + please pass on to anyone else who might be interested.

**Comment by Joe-Winchester** [comment]
@ajinrocket - for the overview video I showed on the scrum last Friday the powerpoint deck used is here https://github.com/zowe/community/blob/master/videos/Zowe%20Overview/Zowe%20Overview.pptx and the .mp4 is here https://ibm.ent.box.com/file/771847613523?s=jlmm12slkhgtjztxgyq00q48nei1jdu1.  Let me know if you can't access the box file (I do want to commit it to github but I can't seem to get over the 100MB limit).  Many thanks for wanting to help out and to get Kimberly and others involved.

**Comment by nannanli** [comment]
@ajinrocket Subtitles are added to the video that Joe updated. I can't find Kimberly or Lenny's Github ID here so will post a message to them in Slack to see if they have any further feedback. 
Check out the video draft here (accessible to people with the link only and in low resolution now): https://youtu.be/AFJ00FpAwSQ 
I think we could publish it first to replace the out-of-date video on zowe.org. When all further comments are gathered, we could do a version 2 so basically iteratively improve the video. : )

**Comment by Joe-Winchester** [comment]
@nannanli - Lenny's github ID is https://github.com/DivergentEuropeans.  Not sure if he needs to be added to the doc repo.

**Comment by ajinrocket** [comment]
Hi all! Sorry I've been silent on this issue up until now. I shared the video with Kimberly. After we review the video, we hope to plan a meeting with @Joe-Winchester (and anyone else who is interested), in order to discuss steps to move forward on this project!

**Comment by nannanli** [comment]
The final Zowe overview video draft is here now: https://youtu.be/R-HNy5UTXH4 . Plan to publish it bu end of this week (Feb 25). Any further comments please let us know. We can iteratively update the video. 

Also plan to publish the script and the original deck used for this video on Zowe.org for download in case anyone prefers to read the text or deck.

**Comment by ajinrocket** [comment]
Hello everyone. I reviewed the Zowe overview video a few times and came up with a lot of notes. I'll be organizing them into a power point, then share the presentation with the group. I can just post the slides, or if we can arrange a time to meet I can present them at that time.

**Comment by Joe-Winchester** [comment]
@ajinrocket - many thanks for reviewing the overview video.  It might be great to have a meeting to get together and have you present your feedback.  @nannanli is based in China and I'm in UK. The documentation squad have their scrum next Wednseday 9:30am EST  https://lists.openmainframeproject.org/g/zowe-dev/viewevent?repeatid=32760&eventid=1077197&calstart=2021-03-10 so maybe that's a good time to present or else the same day before/after the doc squad scrum.

**Comment by nannanli** [comment]
@ajinrocket +1 to Joe's proposal. Let's schedule a call after the Zowe doc scrum so Joe can join us.
