### ISSUE TITLE
Fix example in onboarding with plain java enabler

### ISSUE THREAD

**Issue by janan07** [zowe/docs-site#1542]
Describe the bug

The example below https://docs.zowe.org/stable/extend/extend-apiml/onboard-plain-java-enabler.html#api-info in not valid:

apiInfo:
    - apiId: org.zowe.sampleservice
    version: v1
    gatewayUrl: api/v1
    swaggerUrl: http://localhost:10021/sampleservice/api-doc
    documentationUrl: http://your.service.documentation.url
    defaultApi: true
The indentation is not valid, the items under apiId should be at the same level as the apiId
The version should be semver
The apiId should be prefixed just by zowe to match examples in the Zowe conformance criteria - https://www.openmainframeproject.org/projects/zowe/conformance/test-evaluation-guide
https://github.com/zowe/api-layer/wiki/Issue-management

**Comment by balhar-jakub** [comment]
This one was fixed in meantime.
