### ISSUE TITLE
Note additional requirements for CLI users on NPM v7

### ISSUE THREAD

**Issue by zFernand0** [zowe/docs-site#1569]
## Is your request for enhancement related to a problem? Please describe.

In the efforts of supporting NPM v7, the CLI squad had implemented a few workarounds to circumvent some possible issues end users may face when installing the Secure Credential Store plugin. Said workaround includes a new prerequisite.

## Describe the solution you'd like

We may want to add a few note in the section below, stating the prerequisites as per documented in [this commit](https://github.com/zowe/zowe-cli-scs-plugin/commit/931946b3c8d5828ed001232aadbca34385be25ae#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R59)
https://docs.zowe.org/stable/user-guide/cli-scsplugin.html#software-requirements

## Related doc pages

https://docs.zowe.org/stable/user-guide/cli-scsplugin.html#software-requirements

**Comment by JamesBauman** [comment]
This issue can be closed after we publish the v1.26 docs.

**Comment by nannanli** [comment]
v1.26 is live so closing.
