### ISSUE TITLE
Add ICSF as a pre-requisite for Node.js

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#157]
On z/OS, Node requires ICSF to be installed, configured and running.  If not, Node will not start and there will be no error messages to look at.  Therefore we need to document that ICSF is a requirement and tell the user how to verify that it is up and running.  

At the very least, users should be able to see the CSF task in the SDSF DA display.

```SDSF DA S0W1     S0W1     PAG  0  CPU   6               CHARS 'CSF' FOUND      
COMMAND INPUT ===>                                            SCROLL ===> PAGE 
PREFIX=*  DEST=(ALL)  OWNER=*  SORT=JOBNAME/A  SYSNAME=                        
NP   JOBNAME  StepName ProcStep JobID    Owner    C Pos DP Real Paging    SIO  
     CSF      CSF      CSF      STC06228 STCOPER    NS  FE 1793   0.00   0.00  
```
The jobname might also be ICSF
```COMMAND INPUT ===>                                            SCROLL ===> CSR
NP   JOBNAME  StepName ProcStep JobID    Owner    C Pos DP Real Paging    SIO
     ICSF     ICSF     ICSF     STC15832 SYSTASK    NS  F2 1096   0.00   0.00
```

**Comment by hogstrom** [comment]
John,

Is there a way to detect this during the install and let the customer know ?

Matt Hogstrom
matt@hogstrom.org
+1-919-656-0564
PGP Key: 0x90ECB270

I just read a book on Stockholm Syndrome,
it was pretty bad at first, but, by the end I kind of liked it.

**Comment by Joe-Winchester** [comment]
Matt.  We're looking to create an IVT - install verification script - and add things like this (and other places where folks run into problems).  https://github.com/zowe/zowe-install-packaging/issues/109 is the epic to cover this so we should pull together all of the items we find and put them into automated checks (rather than manual ones) in the scripts to avoid all of the 1:1 lengthy (and complex) troubleshooting and make Zowe more self service.

**Comment by ijmitch** [comment]
sounds like the Node team could also use some feedback on this.

**Comment by nannanli** [comment]
@Joe-Winchester @John-A-Davies Hi Joe, John, the system requirements for Zowe is updated. The updates also consolidated all the prereqs for issue #89 . Could you check the updates to ensure that those are all that's required? 
Here is the link to the updated file: https://github.com/zowe/docs-site/blob/7ca98b0db667d9b569c6c5e3b73acde7930ccb7f/docs/user-guide/systemrequirements.md

If you have any corrections to make, you can directly edit that file and submit changes. Many thanks!

**Comment by ijmitch** [comment]
Is the theory that the list under "**z/OS host requirements (for all components)**" is a list of things that are packaged separately, and the list in the table under "**z/OS requirements**" is which components of the z/OS package need to be configured and active?

I think there's still some clarity which could be provided to distinguish which things (packages - the OS, the JDK, Node.js, ...) people might need to add to their system (ie need to be acquired) vs components within those packages which might need activating and configuring in particular way.

Also you have a typo in "**Disk and brower requirements (for Zowe desktop)**".

**Comment by nannanli** [comment]
@ijmitch Sorry for the delay in reply.  Yes, `brower` is a typo which is now fixed. Your understanding is correct that "**z/OS requirements**" lists what people need to configure and activate in order to set up z/OSMF for Zowe. We'll put more thoughts and efforts to distinguish them in doc and update this issue. Thanks!

**Comment by nannanli** [comment]
ICSF requirement has already been documented in User Guide. See https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/systemrequirements.md. 
- The script to verify this config during install is being tracked in https://github.com/zowe/zowe-install-packaging/issues/109
- The improvement to overall sysreq is being tracked in #89. 

Closing this one. Feel free to reopen if any problem persists.
