### ISSUE TITLE
Generating PassTicket requires an additional PTKTDATA profile

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/docs-site#1571]
## Description
We have done some tests to generate PassTicket according to Zowe documentation, but all tests failed. We found out that the security configuration in documentation is incomplete and an additional profile `<applid>` in **CLASS(PTKTDATA)** is required to get it worked.

## Pages to Update
https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-passtickets.html#ca-acf2
https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-passtickets.html#ca-top-secret
https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-passtickets.html#racf

## Expected behavior
The RACF commands to create this additional profile is:
```
RDEFINE PTKTDATA <applid> UACC(NONE)
SETROPTS RACLIST(PTKTDATA) REFRESH
```
The equivalent command for CA Top Secret and CA ACF2 is required

**Comment by NayerNajafi** [comment]
CC: @jackjia-ibm  @jandadav

**Comment by janan07** [comment]
The parameters have been updated with <applid>

https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-security/#certificate-management-script
