### ISSUE TITLE
Add a ZE-related section to the Zowe Overview doc

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#1579]
**Is your feature request related to a problem? Please describe.**

The Zowe Overview section in Zowe Docs doesn't contain any information about Zowe Explorer https://docs.zowe.org/stable/getting-started/overview.html 
The lack of information about ZE in the above-mentioned section decreases the visibility/exposure of the extension and makes it harder for users to find information they are looking for.

**Describe the solution you'd like**

Add a sub-section containing a brief description of the Zowe Explorer sub-component to the Component Overview section https://docs.zowe.org/stable/getting-started/overview.html#component-overview Arrange it in a way the other components look like.

**Comment by jellypuno** [comment]
@IgorCATech transferred to doc site

**Comment by nannanli** [comment]
This issue has been addressed via PR https://github.com/zowe/docs-site/pull/1794.
