### ISSUE TITLE
Docup on ZOWE Prereqs?

### ISSUE THREAD

**Issue by josephperkins50** [zowe/docs-site#1582]
The ZOWE Installation manual states that PERL and PYTHON are not required to be installed on Z/OS but ZOWE.ORG states that Z/OS requires the install.

If these are not required, please docup ZOWE.ORG.

Regards,
Joseph Perkins

**Comment by jackjia-ibm** [comment]
There is "-> Transfer issue" link/button on the right side function panel of this page. But I'm not 100% sure what permission it requires so I just did it. Thanks.

**Comment by samanthasusu** [comment]
Close with instructions [here](https://docs.zowe.org/stable/user-guide/install-nodejs-zos/#installing-the-smpe-edition-of-nodejs---zos). Thanks
