### ISSUE TITLE
Consolidate all Install instructions in one place

### ISSUE THREAD

**Issue by jalel01** [zowe/docs-site#1585]
Based on this recent standalone API ML install experience below, review the install doc to:

- [ ] Ensure zowe doc refers to instructions on APPLYing PTFs in the readme.txt
- [ ] Ensure zowe doc always references instructions found in other sources such as txt files or jcls where appropriate
- [ ] Ensure zowe doc always references the next step(s) in the process
- [x] Adjust doc where it says to set the parameters 'ZWE_LAUNCH_COMPONENTS' in the instance.env file.  There is no such parameter, instead it should read 'LAUNCH_COMPONENT_GROUPS' as that is the value in the instance.env file.

"At different times, I needed to consult the Zowe documentation, readme.txt files, and JCL comments.  It was often unclear where I was to find my next set of instructions.

For example, there is no documentation on the Zowe site regarding applying the PTFs to the Zowe CSI.  It wasn't until I opened the zip file and found the README.TXT that I found the instructions and JCL I needed.  There is no reference to this readme in the documentation and I spent a lot of time searching.

Another area I had some trouble was the SMP/E installation.  I was often flipping back and forth between the documentation and JCL instructions.  However, this may be understandable as the SMP/E steps aren't entirely Zowe specific.  This may be due to my lack of SMP/E experience more than anything."

**Comment by janan07** [comment]
Parm name for standalone installation addressed in PR: [2371](https://github.com/zowe/docs-site/pull/2371) in docs-site

**Comment by janan07** [comment]
This has been addressed in PR [2371](https://github.com/zowe/docs-site/pull/2371)
