### ISSUE TITLE
Typo in manual (zowe 1.19)

### ISSUE THREAD

**Issue by ccc13481** [zowe/docs-site#1600]
On page 337 of the zowe 1.19.0 doc it says:

Note: When using JCEFACFKS as the keystore type, ensure that you define the class to handle the RACF keyring
using the -D options to specify the java.protocol.handler.pkgs property:

Should it not be:

Note: When using JCERACFKS as the keystore type, ensure that you define the class to handle the RACF keyring
using the -D options to specify the java.protocol.handler.pkgs property:

**Comment by covalentbond** [comment]
Can be closed, merged with #1605
