### ISSUE TITLE
[Troubleshooting tip] Error message help for Db2 CLI if the wrong port is specified

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1611]
### 1. Slack conversation link (if any)

```
currently im getting this error and wanted to know if you may know a fix
4:59
DB2 ODBC Driver Error: [node-ibm_db] SQL_ERROR
Error Details:
Error:    [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "9.63.66.57".  Communication function detecting the error: "recv".  Protocol specific error code(s): "10054", "*", "0".  SQLSTATE=08001
SQLCODE:  -30081
SQLSTATE: 08001
```

### 2. Choose a title

Error message help for SQLCODE:  -30081 and SQLSTATE: 08001

### 4. Solution

This message occurs if the secport is being used instead of the unsecured port.  Refer to the DSN400I message.   

Update the https://docs.zowe.org/stable/user-guide/cli-db2plugin.htm page to include this message

**Comment by nannanli** [comment]
@AbhishekJamhoriya will work on this issue. Thank you for taking the time to contribute to Zowe docs!

**Comment by AbhishekJamhoriya** [comment]
Hi, @nannanli please assign me this work.

**Comment by AbhishekJamhoriya** [comment]
Hi, @nannanli made the required changes please check my PR.

**Comment by JTonda** [comment]
We would like to cover all applicable plug-ins.  We will create a draft doc proposal.

**Comment by anaxceron** [comment]
Closing with [PR 2630](https://github.com/zowe/docs-site/pull/2630)
