### ISSUE TITLE
404 on ACF2 z/OSMF setup link 

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/docs-site#1613]
## Description
https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#configuring-z-osmf-2
 ^ This page's ACF2 doc link 404s.

**Comment by ChrisBoehmCA** [comment]
This may be the correct link https://techdocs.broadcom.com/us/en/ca-mainframe-software/security/ca-acf2-for-z-os/16-0/installing/configure-z-os-management-facility-for-ca-acf2.html

**Comment by chinmaym07** [comment]
Can I do this ?

**Comment by nannanli** [comment]
@chinmaym07 Yes, welcome to pick it up and contribute to Zowe docs!  I just assigned this issue to you. 

To get started, follow the instructions here: https://docs.zowe.org/stable/contribute/contributing.html#sending-a-github-pull-request 

Just a reminder that you need to add a `Signed-off-by` line as a part of the commit message. Here is an example Signed-off-by line, which indicates that the submitter accepts the DCO:

```Signed-off-by: John Doe <john.doe@hisdomain.com>```

Fore more information, see [this article](https://docs.zowe.org/stable/contribute/roadmap-contribute.html#send-a-pull-request).  Looking froward to your first PR in Zowe!
