### ISSUE TITLE
Zowe docs UI revamp - design and feedback 

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1626]
This issue tracks the design progress of the new site UI and any feedback on the new UI or site generator. 

- The new UI prototype is at http://zowe-docs-testing.netlify.app/ 
- A demo recording could be found [here](https://zoom.us/rec/share/MrU_xppGD4Vkh24BsxN_Io5Y0ssTO45p7VgNT1KppJpYNo1o18doMDbWbDQLoUVs.Va6xWXwi7bWCh4oz?startTime=1616592944000). You can get a walk-through of the new look and feel.

The related epic for implementation and various features is https://github.com/zowe/docs-site/issues/1587.

For any comments and ideas about the new experience, please add them as a comment on this issue. Any feedback are appreciated.

**Comment by nannanli** [comment]
Some comments from the last squad call: 

- [ ] Does the “Was this page useful” part allow users to enter feedback. It’d be great to let people comment. 
- [ ] The “Edit this page” link is useful and more visible now. Can we make it to create a PR against the docs-staging branch instead of master? 
- [ ] Need to discuss further: How do we keep consistent when restructuring the toc for fitting into the new doc site UI?

**Comment by skurnevich** [comment]
Hi, the layout looks good, but content icons aren't really informative to me. I hardly could match an icon to a subsection without a title. And the contrast on dark theme is also low for some icons, just first impressions of the [prototype](https://zowe-docs.netlify.app), thanks.

**Comment by Martin-Zeithaml** [comment]
Related to #1672:
After clicking on "Email Image" the picture remains zoomed, zoom out click does not work and you need to reload the page (tried in Chrome and Edge, same behavior).

**Comment by covalentbond** [comment]
Hey @Martin-Zeithaml are you talking about this Email Image, I'm unable to reproduce it 😅

![image](https://user-images.githubusercontent.com/53327173/118795283-0efeb980-b8b8-11eb-8dc2-1d20b9224e1a.png)

**Comment by Martin-Zeithaml** [comment]
Let me specify what I did:
Page: https://zowe-docs.netlify.app/stable/getting-started/zowe-architecture/
The first image: "The following diagram depicts the high-level Zowe architecture."
Click on the image.
Image is zoomed in.
Left click on the image, select menu item "Email Image"
Cancel the mailing operation.
Click on the image to zoom out - nothing will happen in Chrome or Edge.
Note: working fine under Internet Explorer.

**Comment by covalentbond** [comment]
@Martin-Zeithaml can you please attach some screenshots or show a demo.

As you said you **Left clicked on the image, selected menu item "Email Image"**. I think once the image is zoomed-in and you left-click it back it just zooms out!. Did you mean right-click?

If you can provide a demo - it would be really helpful in understanding the issue, thanks!

**Comment by Martin-Zeithaml** [comment]
![Anim2](https://user-images.githubusercontent.com/66114686/118824720-5e45e980-b8ba-11eb-9b88-391eda496c45.gif)

**Comment by covalentbond** [comment]
Not sure, why it's happening - tested Email Image with option with default app "Microsoft Mail" and "Gmail". Both works fine in my case. I think this **Email Image** option is in `Firefox only`, no? Couldn't find **Email Image** for chrome or edge. 

Also Zoom out also works with <kbd>Esc</kbd>, that might work for you. 

![Animation1](https://user-images.githubusercontent.com/53327173/119101386-8eb29280-ba36-11eb-8552-d501798c6463.gif)

**Comment by covalentbond** [comment]
Not sure, why it's happening - tested Email Image with option of default app "Microsoft Mail" and "Gmail". Both works fine in my case as shown below. I think this **Email Image** option is in `Firefox only`, no? Couldn't find **Email Image** for chrome or edge. It does seems like Browser Support issue. 

Also Zoom out also works with <kbd>Esc</kbd>, that might work for you. 

![Animation1](https://user-images.githubusercontent.com/53327173/119101386-8eb29280-ba36-11eb-8552-d501798c6463.gif)

**Comment by Martin-Zeithaml** [comment]
I have found the problem, it is the **Symantec Protection plugin** (I can not uninstall it/disable it/change it - company's policy).

This explains, why it does not work under Chrome or Edge, but it is working under Internet Explorer - there is no Symantec plugin in IE.

**Comment by covalentbond** [comment]
@skurnevich can you please have a look at [zowe-docs.netlify.app/](http://zowe-docs.netlify.app/), we have changed the layout as well as the icons, contrast issue. Let us know, if you have any other suggestions!

**Comment by skurnevich** [comment]
Hi @covalentbond, yes, the icons look much better to me, one moment that I find odd now is borders around "I want to..." and "I'm interested in..." sections, but it is really a minor thing, and the UI looks good in general. Thanks!

**Comment by DivergentEuropeans** [comment]
New website looks great, good updated fresh look. Some of my comments, feel free to address if you think it's relevant!

1. The "K" key is a common key for enabling narrator view for accessibility tools. I have mine downloaded in Chrome back when I was testing it, so when I select the key to enter focus into the search bar, my narrator goes off. This may be prevented in JavaScript by doing things like i.e. event.stopPropagation, event.stopImmediatePropagation, event.preventDefault or some combination of them, that should hopefully intercept the keybinding before it reaches browser extension level. If this doesn't work, I probably wouldn't recommend using the "K" key or a variation of it to launch search. Here's a great chart I use to avoid common browser keybinding conflicts: http://dmcritchie.mvps.org/firefox/keyboard.htm

2. I like the site but this banner doesn't fit the rest of it,
![image](https://user-images.githubusercontent.com/20528015/121263581-cf5a3a80-c883-11eb-92d9-0b6c76ace852.png)
could be something like,
![image](https://user-images.githubusercontent.com/20528015/121263734-121c1280-c884-11eb-8086-a71701ec2f42.png)

3. Was there a specific reason why we don't list the older versions of Zowe?
![image](https://user-images.githubusercontent.com/20528015/121264120-ab4b2900-c884-11eb-956b-af5326212d8c.png)

**Comment by covalentbond** [comment]
Hey @DivergentEuropeans, thanks for your feedback

1. I think <kbd>Ctrl</kbd> + <kbd>K</kbd> is also very commonly used for search functionalities. It's also mentioned in the [link](http://dmcritchie.mvps.org/firefox/keyboard.htm) you refered as shown in image below. I've actually no idea about functionality of narrator view for accessibility tools. Can you tell me how this issue can be reproduced?

      ![image](https://user-images.githubusercontent.com/53327173/121265521-8f707300-c8d6-11eb-9120-992df82803f3.png)

2. Sure @PlutoZhang is handling the UI aspects, will consult him once.
3. These two versions have been used just for testing, we will be adding all the versions soon.

**Comment by DivergentEuropeans** [comment]
Yes, sure @covalentbond The reader I use is "Pericles: Text to Speech Screen Reader" you can download it as a Chrome extension

Then use the hotkey in the Zowe site to launch the search. My recommendation is perhaps [ALT] + [P] ? a common search button for "search files" function in Editors and that's what the Zowe Desktop Editor uses. Or Maybe [ALT] + [S] for "search"

**Comment by covalentbond** [comment]
Hi @DivergentEuropeans, as you might be aware of - we are using the[ Algolia Search](https://www.algolia.com/) for the search functionalities. 

I contacted the Algolia Search team regarding customization of the shortcut keys. But unfortunately till yet - there is option of customizing these keyboard shortcuts. Will create an issue to keep a track of this feature once the new website is merged.

**Comment by covalentbond** [comment]
Hi @DivergentEuropeans, as you might be aware of - we are using the[ Algolia Search](https://www.algolia.com/) for the search functionalities. 

I contacted the Algolia Search team regarding customization of the shortcut keys. But unfortunately till yet - there is no option of customizing these keyboard shortcuts. Will create an issue to keep a track of this feature once the new website is merged.

**Comment by nannanli** [comment]
The new site is live now. [Check it out](https://docs.zowe.org/) and send any feedback in this discussion https://github.com/zowe/docs-site/discussions/1742. 

Thank you everyone for your comments and suggestions!!
