### ISSUE TITLE
Zowe chat bot

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1644]
Create and publish a Zowe chatbot that allows users to get answers to questions by interacting with a bot on zowe.org, Zowe doc site, and Zowe Slack channels.

**Comment by service-management-unite** [comment]
### Project overview
**Ask Zowe** chat bot is designed to answer users' questions in slack channels or Zowe website. It uses natural language understanding (NLU) technologies to understand users' intents, and connect to up-to-date content sources to find the most relevant answers. 
You can find the detailed background information and technology architecture in this deck: 
[Ask Zowe Slackbot.pptx](https://github.com/zowe/docs-site/files/6702054/Ask.Zowe.Slackbot.pptx)

### Project status
- [x] 06.14 - 06.18: **1st round internal test and training** -- Ashley, Cathy, and Pluto from Zowe content design team test and train the bot.
- [ ] 06.21 - 06.25: **Next step planning** 
- [ ] 06.28 - 07.02: **2nd round test** -- Invite members from the Zowe team to test and solicit feedback.
- [ ] 07.05 - 07.09: **2nd round training** -- Add training data based on the test results to improve its performance.
- [ ] 07.12 - 07.16: **Playback** -- Present in the Zowe team and solicit final comments/feedback.
- [ ] 07.19 - 07.23: **Implementation** -- TSC vote to decide how to distribute the chatbot (deliver the slackbot, embed the chatbot in the doc site, or both).
- [ ] 07.26 - 07.30: **Deliver** the chatbot.
