### ISSUE TITLE
Open images in new tab

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/docs-site#1672]
## Is your request for enhancement related to a problem? Please describe.
The images (especially the large one) are not links and can not be open in new tab (via single click).
For example, the architecture diagram is small (not readable) and you need to open it in the new window (right click and select Open in new tab or window):
https://docs.zowe.org/stable/getting-started/zowe-architecture.html

## Describe the solution you'd like
Make it same as in the MD:
https://github.com/zowe/docs-site/blob/master/docs/getting-started/zowe-architecture.md
Each picture is wrapped by a link to the picture and when clicked it is opened in new tab.

## Related doc pages
docs.zowe.org --> all pages with images

**Comment by covalentbond** [comment]
Hey @Martin-Zeithaml, I really liked your concern.

But I feel adding link and opening image in `new tab` or `window` can be a bad user-experience. To solve the issue of images not being readable - what about giving an option to users to zoom the image `onClick()` which will:

- Bring the image in focus.
- Hide all the other components.
- Showcase a zoomed version of the image in the middle of the window as shown below.

![Animation](https://user-images.githubusercontent.com/53327173/118696278-c26d9c80-b82b-11eb-957c-2548171c34a7.gif)

This will mainly prevent more actions required by user and will not redirect to a new page. You can test this feature on this [prototype](https://zowe-docs.netlify.app/stable/getting-started/zowe-architecture) of the Zowe Doc website as well. We are in the middle of the revamp project of the docs.zowe.org. This feature could be live once the revamp project is completed!

Other than this, we are adding more some more features, please let us know if you have some feedback [here](https://github.com/zowe/docs-site/issues/1626) :)

**Comment by covalentbond** [comment]
Hey @Martin-Zeithaml, solution to small image size could be a good idea to be considered.

But I feel adding link and opening image in `new tab` or `window` can be a bad user-experience. To solve the issue of images not being readable - what about giving an option to users to zoom the image `onClick()` which will:

- Bring the image in focus.
- Hide all the other components.
- Showcase a zoomed version of the image in the middle of the window as shown below.

![Animation](https://user-images.githubusercontent.com/53327173/118696278-c26d9c80-b82b-11eb-957c-2548171c34a7.gif)

This will mainly prevent more actions required by user and will not redirect to a new page. You can test this feature on this [prototype](https://zowe-docs.netlify.app/stable/getting-started/zowe-architecture) of the Zowe Doc website as well. We are in the middle of the revamp project of the docs.zowe.org. This feature could be live once the revamp project is completed!

Other than this, we are adding more some more features, please let us know if you have some feedback [here](https://github.com/zowe/docs-site/issues/1626) :)

**Comment by covalentbond** [comment]
Hey @Martin-Zeithaml, solution to small image size issue could be a good idea to be considered.

But I feel adding link and opening image in `new tab` or `window` can be a bad user-experience. To solve the issue of images not being readable - what about giving an option to users to zoom the image `onClick()` which will:

- Bring the image in focus.
- Hide all the other components.
- Showcase a zoomed version of the image in the middle of the window as shown below.

![Animation](https://user-images.githubusercontent.com/53327173/118696278-c26d9c80-b82b-11eb-957c-2548171c34a7.gif)

This will mainly prevent more actions required by user and will not redirect to a new page. You can test this feature on this [prototype](https://zowe-docs.netlify.app/stable/getting-started/zowe-architecture) of the Zowe Doc website as well. We are in the middle of the revamp project of the docs.zowe.org. This feature could be live once the revamp project is completed!

Other than this, we are adding more some more features, please let us know if you have some feedback [here](https://github.com/zowe/docs-site/issues/1626) :)

**Comment by Martin-Zeithaml** [comment]
Feature is ok, I have found some bug there and I will mention it in #1626.
