### ISSUE TITLE
Add ZOWE WA plugin documentation

### ISSUE THREAD

**Issue by zszabo14** [zowe/docs-site#1687]
Add ZOWE WA plugin documentation

ZOWE WA plugin section in https://docs.zowe.org/stable/web_help/index.html

**Comment by MichaelABroadcom** [comment]
@zszabo14 Do you have a PR or issue opened for the Zowe WA plugin? If so, can you supply that here? Thanks!

**Comment by zszabo14** [comment]
@MichaelABroadcom No. I don't have.

**Comment by MichaelABroadcom** [comment]
@zszabo14 Thank you for getting back to me. Do you have the information about the plug-in to add to the documentation?

**Comment by zszabo14** [comment]
https://www.yourautomationhub.io/detail/zowe

but more details and samples...

**Comment by MichaelABroadcom** [comment]
@zszabo14  I conferred with the doc squad and the onboarding team for Zowe.   You will need to submit the documentation for your plugin to the docs-site repo. For the plugin to be documented in the webhelp and CLI help, you will need to bundle your plugin to be included with the CLI.  The following links take you to the Zowe help pages that explain how to submit your code and documentation to the Zowe repository:
- Contribute to Zowe: https://docs.zowe.org/stable/contribute/roadmap-contribute.html
- Contribute to Zowe docs: https://zowe-docs.netlify.app/stable/contribute/contributing

Please let me know if you have further questions. I can direct you to the appropriate resource.

**Comment by JamesBauman** [comment]
We have not had additional communication with this customer for more than one yr.  We presume that the customer abandoned the request.  We are closing the issue.
