### ISSUE TITLE
Zowe doc site UX revamp testing

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1721]
This issue tracks the pre-migration testing results of the new Zowe doc site UX.  Please list the issues you find as a comment in the following format.  

Beta preview site link: https://zowe-docs-testing.netlify.app/ 

- [x] Issue 1
- [x] Issue 2

**Comment by nannanli** [comment]
Tested on Jun 17
- [ ] Installation roadmaps not working. 
- [ ] The versions numbers do not indicate which version is LTS while it previously did. 
- [ ] Might be an issue: Homepage is always the latest for archived versions 
- [ ] PDF: There is no page number in the PDF file so it might be hard for users to navigate and locate content.
- [ ] PDF: Some inline links are not working.
- [ ] PDF: Table display - truncated for complex tables

**Comment by MichaelABroadcom** [comment]
Beta preview site link: https://zowe-docs-testing.netlify.app/

- [ ]  Dark Mode: Blue text on gray background is hard to read.

**Comment by DivergentEuropeans** [comment]
Was just about to write what Michael said. Very nitpicky here, but I think the blue is a little difficult on the eyes. I'm fortunate to have full color vision but others may not be so lucky, maybe we lighten up the text to have more contrast (I know the original blue is the same blue as is used in the banner)

![image](https://user-images.githubusercontent.com/20528015/122804753-45a06900-d296-11eb-87df-a4729b296ec8.png)


->

![image](https://user-images.githubusercontent.com/20528015/122804793-518c2b00-d296-11eb-8b1a-c460f05630fc.png)

**Comment by covalentbond** [comment]
Hey @DivergentEuropeans, can you share the hexa code of the color you used in the mock. I'll update it

**Comment by PlutoZhang** [comment]
The display of the note need to be checked and updated.

https://zowe-docs-testing.netlify.app/stable/extend/extend-desktop/mvd-extendingzlux/#sample-react-app
<img width="836" alt="Screen Shot 2021-06-22 at 3 45 47 PM" src="https://user-images.githubusercontent.com/38718951/122884806-14e13200-d371-11eb-9bc6-1106ecfdbb3d.png">

**Comment by PlutoZhang** [comment]
- [ ] The links doesn't work.

https://zowe-docs-testing.netlify.app/stable/getting-started/summaryofchanges#version-1-20-1-lts-march-2021

<img width="254" alt="Screen Shot 2021-06-22 at 3 55 38 PM" src="https://user-images.githubusercontent.com/38718951/122886181-4c9ca980-d372-11eb-94b6-3a17ece954dd.png">

**Comment by MikeBauerCA** [comment]
The search sometimes takes you to old versions of doc.
![image](https://user-images.githubusercontent.com/35504792/123273671-d95d7980-d4d0-11eb-9b93-769aae9200c1.png)

Each result is to a different version of the doc. For example, the first one directs me to v1.12:
![image](https://user-images.githubusercontent.com/35504792/123273840-fbef9280-d4d0-11eb-955b-6c99fd22275e.png)

The second result directs me to v1.10:
![image](https://user-images.githubusercontent.com/35504792/123273968-17f33400-d4d1-11eb-8a17-e2b092bbfe9a.png)

My concern is users will begin browsing outdated documentation accidentally.

**Comment by covalentbond** [comment]
### Major Issue❗️:

Any other doc page except the homepage falls in an infinite refresh loop/network requests.
This issue does not occurs when a doc page is navigated from homepage.

For eg. https://zowe-docs-testing.netlify.app/stable/user-guide/install-zos

We shall probably wait to publish this, until this issue is fixed.

**Comment by mirekstrnad** [comment]
- [ ] Tiles on the dashboard have no hover effect when mouse over
![Screenshot 2021-07-01 at 13 27 41](https://user-images.githubusercontent.com/5415797/124117347-4f815380-da70-11eb-9b78-1ccc8e922567.png)

- [ ]  Pictures in tiles are bitmap not SVG, this makes them to look blurry on high-res screens
![Screenshot 2021-07-01 at 13 29 22](https://user-images.githubusercontent.com/5415797/124117456-750e5d00-da70-11eb-9fea-8d81c3e632c2.png)

- [ ] Learn more button/component has no hover effect when mouse over
![Screenshot 2021-07-01 at 13 30 36](https://user-images.githubusercontent.com/5415797/124117527-89eaf080-da70-11eb-8745-36aa3fc44a90.png)

- [ ] Hover effects are not consistent, all looks the same, but first is underlined, the second has no hover effect and the third is a dropdown menu.
![Screenshot 2021-07-01 at 13 31 42](https://user-images.githubusercontent.com/5415797/124117680-b43cae00-da70-11eb-9913-b61abc21636b.png)

**Comment by nannanli** [comment]
The new site is live now. [Check it out](https://docs.zowe.org/) and send any further feedback or issues encountered in this discussion https://github.com/zowe/docs-site/discussions/1742. 

Thank you everyone for your testing and suggestions!!
