### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/install-zowe-smpe/

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1798]
## Description
Feedback from a UX study that the DASD storage requirements in both DOC and JCL supplied with PTFs is inaccurate.
Creating the issue to track this and any subsequent discussions.  

## Pages to Update
https://docs.zowe.org/stable/user-guide/install-zowe-smpe/#dasd-storage-requirements

**Comment by Joe-Winchester** [comment]
@OnnoVdT or @NayerNajafi , do you have any background for how we came up with these numbers and how we can verify them and if needed get some more accurate numbers ?

**Comment by IgorCATech** [comment]
Thanks for creating an issue, Joe. Here's a PR that tackles this (and 2 more) doc issue https://github.com/zowe/docs-site/pull/1797. Once we know the correct requirements, I'll take care of the doc.

**Comment by NayerNajafi** [comment]
@Joe-Winchester , the space value we have in Program Directory for IBM Z Distribution for Zowe V1.0.0 is different from the values on Zowe.org docs.
![image](https://user-images.githubusercontent.com/44011615/130240626-3ac0c7de-7ce0-485f-972c-a2ed127afa5c.png)

**Comment by IgorCATech** [comment]
Should I edit the article to include the abovementioned figures?

**Comment by NayerNajafi** [comment]
I confirm the values provided in Program Directory are the right values. Zowe documentation should be updated to the correct values.

**Comment by OnnoVdT** [comment]
thanks Nayer
