### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/install-zos/systemrequirements.html

### ISSUE THREAD

**Issue by david-dbsh** [zowe/docs-site#1800]
Broken link

## Description
 Clicking on link in box "Ensure system requirements are met", the target web page is not found. The broken link is https://docs.zowe.org/stable/user-guide/install-zos/systemrequirements.html

## Pages to Update
https://docs.zowe.org/stable/user-guide/install-zos/

## Expected behavior
Link to target page

**Comment by nannanli** [comment]
Thank you for reporting the issue! All the links in that roadmap have been updated via commit https://github.com/zowe/docs-site/commit/05e7bf22449630b8e5d1af93380e083c6fd7fe64. Check out the doc site: https://docs.zowe.org/stable/user-guide/install-zos/  and let us know if the issue persists.
