### ISSUE TITLE
Hyperlinks does not work 

### ISSUE THREAD

**Issue by achmelo** [zowe/docs-site#1804]
## Description

When I try to follow any hyperlink in the https://docs.zowe.org , it results in PAGE NOT FOUND error.
Steps to reproduce:
1. Go to https://docs.zowe.org/stable/extend/extend-apiml/onboard-plain-java-enabler/#custom-metadata
2. Click on the link [here]
3. You would be redirected to an 

error page

## Screenshots
![Screenshot 2021-08-25 at 13 48 12](https://user-images.githubusercontent.com/37397715/130785314-bc9d7fd9-85a7-4aaa-81ba-bab16616c465.png)

## Expected behavior
Hyperlinks will route to correct destination.

**Comment by shravanatirtha** [comment]
Hi, I would like to work on it. Is it still available?

**Comment by janan07** [comment]
[PR 1808](https://github.com/zowe/docs-site/pull/1808) addresses this broken link
