### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/install-ha-sysplex

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#1809]
## Description

> Ensure that the software requirements are met. The prerequisites are described in [Zowe high availability requirements (host)](https://docs.zowe.org/stable/user-guide/systemrequirements).

The link to **Zowe high availability requirements (host)** at https://docs.zowe.org/stable/user-guide/install-ha-sysplex does not point to HA requirements but to general requirements (https://docs.zowe.org/stable/user-guide/systemrequirements).

## Pages to Update

https://docs.zowe.org/stable/user-guide/install-ha-sysplex

## Expected behavior

I would expect the like to point to a page describing Zowe high availability requirements.

**Comment by AbhishekJamhoriya** [comment]
is this issue still open @nannanli

**Comment by AbhishekJamhoriya** [comment]
if yes i will like to work on it. so please assign me this issue.

**Comment by nannanli** [comment]
@AbhishekJamhoriya Thank you for picking it up! It's assigned to you now. We'll take a look at your PR.

**Comment by nannanli** [comment]
@NayerNajafi Hi Nayer, as Petr pointed out, now the system requiremenrts for HA point to the general Zowe one (https://docs.zowe.org/stable/user-guide/systemrequirements) where there is a bullet point saying that: 
>(Optional, recommended) Parallel Sysplex.
>To deploy Zowe for high availability, a Parallel Sysplex environment is recommended. Please check Configuring Sysplex for high availability for more information.

Does it make sense to create a system requirements page for HA where all HA specific requirements are consolidated?

**Comment by NayerNajafi** [comment]
@nannanli Hi Ashley, I agree with Petr. **Zowe high availability requirements (host)**  in https://docs.zowe.org/stable/user-guide/install-ha-sysplex/ should point to https://docs.zowe.org/stable/user-guide/configure-sysplex#sysplex-environment-requirements.

**Comment by AbhishekJamhoriya** [comment]
Hi @nannanli  ,So basically  whenever someone clicks on Zowe high availability requirements (host)  he/she should be redirected to this page (https://docs.zowe.org/stable/user-guide/configure-sysplex#sysplex-environment-requirements) .correct me if i am wrong.

**Comment by nannanli** [comment]
@AbhishekJamhoriya yes, you're correct. So basically need to update the HA requirement link from https://docs.zowe.org/stable/user-guide/systemrequirements to https://docs.zowe.org/stable/user-guide/configure-sysplex#sysplex-environment-requirements on this page: https://docs.zowe.org/stable/user-guide/install-ha-sysplex/ 

There are two occurences: 

- On the installation roadmap. 
   <img width="829" alt="image" src="https://user-images.githubusercontent.com/14340789/134446151-02f2f514-1300-4c95-a219-2b6e2f260008.png">
- In this section: https://docs.zowe.org/stable/user-guide/install-ha-sysplex/#stage-2-install-the-zowe-runtime 

Would you please update PR #1845 to reflect the change? Thank you!

**Comment by AbhishekJamhoriya** [comment]
@nannanli  updated PR #1845 . please check.

**Comment by nannanli** [comment]
PR #1845 was merged. Closing. 
Thanks for @AbhishekJamhoriya's contribution!
