### ISSUE TITLE
Feature support table

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/docs-site#1811]
## Is your request for enhancement related to a problem? Please describe.

Recently an issue was opened for IPv6 support (zowe/community#1024). Zowe CLI supports this and we were seeking an appropriate place to document the support. It didn't seem like it belonged specifically in the CLI component doc because IPv6 support is more broad as an initiative. 

## Describe the solution you'd like

After discussing with the TSC, I would like to open a request to document larger cross-component initiatives in the form of a table. These initiatives would include things like token support for MFA, Single Sign-on, IPv6 support, etc. We probably have some work to do to define everything that belongs in this table but perhaps these three items would be a good start.

**Comment by JamesBauman** [comment]
There is an article published re IPv6. Does it resolve the issue? 

https://docs.zowe.org/stable/getting-started/zowe-feature-support/

**Comment by samanthasusu** [comment]
Close for now as the page is removed.
