### ISSUE TITLE
Why four slashes after safkeyring: ? Why not just two?

### ISSUE THREAD

**Issue by GrahamHannington** [zowe/docs-site#1828]
## Description
The Zowe docs refer to `safkeyring:////`, with four consecutive slash characters following the colon.

Why four? Why not just two?

For example (just to pick one among many), see [Creating Security Key Lifecycle Manager for z/OS configuration file](https://www.ibm.com/docs/en/sklmfz/1.1.0?topic=csklmz-creating-security-key-lifecycle-manager-zos-configuration-file).

## Pages to update
This issue occurs in various pages in the Zowe docs. For example:

https://docs.zowe.org/stable/user-guide/configure-instance-directory

Source file: [`docs-site/docs/user-guide/configure-instance-directory.md`](https://github.com/zowe/docs-site/blob/master/docs/user-guide/configure-instance-directory.md)

## Expected behavior
Two consecutive slashes should be enough. (There's a joke in there involving Australian slang, but I'll let it pass. 😃)

I gather that four consecutive slashes works, but it looks very odd to me.

Am I missing something? Is there some "escaping" behavior going on here, in the context of Zowe configuration files, that collapses those four slashes down to two? (If so, where is that behavior described?)

## Additional context
I wish the docs for [com.ibm.crypto.ibmjcehybrid.provider.safkeyring](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=SSYKE2_8.0.0/com.ibm.java.zsecurity.api.80.doc/com.ibm.crypto.ibmjcehybrid.provider/com/ibm/crypto/ibmjcehybrid/provider/safkeyring/package-summary.html) offered clearer advice on the `safkeyring://` format.

I believe it's valid to omit the user ID, if the current user is the key ring owner (note the three consecutive slashes following the colon):

````
safkeyring:///MYring
````

**Comment by 1000TurquoisePogs** [comment]
It's not a documentation mistake, the servers really need 4 slashes there.
I don't know the fully story but the app server (powers the desktop) doesn't need 4 slashes internally but respects it due to some limitation in the java code (either zowe or inhereted by zowe).

**Comment by GrahamHannington** [comment]
Thanks for the reply. Interesting:

> the servers really need 4 slashes there.

I don't want to raise anyone's hackles—I'm just gonna leave it here, and move on—but I would be strongly tempted to call that a bug. At best: an unfortunate idiosyncrasy that has the potential to confuse users who are familiar with the 2 slashes used in other contexts, outside of Zowe.

**Comment by daveyc** [comment]
Just to close this out the extra escape characters are required because of the way spring-boot parses the keyStore URL. This is specific to embedded tomcat. The code is[ here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/tomcat/SslStoreProviderUrlStreamHandlerFactory.java)
