### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/release-notes/v1_24.html

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#1843]
## Description

I used the Release Notes link on the Zowe landing page. But the page was not found.

## Pages to Update

https://www.zowe.org/

## Screenshots

![image](https://user-images.githubusercontent.com/7644758/134138443-0a76528b-7992-46ab-befe-a548abbcea85.png)

**Comment by nannanli** [comment]
The doc build caused this issue. It has been resolved. Check out this page: https://docs.zowe.org/stable/getting-started/release-notes/v1_24

**Comment by plavjanik** [comment]
Thank you!
