### ISSUE TITLE
Incorrect basePath for CLI profile to APIML

### ISSUE THREAD

**Issue by gejohnston** [zowe/docs-site#1848]
## Description

I believe that the format of basePath is incorrect in the doc for configuring a CLI profile for use with APIML.

## Pages to Update

https://docs.zowe.org/stable/user-guide/cli-usingcli/#accessing-a-service-through-api-ml

## Expected behavior

I believe that this doc reflects the original APIML format for a basePath, but I think that format has changed.

Old values:
    https://myapilayerhost:port/api/v1/zosmf
    --base-path api/v1 

Should be changed to:
     https://myapilayerhost:port/ibmzosmf/api/v1
    --base-path ibmzosmf/api/v1 

## Additional context

You should confirm this suggested update with other engineers familiar with the configuration values.

**Comment by AbhishekJamhoriya** [comment]
@gejohnston  can i work on this issue ,please assign me this issue.

**Comment by nannanli** [comment]
Hi @aimmta, Abhishek would like to pick up this issue. Would you please add the CLI SME to this issue to confirm the required changes?

**Comment by AbhishekJamhoriya** [comment]
Hi @nannanli made the desired changes please check my PR.

**Comment by nannanli** [comment]
PR #1851 closes this issue. Thanks to @AbhishekJamhoriya!
