### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/mvd-configuration.md

### ISSUE THREAD

**Issue by BLJeffery66** [zowe/docs-site#1880]

**Comment by 1000TurquoisePogs** [comment]
I'm unsure where this occurs but notice that if you remove the .md at the end, it works.
However, as one of the major developers of that part of Zowe, I noticed the page was also in need of several updates.
For now, I recommend reading my corrected version and it will probably be put onto the official website shortly: https://github.com/zowe/docs-site/blob/6ec143b783a873e9aa05317c075655e730fbb053/docs/user-guide/mvd-configuration.md
