### ISSUE TITLE
Installing user must be able to set -a extattr

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#189]
The doc should say that the user performing the install must have authority to set the '-a' extattr flag, which requires at least READ access to the RACF CLASS named BPX.FILEATTR.APF.  It is not essential for this access to be enabled before you run `zowe-install.sh`, but if not enabled then, it must be enabled before you run `zowe-runtime-authorize.sh`.

**Comment by nannanli** [comment]
@John-A-Davies Hi John, the statement is added. Please review this change: https://github.com/zowe/docs-site/commit/dba8166d45a82bdf0d8f2633df7c6992b2ea670a and let me know it it works. Thanks!

**Comment by nannanli** [comment]
This statement was added in 0.9.5 and previous releases. Closing.
