### ISSUE TITLE
BPX.DEAMON should be BPX.DAEMON

### ISSUE THREAD

**Issue by rjmaomao** [zowe/docs-site#1902]
In [https://docs.zowe.org/stable/user-guide/systemrequirements-zos/#zwesvusr](https://docs.zowe.org/stable/user-guide/systemrequirements-zos/#zwesvusr)

Under "User ID Requirements" section, for id ZWESVUSR
  
<img width="948" alt="image" src="https://user-images.githubusercontent.com/44960894/142819789-2acf1213-46d0-41f4-b988-eb10613a2cd0.png">

  BPX.DEAMON should be BPX.DAEMON

**Comment by balhar-jakub** [comment]
It's been fixed. Thanks for noticing and reaching out. :-)
