### ISSUE TITLE
Broadcom Products Re-branding in Zowe Docs

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#1905]
As part of the Broadcom re-branding effort, we need to ensure that the product names mentioned in Zowe Docs are in line with this change - any obsolete references (typically, these that have "CA" in the name) should be replaced with the new names. To check out the new names, see the [(Broadcom)  Product name changes.xlsx](https://github.com/zowe/docs-site/files/7595457/Broadcom.Product.name.changes.xlsx) attached spreadsheet. 

## Is your request for enhancement related to a problem? Please describe.

The request is related to the change that happened to the Broadcom products that are mentioned in Zowe Docs. Current names differ from the actual (re-branded) names and might confuse the reader.

## Describe the solution you'd like

In order for users not to be confused with the product names, we need to update any Broadcom product names across all relevant pages.

## Additional context

17 occurrences of "CA ACF2" and 19 occurrences of "CA Top Secret" were found

**Comment by nannanli** [comment]
The re-branding work is complete. Closing but feel free to reopen if any work remains.
