### ISSUE TITLE
Change installation diagram on install zOS page

### ISSUE THREAD

**Issue by zeibura** [zowe/docs-site#1912]
## Description
The diagram on the install zOS page needs to be updated to add the option of installing via z/OSMF workflows and to remove the SMPE section (except the SMPE shell step)

## Pages to Update
docs.zowe.org/stable/user-guide/install-zos

## Screenshots
Rough draft from Pavel Zlatník attached - the arrow from the ZWE9MNT box should go straight to the z/OSMF workflow one time setup box.

## Additional context
We (at Broadcom) are still not sure where that diagram is generated.

**Comment by zeibura** [comment]
![image (2)](https://user-images.githubusercontent.com/49559040/144088402-e5e736ee-2e1c-43a0-bb84-7a51824e8646.png)

**Comment by nannanli** [comment]
The diagram has been updated. See https://docs.zowe.org/stable/user-guide/install-zos/. Closing. 

here is a quick overview. 
![image](https://user-images.githubusercontent.com/14340789/150919048-06781b50-7a22-4863-98fa-5b80ed51faf1.png)
