### ISSUE TITLE
Out-of-date link 

### ISSUE THREAD

**Issue by samanthasusu** [zowe/docs-site#1939]
## Description
On the [Using Zowe SDKs](https://docs.zowe.org/stable/user-guide/sdks-using/) page, the link for [npm semver](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) is invalid. 

## Pages to Update
The [Using Zowe SDKs](https://docs.zowe.org/stable/user-guide/sdks-using/) page.

## Screenshots
![截屏2021-12-23 上午9 43 00](https://user-images.githubusercontent.com/95402892/147174845-3ed63764-3300-4a8d-8516-624091d533f7.png)

## Expected behavior
 Please update it to the latest one. Many thanks.

**Comment by JamesBauman** [comment]
Updated doc and created a PR: https://github.com/zowe/docs-site/pull/1942
