### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/install-zowe-pswi-acquire

### ISSUE THREAD

**Issue by ehrocha** [zowe/docs-site#1944]
## Description
Remove the continuation (comma) from this line:
//USSBATCH EXEC PGM=BPXBATCH,

The sample has incorrect JCL statements :
//STDOUT DD=SYSOUT=*
//STDERR DD=SYSOUT=*
//STDPARM DD=SYSOUT=*

This should read as :
//STDOUT DD SYSOUT=*
//STDERR DD SYSOUT=*
//STDPARM DD *

## Pages to Update
https://docs.zowe.org/stable/user-guide/install-zowe-pswi-acquire

## Screenshots
![image](https://user-images.githubusercontent.com/355929/147768024-a9cd93b8-d9b7-4c7f-9ce8-db120326534a.png)

## Expected behavior
Correct the JCL statements 
//STDOUT DD SYSOUT=*
//STDERR DD SYSOUT=*
//STDPARM DD *

**Comment by nannanli** [comment]
@zeibura @janan07 Would you please take a look at this issue? Thank you!

**Comment by zeibura** [comment]
Done: https://github.com/zowe/docs-site/pull/1952
