### ISSUE TITLE
Add APIML Metrics Service demo video

### ISSUE THREAD

**Issue by CarsonCook** [zowe/docs-site#1953]
## Is your request for enhancement related to a problem? Please describe.
Users may want a video describing the metrics service in the APIML.

## Describe the solution you'd like
Add a demo video.

## Related doc pages

- Markdown source: docs/user-guide/api-mediation-metrics-service.md 
- Online: https://docs.zowe.org/stable/user-guide/api-mediation-metrics-service

## Additional context
@nannanli this is referencing #zowe-api you mentioned might be good to add. Video is too big to attach here, but I have a copy.
Video in slack: https://openmainframeproject.slack.com/archives/CC5UUL005/p1638381402028000

**Comment by nannanli** [comment]
The video has been uploaded to https://youtu.be/KkuE6xADxPk.
