### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/appendix/tpsr.html

### ISSUE THREAD

**Issue by SMFox90** [zowe/docs-site#1964]
## Description
Navigating to the page listed above from the LEGAL page, I was met with "page not found." 
https://www.zowe.org/legal.html

**Comment by nannanli** [comment]
Thank you for reporting this issue! This is duplicate with this issue https://github.com/zowe/zowe.github.io/issues/307 so closing this one and all updates will be tracked in https://github.com/zowe/zowe.github.io/issues/307.
