### ISSUE TITLE
Rewrite "Verifying Zowe installation on z/OS"

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#1995]
This chapter refers to instance.env and messages that are v1 specific and needs rewriting to v2 launcher and v2 messages

**Comment by samanthasusu** [comment]
Hi Joe, I am wondering if this issue is still necessary since I didn't see this chapter on doc site now. If necessary, please let me know which one to be rewritten. Thanks!

**Comment by Joe-Winchester** [comment]
Hi Sam,  I checked https://docs.zowe.org/v2.6.x/user-guide/verify-zowe-runtime-install/ and it looks as though it is all current for v2, so I'll close the issue.
Thank you for following up on this !
