### ISSUE TITLE
Issue with docs.zowe.org/stable/extend/extend-desktop/mvd-server-config/

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/docs-site#2011]
## Description
Wrong link on the page.

## Pages to Update
Page:
https://docs.zowe.org/stable/extend/extend-desktop/mvd-server-config/#http-1

Wrong link:
https://zowe.github.io/docs-site/latest/user-guide/mvd-configuration.html#defining-the-at-tls-rule

## Expected behavior
Page will be found.

**Comment by samanthasusu** [comment]
hi @Martin-Zeithaml sorry for the late reply and thank you for reporting this. Would you please let us know the version number of this issue so that I could fix it? thanks!

**Comment by Martin-Zeithaml** [comment]
Hi, 
it seems, the page was moved, so this is no longer valid issue.
