### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/cli-install-cli-next/cli-install-cli-nodejs-windows

### ISSUE THREAD

**Issue by billpereira** [zowe/docs-site#2039]
## Description
The link on Zowe CLI documentation about zowe install on windows is broken:
If you are installing Zowe CLI @next on a computer that is running Node.js 16 on Windows operating system, see [Installing Zowe CLI with Node.js 16 on Windows](https://docs.zowe.org/stable/user-guide/cli-install-cli-next/cli-install-cli-nodejs-windows).

## Pages to Update
[](https://docs.zowe.org/stable/user-guide/cli-install-cli-next/cli-install-cli-nodejs-windows)

**Comment by anaxceron** [comment]
Closing as the link to [Installing Zowe CLI with Node.js 16](https://docs.zowe.org/v1.28.x/user-guide/cli-install-cli-nodejs-windows) on Windows is working.
This link can be found in [Install the Zowe CLI @next version](https://docs.zowe.org/v1.28.x/user-guide/cli-install-cli-next) under the Prerequisites section
