### ISSUE TITLE
[0.9.4] Separate the CLI install information from install on z/OS

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#205]
In 0.9.4, Zowe CLI can be downloaded separately instead of within the PAX file. The doc needs to be updated accordingly. Also, need to highlight this in release notes.

**Comment by JamesBauman** [comment]
Hi Ashely @nannanli - Do we know the date that we plan to release 094?

**Comment by jelaplan** [comment]
See also https://waffle.io/zowe/community/cards/5be3592311bff300c573ceea
