### ISSUE TITLE
Zowe V2 updates for Zowe Explorer

### ISSUE THREAD

**Issue by zFernand0** [zowe/docs-site#2112]
## Is your request for enhancement related to a problem? Please describe.
Zowe V2 updates for Zowe Explorer

## Describe the solution you'd like
**Zowe Explorer Profiles**
1. I see the CLI squad uses the term `team profiles` to refer to Zowe v2 LTS profiles in [this article](https://deploy-preview-1961--zowe-docs-master.netlify.app/stable/user-guide/cli-using-using-team-profiles/). Maybe we should stick to the following verbiage:
    - For v1: Zowe v1 LTS profiles, v1 profiles, yaml profiles, single profile per yaml file, ...
    - For v2: Zowe v2 LTS profiles, **team** profiles, v2 profiles, ...

2. The section [`working-with-zowe-explorer-profiles`](https://docs.zowe.org/stable/user-guide/ze-profiles/#working-with-zowe-explorer-profiles) should mention that it is mostly applicable for Zowe v1 LTS profile (singe-profile-per-yaml-file).
From this section, the only thing that applies to both, v1/yaml profiles and **team** profiles, is the **Profile Validation**

3. For v2 we should add a Team Configuration file section before the v1 profile creation documentation (above section)
The contents of this new section will include almost everything in the [Profile Configuration section of the Early Access readme file](https://github.com/zowe/vscode-extension-for-zowe/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#profile-configuration)

4. The [`enabling-secure-credential-store-with-zowe-explorer`](https://docs.zowe.org/stable/user-guide/ze-profiles/#enabling-secure-credential-store-with-zowe-explorer) topic (and its sub heading - for Zowe CLI Users) should be removed. A PR is in the works to remove all of that stuff 😋 

## Related doc pages
Links above

**Comment by nannanli** [comment]
@JamesBauman Can this be closed now?

**Comment by JamesBauman** [comment]
hi @nannanli  ...   I'll get back to you.... The affected article needs a grammar review/update.  Perhaps i should open a "doc enhancement" issue.  Stay tuned... 

thx
