### ISSUE TITLE
Doc enhancement request for docs.zowe.org/stable/user-guide/configure-zos-system

### ISSUE THREAD

**Issue by travatine** [zowe/docs-site#2119]
## Is your request for enhancement related to a problem? Please describe.
Enhancement.
The page is very confusing as it tries to cater for users that run ZWESECUR and those who manually perform steps.

## Describe the solution you'd like
Please split the page into two - one section for users who run 'ZWESECUR' and another for users who want an advanced install , by performing all steps manually.

**Comment by nannanli** [comment]
Thank you for the suggestion! The cited topic has been chunked into smaller pieces. Advanced configurations are consolidated in this topic https://deploy-preview-2146--zowe-docs-master.netlify.app/stable/user-guide/configure-zos-system while other required steps are made standalone ones. 
Read the preview configuration documentation here https://deploy-preview-2146--zowe-docs-master.netlify.app/stable/user-guide/initialize-zos-system and please continue to send us any issues that might persist. Appreciate your feedback.
