### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/install-zowe-smpe#service-level-information

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#2124]
## Description

The "Service level information" of the program directory documents the service that is included in the FMID (base install). Since we have not done a refresh of the FMID, it is still at the original level. Therefore we should say
`No PTFs against this release of Zowe have been incorporated into the product package.`
and remove the list of PTFs that is currently here (as they are not included).

We can add a sentence that points to the https://www.zowe.org/download download site where the customer can get the latest (or previous) service.
`Zowe service can be downloaded from https://www.zowe.org/download/.`

## Pages to Update
https://docs.zowe.org/stable/user-guide/install-zowe-smpe#service-level-information

**Comment by nannanli** [comment]
Thank you for reporting this issue! The "Service level information" list has been removed. It'll be added back once the refresh is available in a future release. See the updated topic here: https://deploy-preview-2146--zowe-docs-master.netlify.app/stable/user-guide/install-zowe-smpe#service-level-information
