### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/install-zowe-smpe#target-system-requirements

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#2125]
## Description

Section "Storage requirements for SMP/E work data sets" says you need `(20,200)` tracks for SMPWRK6 and SYSUT1. This is incorrect, the actual value in tracks is 15 times higher: `(300,3000)`.

## Pages to Update
https://docs.zowe.org/stable/user-guide/install-zowe-smpe#target-system-requirements

**Comment by nannanli** [comment]
This has been updated. Thank you for the information!
