### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-displaying-help/

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#2176]
## Description

The Zowe Web Help does not show the CLI plugins that it used to display before. I see that there is v2.0.0. Is there a way how I can get to the v1 with all the plugins?

## Pages to Update
https://docs.zowe.org/stable/web_help/index.html

## Expected behavior

I would like to see documentation of all CLI plugins. For both v1 and v2 because I am using v1 and v2 for different projects.

**Comment by plavjanik** [comment]
Thank you! It brought me to https://docs.zowe.org/v1.27.x/web_help/index.html which is the version with all CLI plugins.

My mistake was clicking on the dropdown with versions that redirected me to the home page.

When I download the ZIP format it downloads the 1.27.3 version with all the plugins instead of 2.0.0.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/7644758/167491809-59da1bb0-189b-4a69-94df-1b5c5bfc3234.png">

<img width="213" alt="image" src="https://user-images.githubusercontent.com/7644758/167491868-14ad7296-1b11-476f-b0b6-f629f13c7f20.png">

**Comment by JamesBauman** [comment]
@petr-galik 

That's a bug! :( We will fix asap.. Please check when you get in on Tuesday.

**Comment by plavjanik** [comment]
Thank you, it works 👍🏼

**Comment by JamesBauman** [comment]
Closed, verified fixed.
