### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/release-notes/user-guide/cli-updatingcli

### ISSUE THREAD

**Issue by markklerks** [zowe/docs-site#2186]

**Comment by nannanli** [comment]
Hi, thank you for catching the broken link! We're checking the docs. Meanwhile, may I know on which page you spotted this link? It seems the link cited is mixing different topics so we'd like to understand more where it occured. Thank you!

**Comment by markklerks** [comment]
No problem, please check the included screenprint:
***@***.***

**Comment by nannanli** [comment]
Hey, the reported issue has been fixed. Thank you again for reporting the error to us! If you see any other issues or have further comments, don't hesitate to let us know.
