### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/user-guide/cli-updatingcli

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/docs-site#2191]
## Description

From page https://docs.zowe.org/stable/getting-started/release-notes/v2_0_0, clic on "Migrating Zowe CLI from V1 to V2" in left menu:

https://docs.zowe.org/stable/getting-started/user-guide/cli-updatingcli#updating-to-the-zowe-cli-v2-long-term-support-v2-lts-version

--> Page not found

## Pages to Update

https://docs.zowe.org/stable/getting-started/release-notes/v2_0_0

**Comment by nannanli** [comment]
Thank you for reporting this issue! It has been fixed already on the Zowe doc site so closing this now. Let us know if you spot any other issues or have further questions.
