### ISSUE TITLE
Issue with docs.zowe.org/v1.27.x/user-guide/install-zowe-smpe/

### ISSUE THREAD

**Issue by ktanriverir** [zowe/docs-site#2194]

**Comment by ktanriverir** [comment]
Page Not Found
We could not find what you were looking for.

Please file an [Issue](https://github.com/zowe/docs-site/issues/new?assignees=&labels=&template=---doc-error-report.md&title=Page%20Not%20Found:%20docs.zowe.org/zowe-docs-v1.27.x.pdf) and let us know from where you were redirected on this page.

**Comment by nannanli** [comment]
Hey, the issue with docs.zowe.org/v1.27.x/user-guide/install-zowe-smpe/ and the v1.27.x PDF file are both fixed now. Let us know if the issue persists. Thank you again for reporting the issue!
