### ISSUE TITLE
Edit and upload API ML videos to the YouTube channel

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#2197]
There are a couple of API ML videos that can be uploaded to the Zowe YouTube playlist. 

- Check whether there are style issues of the videos. 
- Add descriptions about these videos. 
- Upload them to the proper playlist. 
- Check whether they need to be embedded in Zowe docs.

**Comment by samanthasusu** [comment]
Close for now. If any further input, will open a new one.
