### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/extend/extend-apiml/onboard-direct-eureka-call/implement-new-saf-provider.md

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2198]
## Description
As the title says HTTP 404 on request to:
https://docs.zowe.org/stable/extend/extend-apiml/onboard-direct-eureka-call/implement-new-saf-provider.md

## Pages to Update
https://docs.zowe.org/stable/extend/extend-apiml/onboard-direct-eureka-call/#authentication-parameters

## Screenshots
![image](https://user-images.githubusercontent.com/3938398/167396884-ca7a7b01-b1d3-4dfb-a4a1-c10bcb1d97bc.png)

## Expected behavior
Page displayed

## Additional context
None

**Comment by janan07** [comment]
Addressed in PR: [#2202 ](https://github.com/zowe/docs-site/pull/2202)
