### ISSUE TITLE
Duplicate "zosmf" item in apiml.authentication.scheme types list

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2199]
## Description
Duplicate "zosmf" item in apiml.authentication.scheme types list

## Pages to Update
https://docs.zowe.org/stable/extend/extend-apiml/onboard-direct-eureka-call/#authentication-parameters

## Screenshots
![image](https://user-images.githubusercontent.com/3938398/167397435-a46b4980-42ad-4e6e-aa27-933ab9fb13a1.png)

## Expected behavior
A single occurrence of the "zosmf" item

## Additional context
None

**Comment by janan07** [comment]
Addressed in PR#[2616](https://github.com/zowe/docs-site/pull/2616)
