### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/api-mediation/stable/getting-started/release-notes/v2_0_0

### ISSUE THREAD

**Issue by sri-zos** [zowe/docs-site#2201]
## Description
The display pop-up at the top of the screen with link to new features and fixes of zowe 2.0 seems broken.
https://docs.zowe.org/stable/contribute/stable/getting-started/release-notes/v2_0_0

"Zowe Version 2.0 is now available! Read about the [new features and fixes](https://docs.zowe.org/stable/contribute/stable/getting-started/stable/getting-started/stable/getting-started/release-notes/v2_0_0) in this release."

## Pages to Update
[](https://docs.zowe.org/stable/contribute/stable/getting-started/release-notes/v2_0_0)

## Expected behavior
Reach release-notes for Zowe Version 2.0

## Additional context

**Comment by nannanli** [comment]
Thank you for reporting this issue! The banner has been removed now. We'll add it back when a new release is made available.
