### ISSUE TITLE
Page Not Found 

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2206]
## Description
Received HTTP 404 for https://docs.zowe.org/stable/user-guide/upgrade-zos-system/configure-instance-directory.md#updating-the-instance-env-configuration-file

## Screenshots
![image](https://user-images.githubusercontent.com/3938398/168284475-364d9e5a-53ff-4b8e-a32d-fa1e5c482693.png)

**Comment by nannanli** [comment]
The link issue has been fixed. Closing.
