### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/components/zwe-components

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2208]
## Description

HTTP 404 on all links on zwe_server_command_reference.md, e.g. the following don't work:
[certificate](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/certificate/zwe-certificate)
[components](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/components/zwe-components)
[init](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/init/zwe-init)
[install](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/zwe-install)
[internal](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/internal/zwe-internal)
[migrate](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/migrate/zwe-migrate)
[sample](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/sample/zwe-sample)
[start](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/zwe-start)
[stop](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/zwe-stop)
[support](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/support/zwe-support)
[version](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/zwe-version)

## Pages to Update
https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/

## Screenshots
![image](https://user-images.githubusercontent.com/3938398/168611820-03ea961e-fef4-41cc-b0f9-9106416c4f80.png)

**Comment by nannanli** [comment]
The ZWE command reference links are all working correctly now. Check them out using the link below and let us know if the issue persists. 
[certificate](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/certificate/zwe-certificate)
[components](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/components/zwe-components)
[init](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/init/zwe-init)
[install](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-install)
[internal](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/internal/zwe-internal)
[migrate](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/migrate/zwe-migrate)
[sample](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/sample/zwe-sample)
[start](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-start)
[stop](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-stop)
[support](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/support/zwe-support)
[version](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-version)
