### ISSUE TITLE
Update the zowe cli install doc for the change to a standalone CLI download and install.

### ISSUE THREAD

**Issue by jelaplan** [zowe/docs-site#221]
See the e-mail thread titled Re: [zowe/zlc] Allow CLI as separate download (#54)

**Comment by JamesBauman** [comment]
Screen mockup here.

https://zowe.org/download-copy/

**Comment by JamesBauman** [comment]
content is live

**Comment by JamesBauman** [comment]
Content published,   See 
https://zowe.github.io/docs-site/latest/user-guide/gettingstarted.html
and
https://zowe.github.io/docs-site/latest/user-guide/cli-installcli.html#installing-zowe-cli-from-local-package
