### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/configure-zowe-server/

### ISSUE THREAD

**Issue by johnottogood** [zowe/docs-site#2212]
## Description
Step 2 , first paragraph incorrectly states that the administrator userid should be ZWEADMIN.

ZWEADMIN is a group, not an ID.

## Pages to Update
[](https://docs.zowe.org/stable/user-guide/configure-zowe-server/)

## Screenshots
(The sentence in question)
"The ZWESVSTC should be configured as a started task under the ZWESVUSR user ID with the administrator user ID of ZWEADMIN"

## Expected behavior
(Suggested edit)
The ZWESVSTC should be configured as a started task under the ZWESVUSR user ID which belongs to the  (started task???) group ZWEADMIN.

**Comment by nannanli** [comment]
Hi @johnottogood , similar to #2216, the cited file `user-guide/configure-zowe-server` is not applicable to Zowe V2, thus it has been removed from Zowe docs now. Sorry for the confusion and thank you again for bringing this to the Zowe doc squad. 

The lastest doc about configuring Zowe can be found as follows:
https://docs.zowe.org/stable/user-guide/initialize-zos-system
