### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/configure-zowe-server/

### ISSUE THREAD

**Issue by johnottogood** [zowe/docs-site#2216]
## Description
The page referenced below which is taged with "Version: v2.0.x LTS" makes references to ZOWE_INSTANCE_DIR and instance.env.

I'm new to Zowe, (no experience prior to this 2.0 release) but as I understand it instance.env is the predecessor to zowe.yaml.   It seems this page needs updating to refer proper v2.0 configuration elements and scripts/jobs/procs

## Pages to Update
https://docs.zowe.org/stable/user-guide/configure-zowe-server/

**Comment by nannanli** [comment]
Thank you for reporting this issue! The cited file is out-of-date as you noticed and it has been removed from Zowe docs completely. Sorry for the confusion. 

The lastest doc about configuring Zowe can be found as follows: 
https://docs.zowe.org/stable/user-guide/initialize-zos-system 

Let us know if you see any further issues with Zowe docs. Appreciate your feedback!
