### ISSUE TITLE
Issue with docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/

### ISSUE THREAD

**Issue by johnottogood** [zowe/docs-site#2220]
## Description
All of the linked pages for zwe subcommands (below) on the page identified in this issue are broken:
    certificate
    components
    init
    install
    internal
    migrate
    sample
    start
    stop
    support
    version
    
## Pages to Update
docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe/

**Comment by nannanli** [comment]
These links are working now. Check out the files in that section and let us know if the issue persists. Thanks again for reporting the issue! 
https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/certificate/keyring-jcl/zwe-certificate-keyring-jcl-clean

**Comment by johnottogood** [comment]
Thanks for the update.
