### ISSUE TITLE
Fixing the "unmaintained" warning banner

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2221]
![image](https://user-images.githubusercontent.com/30730276/169842820-765a5ef6-4cde-4dae-afde-4d21750bcda3.png)
This warning is now displayed on every v1 document.
This banner is the opposite of our stated support for v1: every part of zowe is maintained such as doc, code, etc.
And users have already complained.

So, we either need a different banner or no banner.
Ideally, we should be saying something like...

> latest v2.x: no banner
> v2.x less than latest v2.x: warning banner stating you are looking at an outdated version of the documentation, and should look at the latest v2.x as fixes are always applied to the latest version.
> 
> latest v1.x: info (not warning) message asking if you're looking for the latest version of zowe (link to v2)
> v1.x less than latest v1.x: warning banner stating you are looking at an outdated version of the documentation, and should look at > the latest v1.x as fixes are always applied to the latest version.

The warning message appears to be a default from docusaurus: https://docusaurus.io/docs/versioning
They only have 'none', 'unreleased', and 'unmaintained' `banner` which gets applied depending on how you organize your versions.

I'm not very familiar with the docs site code and will be away for a few weeks soon, so I'm just adding some insight if it helps:
* https://github.com/zowe/docs-site/blob/master/src/pages/versions.js appears to be applying a list that adheres to the versioning API above
* Ideally why not set ALL of them to banner=none and make a custom banner that says what you really want to say: https://docusaurus.io/docs/next/markdown-features/admonitions
* Worst case, why not take the first non-v2 in the list and set it to banner=none, so the warning doesnt show up.

**Comment by RASakach** [comment]
@nannanli :  At the May24 ZAC we agreed that the current banner / message displayed for the latest V1.x release was misleading to our customers.  All were in favor of the custom banner referenced by @1000TurquoisePogs (Sean) above.  If a custom banner is possible:

We recommend using this message for just the latest Zowe v1.x (1.28) release.
_"Please Note:  The Zowe V1 LTS release has transitioned to “maintenance” effective 04/23/2022 with the 1.28 release and will no longer include new features.  Security patches and critical bug fixes will continue to be documented for this release.  For the latest Zowe features and capabilities, please reference the latest version of Zowe Docs for the "active" V2 LTS release (v2.x.x LTS)."_

For all prior Zowe V1.x releases, we recommend this message:  
_"Please Note:  The Zowe V1 LTS release has transitioned to “maintenance” effective 04/23/2022 with the 1.28 release and will no longer include new features.  Security patches and critical bug fixes will continue to be documented for this release.  Customers planning to remain on the V1 LTS release please reference the latest version of Zowe Docs for the **maintained** V1 LTS release (v1.28.x).  For the latest Zowe features and capabilities, please reference the latest version of Zowe Docs for the **active** V2 LTS release (v2.x.x LTS)."__

Will customers be allowed to submit DOCUMENTATION UPDATES to the last V1.28.x Zowe Docs?  If yes, is this process documented somewhere within Zowe v1.28.x Doc?  If no, can we add that somewhere?

Thanks very much for your help with this! 
@janan07 FYI (in case this comes up on the TSC call)

**Comment by nannanli** [comment]
@idontknowjs Hi Arijit, I know we just changed the banner in PR https://github.com/zowe/docs-site/pull/2222. Is it possible to further customize the banner for different releases.
For just the Zowe v1.28 release, use this message as the banner: 
"Please Note: The Zowe V1 LTS release has transitioned to “maintenance” effective 04/23/2022 with the 1.28 release and will no longer include new features. Security patches and critical bug fixes will continue to be documented for this release. For the latest Zowe features and capabilities, please reference the latest version of Zowe Docs for the "active" V2 LTS release (v2.x.x LTS)."

For all prior Zowe V1.x releases, we recommend this message:
"Please Note: The Zowe V1 LTS release has transitioned to “maintenance” effective 04/23/2022 with the 1.28 release and will no longer include new features. Security patches and critical bug fixes will continue to be documented for this release. Customers planning to remain on the V1 LTS release please reference the latest version of Zowe Docs for the maintained V1 LTS release (v1.28.x). For the latest Zowe features and capabilities, please reference the latest version of Zowe Docs for the active V2 LTS release (v2.x.x LTS)."_

**Comment by idontknowjs** [comment]
Hi @nannanli what needs to be shown in the banner, when `v2.1.x` will be the latest and `v2.0.x` will become an archived version just like `v1.x.x` versions.?

**Comment by nannanli** [comment]
> Hi @nannanli what needs to be shown in the banner, when `v2.1.x` will be the latest and `v2.0.x` will become an archived version just like `v1.x.x` versions.?

Hi @idontknowjs , sorry for misssing this part about v2 release. Taking v2.1.0 and v2.0.x for example, the banner for v2.0.x release should be as follows. This should apply to all V2 `archived` releases. 

> This is documentation for Zowe v2.0.x LTS. For documentation of the latest version, see [v2.1.x LTS](https://docs.zowe.org/stable/getting-started/overview).
