### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/initialize-zos-system/initialize-mvs-dataset.md

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#2231]
I tried to follow the link `[Prepare custom MVS data sets](https://docs.zowe.org/stable/user-guide/initialize-zos-system/initialize-mvs-dataset.md)` on https://docs.zowe.org/stable/user-guide/initialize-zos-system/

**Comment by samanthasusu** [comment]
@plavjanik Thank you for reporting this issue. PR#2240 is created to fix this issue.

**Comment by nannanli** [comment]
Verified that this issue has been fixed. Check out the updated topic https://docs.zowe.org/stable/user-guide/initialize-zos-system/. Closing.
