### ISSUE TITLE
What is the correct started task in Zowe V2? ZWESVSTC or ZWESLSTC?

### ISSUE THREAD

**Issue by rjmaomao** [zowe/docs-site#2234]
In Zowe doc for V2 section Installing and starting the Zowe started task (ZWESLSTC)

https://docs.zowe.org/stable/user-guide/configure-zowe-server/

Contents looks like still V1, what should be the correct started task used in V2?  ZWESVSTC or ZWESLSTC?  Name ZWESVSTC is used in the doc, but seems there's no ZWESVSTC provided in dataset .SZWESAMP 
```
Step 1: Copy the PROCLIB member ZWESVSTC
Step 2: Configure ZWESVSTC to run under the correct user ID
Step 3: Launch the ZWESVSTC started task
```

And this part of document is still referring to instance_dir.  I think there's no instance concept now?
```
Option 1: Starting Zowe from a USS shell
To launch the ZWESVSTC started task, run the zowe-start.sh script from a USS shell. This reads the configuration values from the instance.env file in the Zowe instance directory.

 
cd <ZOWE_INSTANCE_DIR>/bin
./zowe-start.sh
 
```

**Comment by nannanli** [comment]
Hi @rjmaomao , the cited topic https://docs.zowe.org/stable/user-guide/configure-zowe-server/ is out-of-date and it has been removed from Zowe docs now. We're sorry for the confusion. 

In V2, the started task name is ZWESLSTC. Check out this topic for more details  https://docs.zowe.org/stable/user-guide/install-stc-members. Let us know if you have further questions.
