### ISSUE TITLE
Enhance the banner message background color

### ISSUE THREAD

**Issue by travatine** [zowe/docs-site#2248]
## Description
There is a warning message at the top of the  page with yellow & white text when viewed with "light" mode - this message is almost unreadable.

## Pages to Update
[](https://docs.zowe.org/v1.28.x/getting-started/release-notes/v1_28_0)

## Screenshots
![image](https://user-images.githubusercontent.com/17565183/174707960-7784187b-e003-469e-99d5-b8abc4363677.png)

## Expected behavior
Use black text on a yellow background for better contrast.

**Comment by JamesBauman** [comment]
@nannanli This is an issue only when not using dark mode. The image renders ok in dark mode.

**Comment by nannanli** [comment]
Hey @idontknowjs , could we enhance the site banner as shown in the description to use a style that is consistent with the Docusaurus site？ https://docusaurus.io/docs/2.0.0-beta.22 

They are using a background color that looks more friendly in both dark and light mode. 
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/14340789/181450822-8c8de305-463c-4a7c-8ebf-21d7dd22c2b2.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/14340789/181450895-7d262527-dd2d-4380-a145-a22e9ee7910f.png">
