### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/cli-installcli/cli-configure-scs-on-headless-linux-os

### ISSUE THREAD

**Issue by dvpbandaru** [zowe/docs-site#2251]

**Comment by JamesBauman** [comment]
@dvpbandaru

On what page did you click a link that gave you the 404?

**Comment by dvpbandaru** [comment]
Hi James,
        Sorry for not providing the details.
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/41592558/176221066-af9dcce2-444d-47b9-ad5c-8478a7085891.png">

Navigate to this page and the link with https://docs.zowe.org/stable/user-guide/install-ha-overview.md got broken. Please see this in the screenshot.
Thanks,
Prasad Bandaru

**Comment by JamesBauman** [comment]
@dvpbandaru ... Hi Prasad - that page is in fact returning a 404 error. it is pointing to https://docs.zowe.org/stable/user-guide/install-ha-overview.md. This link is not the same topic that returned the 404 that you mentioned in your original notification to us. By some chance, do you recall the topic that returned the 404 error?   https://docs.zowe.org/stable/user-guide/cli-installcli/cli-configure-scs-on-headless-linux-os.

Thank you!

PS we will fix this latest error that you discovered!

**Comment by t1m0thyj** [comment]
@JamesBauman I think this 404 may be the same one as https://github.com/zowe/docs-site/issues/2275

**Comment by nannanli** [comment]
Verified that the two link issues have been fixed on the Zowe doc site: 

- https://docs.zowe.org/stable/user-guide/install-zos where "High availability overview" now points to https://docs.zowe.org/stable/user-guide/zowe-ha-overview. 
- https://docs.zowe.org/stable/user-guide/cli-installcli where "Configure Secure Credential Store on headless Linux operating systems" now points to https://docs.zowe.org/stable/user-guide/cli-configure-scs-on-headless-linux-os

Closing this issue and thank you @dvpbandaru again for bringing this to the team!
