### ISSUE TITLE
Images issue on 2 configuration-related pages

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#2261]
## Description

The workflows-related images are broken (not displayed)

## Pages to Update
On page https://docs.zowe.org/stable/user-guide/certificates-setup

- [ ] `<img src="../images/configure/workflow-one.png" alt="Workflow ZWEKRING" style="height: 300px; width:500px;"/> <br />`
- [ ] `<img src="../images/configure/workflow-two.png" alt="Workflow ZWECRECR" style="height: 450px; width:500px;"/> <br />`
- [ ] `<img src="../images/configure/workflow-threeB.png" alt="Workflow ZWESIGNC" style="height: 150px; width:500px;"/> <br />`
- [ ] `<img src="../images/configure/workflow-parameters.png" alt="Workflow Parameters" style="height: 400px; width:500px;"/> <br />`
- [ ] `<img src="../images/configure/workflow-four.png" alt="Workflow ZWELOADC" style="height: 450px; width:500px;"/> <br />`

On page https://docs.zowe.org/stable/user-guide/configure-zowe-zosmf-workflow/, fix the following links: 

- [ ] `<img src="../images/zosmf/perform-workflows.png" alt="Workflow ZWECRECR" style="height: 300px; width:500px;"/> <br />`

Please update the links in all available Zowe doc versions including archived docs in the `docs-site/versioned_docs` directory. You can do this by using the search and replace function of your local text editor. 

## Screenshots

https://prnt.sc/xfrKsizgQo_P

## Expected behavior

The images should be properly dispayed

**Comment by nannanli** [comment]
The image syntax in this topic should be updated. Take this as an example: 
`<img src="../images/configure/workflow-one.png" alt="Workflow ZWEKRING" style="height: 300px; width:500px;"/> <br />`

Use one of the following formats to code it instead. Either works.

- `![Workflow ZWEKRING](../images/configure/workflow-one.png)`
- `<img src={require("../images/configure/workflow-one.png").default} width="500" alt="Workflow ZWEKRING"/>`

**Comment by nannanli** [comment]
Hey @chinmaym07, instead of #2266 which has been addressed, I wonder if you would like to pick up this one instead.  Please let me know. I can provide you more details or further help if needed. Thanks!

**Comment by IgorCATech** [comment]
> * <img src={require("../images/configure/workflow-one.png").default} width="500" alt="Workflow ZWEKRING"/>

This format doesn't seem to work, only ![Workflow ZWEKRING](../images/configure/workflow-one.png). However, one cannot set the width of the image with this syntax. I've tried the following formats: 

<img src={require("../images/zosmf/perform-workflows.png").default} width="500" alt="Workflow ZWECRECR"/>

![Workflow ZWECRECR](../images/zosmf/perform-workflows.png){:height="300px" width="500px"}
![Workflow ZWECRECR](../images/zosmf/perform-workflows.png =300x500)

They don't work, unfortunately.

**Comment by anaxceron** [comment]
Closing w/ [PR 2636](https://github.com/zowe/docs-site/pull/2636)
