### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/cli-installcli/cli-configure-scs-on-headless-linux-os

### ISSUE THREAD

**Issue by MS615511** [zowe/docs-site#2275]
## Description

Seems to be a broken link or the page just does not exist

## Screenshots

![image](https://user-images.githubusercontent.com/47430882/179248248-ad2a3696-8a71-4c19-a231-bd3621e36c3c.png)

**Comment by t1m0thyj** [comment]
Thanks for reporting this!
The link it should be pointing to is here: https://docs.zowe.org/stable/user-guide/cli-configure-scs-on-headless-linux-os/

**Comment by nannanli** [comment]
Verified that the issue has been fixed on the Zowe doc site. Check it out https://docs.zowe.org/stable/user-guide/cli-installcli which points now to https://docs.zowe.org/stable/user-guide/cli-configure-scs-on-headless-linux-os. Closing this issue but feel free to reopen if the issue still persists. Thanks again for reporting the error!
