### ISSUE TITLE
[cli] Command to initialize team configuration is missing a flag

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/docs-site#2276]
## Description

The documentation for "Create team profile configuration files" says it will add a file to your local `.zowe` directory.

This is inaccurate because the command shown will add the file in your current directory.

To fix this, the command should include the `--global-config` flag.

## Pages to Update

https://docs.zowe.org/stable/user-guide/cli-using-initializing-team-configuration#create-team-profile-configuration-files

## Screenshots

![image](https://user-images.githubusercontent.com/22344007/179292469-c4f7a07f-58ac-4fbc-87a5-afe2bc9fd282.png)

## Expected behavior

The command should be: `zowe config init --global-config`

## Additional context

@JamesBauman

**Comment by JamesBauman** [comment]
Article updated.....  will publish with v2.2 GA:

https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/cli-using-initializing-team-configuration.md
