### ISSUE TITLE
Issue with docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-start

### ISSUE THREAD

**Issue by hockeyrob** [zowe/docs-site#2280]
## Description
As with the description of zwe stop...the description of zwe start references the zowe.jobname entry in zowe.yaml, but there is no such specification. This should likely refer to zowe.job.name, although there is no other real reference to what this means that I have found in the documentation. The installation/initialization documentation refers to the STC names and the userids associated with the STC names, but I haven't seen anything that refers to zowe.job.name until I got to the zwe start and zwe stop commands.

## Pages to Update
https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-start

## Expected behavior
Please correct, and if possible, make other references in the doc pages for installation/configuration.

**Comment by nannanli** [comment]
This issue is similar to what's reported in #2279. `zowe.jobname` versus `zowe.job.name` should be clarified and unified in the documentation.

**Comment by jackjia-ibm** [comment]
Should be fixed with https://github.com/zowe/zowe-install-packaging/pull/2973. Will need to regenerate doc.
