### ISSUE TITLE
ZWEL0047E not documented

### ISSUE THREAD

**Issue by lzuckett** [zowe/docs-site#2288]
## Pages to Update

https://docs.zowe.org/stable/troubleshoot/launcher/launcher-error-codes

**Comment by nannanli** [comment]
@jackjia-ibm @ojcelis Hi Jack, Oj, I wonder if you could help provide more details about this message ZWEL0047E. It's not documented in the launcher doc https://docs.zowe.org/stable/troubleshoot/launcher/launcher-error-codes yet. Thanks!
