### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/configure-zowe-server/

### ISSUE THREAD

**Issue by connorpekovic** [zowe/docs-site#2311]
## Description

Hi Zowe Team,

Our data center is installing the ZWESLSTC started task for the first time.  The documentation on [configuring ZWESLSTC](https://docs.zowe.org/stable/user-guide/configure-zowe-server/) seems to be using the name ZWE**SVS**TC in the instructions. Can take a look and see if that's reading as intended?

Thanks a bunch,
Connor Pekovic

## Pages to Update
https://docs.zowe.org/stable/user-guide/configure-zowe-server/

## Screenshots

![Screenshot](https://connors-file-public.fra1.digitaloceanspaces.com/Zowe%20ZWESLSTC.png)

## Expected behavior

Data center team seeking instructions on how to install and configure the ZWESLSTC. The ZWESISTC started task is up and running as of now.

**Comment by nannanli** [comment]
@connorpekovic Hi, thanks for reaching out! Which Zowe version is the team installing now? It seems Zowe V2 is installed. Zowe V1 and V2 installations are different and the cited link is an out-of-date topic that should be revmoved from Zowe docs. Please check the latest instructions about installing and configuring ZWESLSTC here https://docs.zowe.org/stable/user-guide/configure-xmem-server. We're sorry for the confusion and let us know if there is any further question.

**Comment by connorpekovic** [comment]
Thanks @nannanli, we're going to move forward with that doc on the ZWESLSTC. Thank you!
