### ISSUE TITLE
Create Zowe CLI Day 1 Task Checklist

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#2324]
As a new user, I need guidance for common tasks as I start using Zowe CLI.

**Description:**

Customers often ask, "Now that the product is up and running, how do I start using it?" In most instances, product doc sets include the right scenarios to help users get started. However, they may not be easy to find. With this story, we build a Day 1 Checklist, which summarizes key tasks to start using your product for the first time. The checklist includes a brief description of the tasks, with links to the procedures. The checklist also identifies the roles that are typically required to complete the task.

**Acceptance Criteria:**

- The checklist includes the top 5 day 1 tasks that we recommend.
- Make sure the five topics include real-world examples.

**Comment by anaxceron** [comment]
@JamesBauman -- what do we need to do to get working on this?

**Comment by anaxceron** [comment]
Closing this as it was determined that a Day 1 task checklist was not suitable for Zowe CLI. The Zowe CLI Installation Checklist already includes the tasks that would be designated as Day 1 items.
