### ISSUE TITLE
Update the node pre-req so we let users know that make and python are not required

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#234]
https://github.com/zowe/docs-site/blob/bccb7f620cac5fe1d8336bc02ea3e4d71f2bd803/docs/user-guide/systemrequirements.md

Refers to the node pre-req and points end users to the IBM SDK for Node trial.  This then asks users to install make and python that aren't required.  All that is required for node to work for Zowe is just the basic server.

The docs should be updated to reflect this.

**Comment by JamesBauman** [comment]
This issue does not apply to CLI.

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, the doc is updated to clarify that requirements like Make or Python are not needed. Can you review this file? Thanks!
https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/systemrequirements.md

**Comment by Joe-Winchester** [comment]
Hi Ashley,
 
This looks great - many thanks for making the change.
 
Best regards,
 
Joe Winchester
IBM z/OS Explorer Senior Technical Staff Member - Project Zowe Contributor zowe.org
 
Phone: 44-7749-965423
Twitter: @JoeWinchester    LinkedIn: joewinchester
E-mail: winchest@uk.ibm.com
 
 
----- Original message -----From: nannanli <notifications@github.com>To: zowe/docs-site <docs-site@noreply.github.com>Cc: Joe-Winchester <winchest@uk.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [zowe/docs-site] Update the node pre-req so we let users know that make and python are not required (#234)Date: Fri, Nov 16, 2018 9:20 AM 
@Joe-Winchester Hi Joe, the doc is updated to clarify that requirements like Make or Python are not needed. Can you review this file? Thanks!https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/systemrequirements.md
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread. 
 Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU
