### ISSUE TITLE
Information roadmap for Zowe CLI is not in the TOC

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#2340]
The Information roadmap for Zowe CLI is not attached to the TOC for the web site.  We link to it from the Zowe CLI installation checklist. 

Checklist: https://docs.zowe.org/stable/user-guide/cli-install-cli-checklist
CLI Info roadmap: https://docs.zowe.org/stable/getting-started/user-roadmap-zowe-cli

**Corrective action:**

1. Rename the file *Zowe CLI information roadmap*
2. Update the sidebar.js file. Insert the file immediately after Getting Started > Zowe fundamentals > Zowe architecture.
3. Ensure that the link in the checklist opens the article.

**Comment by anaxceron** [comment]
The roadmap has been added to the ToC.
