### ISSUE TITLE
Docs for developing a CLI plug-in need updates for v2 profiles

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/docs-site#2342]
## Description
The contents of `DataSets.handler.ts` are outdated because they contain deprecated code that can only load v1 profiles.

## Pages to Update
https://docs.zowe.org/stable/extend/extend-cli/cli-developing-a-plugin#defining-commands

## Screenshots
![image](https://user-images.githubusercontent.com/22344007/183462979-5b77ba6f-3500-4144-adb0-8e137614ca49.png)

## Expected behavior
The docs should be updated to replace the deprecated `params.profiles.get` API with new methods of loading team configuration.

## Additional context
This issue is related to zowe/zowe-cli-sample-plugin#73

**Comment by anaxceron** [comment]
@JamesBauman -- to-do item for the near future?

**Comment by anaxceron** [comment]
Closing w/ [PR 2652](https://github.com/zowe/docs-site/pull/2652)
