### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/cli-usingcli.html

### ISSUE THREAD

**Issue by HPienaar** [zowe/docs-site#2368]
## Description
<--!The link I am trying to access is form an IBM website as well as a link from Coursera that is related to Zowe, COBOL CLI access. I assume the link used to work.-->

**Comment by nannanli** [comment]
I think a redirect should be set to point people to the latest topic https://docs.zowe.org/stable/user-guide/cli-using-usingcli.

**Comment by samanthasusu** [comment]
Close as the link is updated.
