### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/zowe-getting-started.html

### ISSUE THREAD

**Issue by Thibaut69** [zowe/docs-site#2372]
## Description
When clicking on "Get started" on the page https://www.zowe.org/learn, I go to the page : https://docs.zowe.org/stable/getting-started/zowe-getting-started.html

On this latest page, I have the error 
Page Not Found

## Pages to Update
[[](https://www.zowe.org/learn)](https://docs.zowe.org/stable/getting-started/zowe-getting-started.html)

https://github.com/zowe/docs-site/issues/2372#tasklist-block-f3abe540-4736-46d1-8506-260921e18574

**Comment by samanthasusu** [comment]
@Thibaut69 Thank you so much for reporting this issue. We will update it soon.
