### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-scsplugin/

### ISSUE THREAD

**Issue by gejohnston** [zowe/docs-site#2384]
## Description

This page is listed as Zowe v2.2.x doc, but it talks about the secure credential store as a plugin, which is no longer true in V2.

## Pages to Update

https://docs.zowe.org/stable/user-guide/cli-scsplugin/

## Expected behavior

Perhaps this page should be removed? Perhaps we should alter the page to discuss the embedded SCS?

**Comment by anaxceron** [comment]
Closing as v2.4 and 2.5 documentation no longer include this page.
