### ISSUE TITLE
Explain Team Config Files

### ISSUE THREAD

**Issue by VitGottwald** [zowe/docs-site#2385]
## Is your request for enhancement related to a problem? Please describe.
It is unclear what the effect of running `zowe config init` and `zowe config secure` is with various switches (`--global-config`, `--user-config`).

## Describe the solution you'd like
It would be valuable to have a concise description / overview / picture of all files that participate in team config (profiles v2), what they are called (terminology), how they are impacted by various `zowe config` commands and how they participate in profile contents resolution when a profile is read.

**Comment by anaxceron** [comment]
Closed with [PR 2690](https://github.com/zowe/docs-site/pull/2690).

**Comment by anaxceron** [comment]
See comment above.
