### ISSUE TITLE
Add a generic Zowe release notes overview topic

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#2396]
## Is your request for enhancement related to a problem? Please describe.

Since the release notes have no static landing page, the “Review the release notes” link in the Zowe CLI [Installation checklist](https://docs.zowe.org/stable/user-guide/cli-install-cli-checklist) sends users to [Zowe overview](https://docs.zowe.org/stable/getting-started/overview). This is confusing b/c the overview doesn’t include any links to the release notes. The only mention of “release notes” is in the ToC on the left nav bar.

There are a couple of other pages ([Updating to the Zowe CLI V2 Long-term Support (v2-Its) version](https://docs.zowe.org/stable/user-guide/cli-updatingcli/#updating-to-the-zowe-cli-v2-long-term-support-v2-lts-version) and [Installing Zowe CLI](https://docs.zowe.org/stable/user-guide/cli-installcli/)) that refer readers to the latest release notes and b/c there’s no static landing page, it’s up to the doc writer to remember to update these links and it's easy to forget and then the links take the reader to an outdated set of notes.

## Describe the solution you'd like

Add some sort of static page in the Release notes section of the ToC, such as “Zowe release notes” or “Understanding release notes”.  This page could be one brief paragraph that explains what a reader can expect out of our release notes and how often they’re published.

**Comment by anaxceron** [comment]
@nannanli -- I'm happy to work on this. However, I need someone to show me how to convert the "Release Notes" header on the ToC to an actual static overview page. Not sure how to do the coding for that, or where. Please advise.

**Comment by anaxceron** [comment]
Closed w/ [PR 2502](https://github.com/zowe/docs-site/pull/2502).
