### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-using-profiles/

### ISSUE THREAD

**Issue by gejohnston** [zowe/docs-site#2398]
## Description

Underneath the `zowe config convert-profiles` command on this page, we should add a statement telling the reader that if plain text credentials exist in the original V1 profiles, the resulting V2 team configuration file zowe.config.json will also contain plain text credentials.

**Comment by adam-wolfe** [comment]
The page has moved to https://docs.zowe.org/stable/user-guide/cli-using-using-team-profiles

**Comment by anaxceron** [comment]
Closing w/ [PR 2883](https://github.com/zowe/docs-site/pull/2883)
