### ISSUE TITLE
[Troubleshooting tip] using "ZLUX_NO_CLUSTER" to control app-server cluster behavior

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2437]
On the Zowe servers, the component "app-server" has an environment variable "ZLUX_NO_CLUSTER" which controls whether or not it uses cluster mode.
Cluster mode is enabled by default.
When ZLUX_NO_CLUSTER=1 as an env var, you disable cluster mode.

When you do this, you lose these benefits:

    Performance under high user count due to lack of redundant workers
    Low-downtime when an unexpected exception occurs (only 1 interrupted request vs about 15 seconds downtime)

But, you gain this benefit:

    **There is a limitation in node where it cannot handle a network interface going down. This leads to an infinite socket read loop until the process is canceled**

To have cluster mode on:

In v1, do NOT have "ZLUX_NO_CLUSTER" in instance.env
In v2, do NOT have "zowe.environments.ZLUX_NO_CLUSTER" in zowe.yaml

To have cluster mode OFF:

In v1, have "ZLUX_NO_CLUSTER=1" in instance.env
In v2, have "zowe.environments.ZLUX_NO_CLUSTER=1" in zowe.yaml

On IBM's github, they have stated they have a fix for this so that the workaround will no longer be needed. The fix should be within all versions of nodejs 18, plus versions of nodejs post Q1 2023 for v14 and v16.

**Comment by nellietan** [comment]
Hi Sean, is this still valid? @1000TurquoisePogs

**Comment by 1000TurquoisePogs** [comment]
Yes this is still valid. I know its been a long time but that just means its been a long time that we've needed it.

**Comment by DivergentEuropeans** [comment]
@nellietan And this one as well, will you be taking it on?
