### ISSUE TITLE
Clarify the Windows version for local_cer

### ISSUE THREAD

**Issue by ActionThisDay** [zowe/docs-site#2441]
I opened an original issue as I was having trouble importing the local_ca certificate . 
https://github.com/zowe/zowe-install-packaging/issues/3105#issuecomment-1280864299

It turns out for Windows you need to import the P12 version of the local_cer. 
Windows does not recognise the PEM format. 

Perhaps you can add this clarification to the doc. 

Page: 

docs.zowe.org/v2.0.x/extend/extend-apiml/api-mediation-security/

**Comment by janan07** [comment]
Closed with https://github.com/zowe/docs-site/pull/2662
