### ISSUE TITLE
Can’t connect nor addSession onZowe

### ISSUE THREAD

**Issue by IMackie22** [zowe/docs-site#2446]
Hello I’m having trouble reconnecting with my Zowe profile. After I submitted a job, I received this following error
![3CDDB7F9-B3AB-4EC5-8C4D-CCB33C93BDCE](https://user-images.githubusercontent.com/87789451/197048017-25ed3beb-4f06-41d1-9577-f1988acd869a.jpeg)

I tried deleting my .zowe file/removing and uninstalling the program. I still have the same issue.

**Comment by nannanli** [comment]
@JillieBeanSim Hi Billie, any suggestions or advice regarding this issue? Feel free to move it to the Zowe Explore repo as needed. Thank you!

**Comment by JillieBeanSim** [comment]
Hey @nannanli I don't see the option to move to our repo, I may not have the permissions.  I am not sure what is causing the issue but will investigate, thanks.

**Comment by nannanli** [comment]
Issue moved to [zowe/vscode-extension-for-zowe #2005](https://github.com/zowe/vscode-extension-for-zowe/issues/2005) via [**Zenhub**](https://www.zenhub.com/)
