### ISSUE TITLE
Missing page for search result

### ISSUE THREAD

**Issue by achmelo** [zowe/docs-site#2448]
## Description
When I try to search for `change password` in docs site, I am presented with results. Howeve, when I click on the search result I am routed to non-existing page

## Screenshots

Search for `change password`
<img width="672" alt="Screenshot 2022-10-21 at 13 12 19" src="https://user-images.githubusercontent.com/37397715/197183408-eb436665-aa77-4b85-b7c2-45362005ba89.png">

Route to page from search bar
<img width="995" alt="Screenshot 2022-10-21 at 13 12 35" src="https://user-images.githubusercontent.com/37397715/197183444-5c823fed-f1e2-48f9-8a09-daa8ad1fe6f6.png">

**Comment by janan07** [comment]
It appears that the indexing has resolved itself. All links that appear in the search now work.
