### ISSUE TITLE
[Troubleshooting tip] Known issue - PKCS12 server keystore generation can fail on Java 8 sr7fp15, sr7fp20

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2459]
An incompatibility was found between Java and GSK regarding cryptography.
Specifically, if you use Java 8 sr7fp15 or sr7fp20 when letting Zowe server installs create a pkcs12 keystore, the keystore generated will not be readable by ZSS, causing general inability to use parts of Zowe.

If you have a preexisting keystore, you are fine.
If you do not use ZSS, you are fine, but it is on by default.
If you are using keyrings, you are fine.
If you bring your own pkcs12 files instead of letting zowe generate them, you are fine.

If you are effected, there are a few options,
* temporarily downgrade java
* or use the flags `-J-Dkeystore.pkcs12.certProtectionAlgorithm=PBEWithSHAAnd40BitRC2 -J-Dkeystore.pkcs12.certPbeIterationCount=50000 -J-Dkeystore.pkcs12.keyProtectionAlgorithm=PBEWithSHAAnd3KeyTripleDES -J-Dkeystore.pkcs12.keyPbeIterationCount=50000` when generating a keystore.

**Comment by lv198** [comment]
Java 8 SR7 FP16 also has this issue, went back to Java 8 SR7 and it works

**Comment by achmelo** [comment]
The result should be the same as using `legacy` flag, it also makes scripts more readable. 
To create a PKCS12 keystore which they can load, set the system
property "keystore.pkcs12.legacy" which overrides the values of the properties
defined below with legacy algorithms. Setting this system property (which can
only be enabled and has no value) is equivalent to

  -Dkeystore.pkcs12.certProtectionAlgorithm=PBEWithSHA1AndRC2_40
  -Dkeystore.pkcs12.keyProtectionAlgorithm=PBEWithSHA1AndDESede
   -Dkeystore.pkcs12.macAlgorithm=HmacPBESHA1
  -Dkeystore.pkcs12.certPbeIterationCount=50000
   -Dkeystore.pkcs12.keyPbeIterationCount=50000
   -Dkeystore.pkcs12.macIterationCount=100000

**Comment by samanthasusu** [comment]
> The result should be the same as using `legacy` flag, it also makes scripts more readable. To create a PKCS12 keystore which they can load, set the system property "keystore.pkcs12.legacy" which overrides the values of the properties defined below with legacy algorithms. Setting this system property (which can only be enabled and has no value) is equivalent to
> 
> -Dkeystore.pkcs12.certProtectionAlgorithm=PBEWithSHA1AndRC2_40 -Dkeystore.pkcs12.keyProtectionAlgorithm=PBEWithSHA1AndDESede -Dkeystore.pkcs12.macAlgorithm=HmacPBESHA1 -Dkeystore.pkcs12.certPbeIterationCount=50000 -Dkeystore.pkcs12.keyPbeIterationCount=50000 -Dkeystore.pkcs12.macIterationCount=100000

hi @achmelo Thanks for your illustration. Would you please check [this PR](https://github.com/zowe/docs-site/pull/2576) and see if I get your point correctly? Any comment is welcomed. Thank you!

**Comment by achmelo** [comment]
Hi @samanthasusu , I meant to replace the long version(when you specify all parameters) with a short one: -Dkeystore.pkcs12.legacy . According to keytool java documentation, they are equivalent. The second example could then be just ```-J-Dkeystore.pkcs12.legacy```

**Comment by samanthasusu** [comment]
> Hi @samanthasusu , I meant to replace the long version(when you specify all parameters) with a short one: -Dkeystore.pkcs12.legacy . They are equivalent according to keytool java documentation. The second example could then be just `-J-Dkeystore.pkcs12.legacy`

Thank you so much for your explanation. I just updated the wording [here](https://github.com/zowe/docs-site/pull/2576/commits/b254c41c7bff96c84bcbd21c5646aea52bb99b3e). Thank you for reviewing this.

**Comment by 1000TurquoisePogs** [comment]
Reopening this as it looks like the troubleshooting tip was only merged into v1 documentation, and not also v2 documentation despite effecting both.

**Comment by 1000TurquoisePogs** [comment]
I attempted to resolve that via https://github.com/zowe/docs-site/pull/2675

**Comment by 1000TurquoisePogs** [comment]
Closing due to that being merged.
