### ISSUE TITLE
Cannot chain Zowe CLI commands in a .bat / .cmd script

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/docs-site#2475]
On Windows, either the `test.bat` file with the content:

```
echo 1
zowe --version
echo 2
zowe --version
echo 3
zowe --version
```

The execution of the `test.bat` file stops after the first zowe command...

Checked on different installations with Zowe CLI versions 6.32.0 and 6.32.2 ...

**Comment by anaxceron** [comment]
Closing issue now that we have documentation for this known issue, per [PR 2500](https://github.com/zowe/docs-site/pull/2500).
