### ISSUE TITLE
Documentation for updated ZE install

### ISSUE THREAD

**Issue by anaxceron** [zowe/docs-site#2476]
Document new features/procedures in the updated ZE installation process in [PR 1993](https://github.com/zowe/vscode-extension-for-zowe/pull/1993).

**Comment by anaxceron** [comment]
@zFernand0 @JillieBeanSim @rudyflores 

I'm requesting a demo (live or recorded) for the new install process outlined in [PR 1993](https://github.com/zowe/vscode-extension-for-zowe/pull/1993). Would like to see all the steps/processes that need to be documented, and an explanation of how this benefits the user.

**Comment by rudyflores** [comment]
Demo of unsecure & regular profile creation:

https://user-images.githubusercontent.com/68666202/201197590-d96bafdd-4cdf-4898-8692-ef35a72780a7.mov

**Comment by anaxceron** [comment]
Closed with [PR 2494](https://github.com/zowe/docs-site/pull/2494)
