### ISSUE TITLE
Document how to update the zftp credentials using ZOWE CLI V2

### ISSUE THREAD

**Issue by jeevakp** [zowe/docs-site#2488]
Documentation for updating Credentials over command line with ZOWE CLI V2 is not documented. My MVS password changed, but am not able to change the password for zftp profile using the zowe config set. ZOWE explorer extension in VSCODE profiles support for update credentials only for zosmf and uss. Can someone help, how should I update the zftp credentials using ZOWE CLI V2.

**Comment by anaxceron** [comment]
Hi @jeevakp  -- we document how to use the `zowe config set` and `zowe config secure` commands in [Managing credential security](https://docs.zowe.org/stable/user-guide/cli-using-team-managing-credential-security). 

Do you think this topic is sufficiently/appropriately documented? Or are there any changes you'd like to suggest to make this topic easier to understand/easier to find?

**Comment by anaxceron** [comment]
Closing as the `zowe config set` and `zowe config secure` commands have been documented in [Managing credential security](https://docs.zowe.org/stable/user-guide/cli-using-team-managing-credential-security/) and have not received any additional feedback from @jeevakp
