### ISSUE TITLE
[Troubleshooting tip] Identifying a keyring issue

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2492]
### 2. Choose a title

Troubleshooting R_datalib keyring errors

### 3. Symptom

If you see one or more of the following in the logs,

* ZWED0148E - Exception thrown when reading SAF keyring, e= Error: R_datalib call failed: function code: 01, SAF rc: `number`, RACF rc: `number`, RACF rsn: `number`

* java.io.IOException: R_datalib (IRRSDL00) error: profile for ring not found (`number`, `number`, `number`)

Then the cause is due to keyring configuration.
You may also see the log message
* ZWES1060W Failed to init TLS environment, rc=1(Handle is not valid)
But this log message can have other causes too, such as lack of READ permission to resources in the CRYPTOZ class.

### 4. Solution

Refer to table 2 (DataGetFirst) of this page https://www.ibm.com/docs/en/zos/2.5.0?topic=library-return-reason-codes
It describes which problem you are facing.
Then, check your keyring (such as with a LISTRING command) and your zowe configuration file's `zowe.certificate` section to spot & resolve the issue.

**Comment by nannanli** [comment]
Assigned to @nellietan to add the tip to the documentation.
