### ISSUE TITLE
Issue with docs.zowe.org/stable/getting-started/overview

### ISSUE THREAD

**Issue by tjraskin** [zowe/docs-site#2503]
## Screenshots

<img width="477" alt="image" src="https://user-images.githubusercontent.com/42775425/202293670-b004ec0b-a632-49a9-9e38-588e3849b83d.png">

## Expected behavior

Am in the Zowe Docs for Version 2.4 but, when I click on PDF, I get the Zowe Version 2.2 documentation.

**Comment by nannanli** [comment]
The PDF issue has been fixed. See https://docs.zowe.org/zowe-docs-v2.4.x.pdf. Closing.
Thank you very much for reporting the issue!
