### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-using-profiles

### ISSUE THREAD

**Issue by COBOL-Erik** [zowe/docs-site#2515]
## Description
zowe profiles commands are no longer valid, yet the documentation refers to zowe profiles commands and not zowe config commands.

## Pages to Update
docs.zowe.org/stable/user-guide/cli-using-using-profiles

## Additional context
It is unclear how a Zowe CLI user should work with profiles now in v2.

**Comment by anaxceron** [comment]
Closing w/ [PR 2732](https://github.com/zowe/docs-site/pull/2732)
