### ISSUE TITLE
Enhancement for `cli-using-initializing-team-configuration`

### ISSUE THREAD

**Issue by zFernand0** [zowe/docs-site#2524]
## Description

I have 2 small enhancements requests
1. It'd be ideal if the documentation reflected the aggregation feature of running the `zowe config init` (or `zowe config auto-init`) multiple times
    These steps should help illustrate this aggregation behavior:
    - Assuming you already have a `zowe.config.json` file created (run `zowe config init` to create one)
    - Install a new plugin (example: `zowe plugins install @zowe/cics-for-zowe-cli`)
        - Note: the `zowe.schema.json` file will be automatically updated after the plugin installation
    - Run `zowe config init` again
    - Notice that the profiles corresponding to the plugin are added (e.g. `cics: { ... }`)
2. Maybe we should mention that the `auto-init` functionality only works for services that support SSO 
    ` to automatically access the services that are registered to the API ML` -> ` to automatically access the services that are registered to the API ML and support Single Sign-On`
    
## Pages to update
https://docs.zowe.org/stable/user-guide/cli-using-initializing-team-configuration/#create-team-profile-configuration-files

## Additional Context
This is somewhat related to:
- #487

**Comment by anaxceron** [comment]
Closing w/ [PR 2537](https://github.com/zowe/docs-site/pull/2537)
