### ISSUE TITLE
Update node.js software requirement to point to Shopz

### ISSUE THREAD

**Issue by armstro** [zowe/docs-site#253]
The current documentation points to node.js trial code that will be going away in Jan 2019 to be replaced by a no-charge version of node downloadable by Shopz. 

[ENUS918-171.PDF](https://github.com/zowe/docs-site/files/2616876/ENUS918-171.PDF)

**Comment by nannanli** [comment]
Latest update from Slack: 
> the node.js team plans to continue publishing pax.Z drivers on IBM Developer https://developer.ibm.com/node/sdk/ztp/ (so doc continues to be correct on this point.) However the latest is now 6.14.4.1 and there are two ways to get the code either Shopz or IBM Developer. The binaries are identical to what you'd get for the no-charge node.js via Shopz (in SMP/E format).....or the pax file on Developer. Same code just packaged differently.   It is recommended that all Zowe customers move to that level (or newer), as the previous "trial" versions had a test that forced the need to update the code once the evaluation period expired.  It is recommended to  update the docs to explicitly say 6.14.4.1 or newer.

**Comment by armstro** [comment]
Where can I find the exact text ? I would like the node.js team to review. I am concerned there may still be confusion.

**Comment by nannanli** [comment]
Hi Bruce, @armstro, this is the link to the topic that discusses Node.js: https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/systemrequirements.md

We still point users to https://developer.ibm.com/node/sdk/ztp but the Node.js version is updated to be 6.14.4.1.

**Comment by armstro** [comment]
Let me have the node.js team review and see if they will provide advice. I don't think we want to point to https://developer.ibm.com/node/sdk/ztp  because the node.js code expires in 90 days. That was ok for Zowe Open Beta but for Zowe 1.0 we need customers to have a level of node that does not expire.

**Comment by armstro** [comment]
The node.js team has provided a blog on how to obtain node depending on the use case by the customer https://developer.ibm.com/mainframe/2019/04/17/ibm-sdk-for-node-js-z-os-at-no-charge/ It might be useful for zowe doc to point to this blog for additional info

**Comment by nannanli** [comment]
@armstro Hi Bruce, the Zowe doc has been updated to point users to that blog as well as summarized briefly the two ways users could use to satisfy the prerequisite for Zowe. It would be great if you could take a look at the doc. See https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/install-nodejs-zos.md. 

@Joe-Winchester Hi Joe, some updates to Node.js install. See above. Wondering if you could review that too to keep me honest. 

Thanks!
