### ISSUE TITLE
Page Not Found: docs.zowe.org/v1.26.x/getting-started/overview

### ISSUE THREAD

**Issue by seniorkj** [zowe/docs-site#2553]
## Description
Broken link on https://www.zowe.org/download#download-v1 to V1 Documentation

## Pages to Update
[https://www.zowe.org/download#download-v1]

## Additional context
Under heading 'All Zowe V1.x Releases' clicked link to Documentation next to V1.26.

**Comment by nannanli** [comment]
Thank you for reporting the issue! We're working on this and will give an update here soon.

**Comment by janan07** [comment]
This bug has been resolved.
