### ISSUE TITLE
404 on api-gateway-configuration#personal-access-token

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2557]
## Description
Clicking on the link [configuration guide](https://github.com/zowe/docs-site/blob/master/docs/user-guide/api-mediation/api-gateway-configuration#personal-access-token) from page [Personal Access Token](https://github.com/zowe/docs-site/blob/master/docs/user-guide/api-mediation/api-mediation-personal-access-token.md) displays HTTP 404 Not Found.

## Pages to Update
[](https://github.com/zowe/docs-site/blob/master/docs/user-guide/api-mediation/api-gateway-configuration#personal-access-token)

## Screenshots
![image](https://user-images.githubusercontent.com/3938398/208422676-850e3fbf-04bd-48f0-be3b-edfe3a050f4d.png)

## Expected behavior
Doc page displayed

**Comment by nannanli** [comment]
Thank you for creating the issue! Assigned to @janan07 to fix the link.

**Comment by janan07** [comment]
Link is functional in the published doc: https://docs.zowe.org/stable/user-guide/api-mediation/api-gateway-configuration#personal-access-token
