### ISSUE TITLE
Configuring Zowe Explorer - info about "Jobs: Confirm Submission" option

### ISSUE THREAD

**Issue by traeok** [zowe/docs-site#2561]
## Is your request for enhancement related to a problem? Please describe.

A feature will be added to Zowe Explorer that gives the user the option to confirm their submission for the "Submit Job" feature in the Data Sets panel. Since the feature has multiple options, it would be best to document this feature in the [Configuring Zowe Explorer](https://docs.zowe.org/stable/user-guide/ze-install#configuring-zowe-explorer) section.

See https://github.com/zowe/vscode-extension-for-zowe/pull/2054 for more info.

## Describe the solution you'd like

Add some context on this option to the Configuring Zowe Explorer section, as users might want to enable/customize it for their own usage, e.g.:

"For some users, running a job without confirmation can cause a myriad of problems on their server, and hence a confirmation option could be useful before accidental submission w/ Zowe Explorer's 'Submit Jobs' feature. This option will enable a confirmation dialog that appears when using the "Submit Job" functionality. By clicking 'Submit', the user confirms that the use of this feature was intentional, avoiding the potential harm in an accidental misclick of Submit Jobs."

**Options:**
- *Disabled:* No confirmation dialogs will appear when submitting a job.
- *All jobs*: A confirmation dialog will appear before submitting any job.
- *Your jobs:* A confirmation dialog only appears before submitting your jobs.
- *Other user jobs:* A confirmation dialog only appears before submitting another user's job.

## Related doc pages

https://docs.zowe.org/stable/user-guide/ze-install#configuring-zowe-explorer

## Additional context

Here's what the option looks like from extension settings:
![image](https://user-images.githubusercontent.com/86500639/210436155-1bf9a66c-3a97-410d-80b8-0aeb71e760c6.png)

The dialog that appears when the above option is selected:
![image](https://user-images.githubusercontent.com/86500639/209198841-5f2c59ac-fced-447f-ba37-dd345bbff657.png)

@anaxceron

**Comment by anaxceron** [comment]
Closing with [PR 2577](https://github.com/zowe/docs-site/pull/2577).

**Comment by anaxceron** [comment]
Closing with [PR 2577](https://github.com/zowe/docs-site/pull/2577).
