### ISSUE TITLE
"configure-sysplex" - Page Not Found 

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2564]
## Description
The reference to page "configure-sysplex" is not found when linking from 
https://docs.zowe.org/stable/user-guide/zowe-ha-overview/#enable-high-availability-when-zowe-runs-in-sysplex

## Pages to Update
[](https://docs.zowe.org/stable/user-guide/zowe-ha-overview/#enable-high-availability-when-zowe-runs-in-sysplex)

## Expected behavior
Display the requested page

**Comment by nannanli** [comment]
Thank you for creating the issue! 
Assigned to @nellietan to work on this.
