### ISSUE TITLE
"systemrequirements-zosmf-ha" - Page Not Found

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2565]
## Description
[configure z/OSMF for high availability in Sysplex](https://docs.zowe.org/stable/user-guide/zowe-ha-overview/systemrequirements-zosmf-ha).
- Page Not Found  - reference from https://docs.zowe.org/stable/user-guide/zowe-ha-overview/#enable-high-availability-when-zowe-runs-in-sysplex

## Pages to Update
https://docs.zowe.org/stable/user-guide/zowe-ha-overview/#enable-high-availability-when-zowe-runs-in-sysplex

## Expected behavior
Display the requested page

**Comment by nannanli** [comment]
Thank you for taking the time to report this issue! 
@nellietan will fix the issue.
