### ISSUE TITLE
Configuring Zowe Explorer - Info about Error dialog for invalid profiles

### ISSUE THREAD

**Issue by traeok** [zowe/docs-site#2569]
## Is your request for enhancement related to a problem? Please describe.

A feature will be added to Zowe Explorer that displays an error message when one or more Zowe profiles are invalid. It also provides a "Show Config" button to view the config w/ culprits. Since this is a new addition to ZE UX and might arise during initial configuration, it would be best to document this feature in the [Configuring Zowe Explorer](https://docs.zowe.org/stable/user-guide/ze-install#configuring-zowe-explorer) section.

See https://github.com/zowe/vscode-extension-for-zowe/pull/2056 for more info.

## Describe the solution you'd like

Add some context on this error dialog to the "Configuring Zowe Explorer" section:

"When a v1 Zowe profile is invalid, or if there are issues loading your v2 Zowe config, Zowe Explorer will display an error message that it cannot read your Zowe configs. By clicking the 'Show Config' button, Zowe Explorer will open an editor view for the config that contains problems that need resolved."

## Related doc pages

https://docs.zowe.org/stable/user-guide/ze-install#configuring-zowe-explorer

## Additional context

Here's what the error dialog looks like:
![image](https://user-images.githubusercontent.com/86500639/210419853-979fb832-ccf7-416a-a81e-1e86bf1ef86f.png)

@anaxceron

**Comment by anaxceron** [comment]
Closing w/ [PR 2502](https://github.com/zowe/docs-site/pull/2502).
