### ISSUE TITLE
[Troubleshooting tip] node not found

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2573]
### 1. Slack conversation link (if any)

https://github.com/zowe/community/issues/1789

### 2. Choose a title

zwe fails with `node: ... FSUM7351 not found`

### 3. Symptom

Running a `zwe` command fails with the above

### 4. Solution

https://github.com/zowe/community/issues/1789#issuecomment-1372262908

**Comment by nellietan** [comment]
The issue has been addressed with https://github.com/zowe/docs-site/pull/2578

**Comment by DivergentEuropeans** [comment]
Re-opening because Doc PR doesn't contain "FSUM7351"

**Comment by nellietan** [comment]
Hi @DivergentEuropeans , could you review the update with "FSUM7351" added? https://654c873a4cf70143e90f5300--zowe-docs-master.netlify.app/stable/appendix/zowe-yaml-configuration#yaml-configurations---java  Let me know if it is good to go, thanks!

**Comment by DivergentEuropeans** [comment]
Apologies I missed your tag @nellietan . You're welcome to ping me any time on Slack.

Thanks @samanthasusu , thanks gang
