### ISSUE TITLE
Zowe supports TLS in version 1.3 but it isn't mentioned anywhere

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/docs-site#2591]
## Is your request for enhancement related to a problem? Please describe.
Zowe support TLS in version 1.2 and 1.3 and while we do mention a TLS as such a lot in documentation, it seems that we are missing the information about the supported version. 

## Describe the solution you'd like
In a page focusing on Zowe configuration mention both of the versions and the impacts they have.

**Comment by janan07** [comment]
The doc for versions 1.2 and 1.3 are no longer supported. Please include more details if this note should be added for later versions.

**Comment by balhar-jakub** [comment]
The Zowe in the latest 1.x and 2.x stream support TLS protocol (https). The TLS protocol has multiple versions. We support the version 1.2 and 1.3 for both version streams. 

We need to add this information somewhere.

**Comment by janan07** [comment]
Resolved with https://github.com/zowe/docs-site/pull/2668
