### ISSUE TITLE
Enhance the search experience

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#2606]
- Releases like v2.4, v2.5 were not indexed properly for search.
- Removed files still show up in the search results which causes confusion.
- Search results lead to empty pages. “When I try to search for change password in docs site, I am presented with results. However, when I click on the search result I am routed to non-existing page”   - achmelo

Also, see this thread for more discussions: https://openmainframeproject.slack.com/archives/CC961JYMQ/p1673308867175179

**Comment by samanthasusu** [comment]
Close because it's resolved.
