### ISSUE TITLE
Add instructions to override the destination directory of temporary files

### ISSUE THREAD

**Issue by pablocarle** [zowe/docs-site#2621]
## Is your request for enhancement related to a problem? Please describe.
The main analysis is here: https://github.com/zowe/zowe-install-packaging/issues/3236
There's a bug up to Zowe 2.6 that makes zowe ignore overrides to the temporary directory variables.
2.7 will include the fix.

## Describe the solution you'd like
Docs should describe the procedure to update the destination temporary directory in the installation and run.
There are three variables that control this behaviour now, the issue 3236 shared above is to improve this by providing only one variable.
The current ones are:
`TMPDIR`, `TEMP_DIR` and `CATALINA_TMPDIR`

## Related doc pages
No current doc page covers this topic.

## Additional context
This issue is important because customers may have reasons to update the directory to not affect other products that use the main `/tmp` uss directory.
We confirm that the Zowe installation creates thousands of these temporary files during normal operation.

**Comment by janan07** [comment]
Addressed with https://github.com/zowe/docs-site/pull/2656
