### ISSUE TITLE
Minor typo ZWESI00 instead of ZWESIS01

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/docs-site#2635]
This section refers to ZWESI00 instead of ZWESIS01
https://docs.zowe.org/stable/user-guide/configure-xmem-server/#summary-of-cross-memory-server-installation

For example, 
PPT PGMNAME(ZWESI00) KEY(4) NOSWAP

should be

PPT PGMNAME(ZWESIS01) KEY(4) NOSWAP

**Comment by samanthasusu** [comment]
Thank you for reporting this issue to us! Would you please review this PR[#2637 ](https://github.com/zowe/docs-site/pull/2637)and let me know if it is good to go? Thanks
