### ISSUE TITLE
APIML troubleshooting present in Appfw section

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#2649]
https://github.com/zowe/docs-site/pull/2620 acted upon https://github.com/zowe/docs-site/issues/2492 by adding the tips to the app framework section of troubleshooting, but there is a problem with that.
`java.io.IOException` isn't related to the app-framework.
If people are searching for a keyring problem that's occurring in the api mediation layer, they may not find it due to it being here.
The information in this PR should be moved to a more general location. I suggest making a troubleshooting document within the servers folder https://github.com/zowe/docs-site/tree/master/docs/troubleshoot/servers because then information that applies to multiple servers of zowe can be found, rather than overlooking help only present in 1 server (app-server) or another (zss, apiml gateway, etc)

**Comment by janan07** [comment]
After discussing this with the API ML squad, they suggest we put this error to Troubleshooting API ML. I will add this content to that article for now.
