### ISSUE TITLE
Zowe feature support update

### ISSUE THREAD

**Issue by samanthasusu** [zowe/docs-site#2676]
## Description
Hi Zowe-Doc, the latest doc currently makes claims about IPV6 support which may not be accurate.  Please reach out to the relevant squads to request statements of support bearing in mind the difference between theoretical support (we think it should work) and actual support (our test regimen includes IPv6 tests).

## Pages to Update
[
](https://docs.zowe.org/stable/getting-started/zowe-feature-support/)
## Screenshots
<img width="256" alt="image (16)" src="https://user-images.githubusercontent.com/95402892/220624365-6fb082b4-fbf3-4634-9971-cbce30dce368.png">

## Expected behavior
Update the feature support information accordingly.

**Comment by balhar-jakub** [comment]
We should also delete the row with the MFA Token Support. 
As for the IPv6 we shouldn't claim the support until we test on marist, which is linked to the issue https://github.com/zowe/community/issues/1024

**Comment by balhar-jakub** [comment]
Possibly instead of removing the row, claim the latest update date and use TBD as the state.

**Comment by balhar-jakub** [comment]
The change needs to be propagated at least to the latest v1.x and v2.x version of docs.

**Comment by balhar-jakub** [comment]
@adam-wolfe That's a good point. I believe that as a final version we should have a table with the information on the key features and support to areas such as z/OMSF version, z/OS versions and other topics that spans the whole Zowe project. 

It probably should become part of the overview - https://docs.zowe.org/stable/getting-started/overview or in the final version it may be sizeable enough to actually ask for it's own page. 

For now, I would as a next step, just clean the table. With the next action item being to figure out what are the other topics and features that needs to be added and how.

**Comment by anaxceron** [comment]
Updating after chatting w/ Jakub: 

- We are closing this issue. 
- @balhar-jakub will open a new issue to address the items he has mentioned.

**Comment by samanthasusu** [comment]
Close #2647 until further features or topics to be added.
