### ISSUE TITLE
The explorer names should be corrected.

### ISSUE THREAD

**Issue by chentingcathy** [zowe/docs-site#279]
## Description
A clear and concise description of what the error is.
I find that the explorer names seem not correct: 
Data set Explorer -> should be MVS Explorer
UNIX file Explorer -> should be USS Explorer
## Pages to Update
https://zowe.github.io/docs-site/...
https://zowe.github.io/docs-site/latest/user-guide/mvd-using.html#using-explorers-within-the-zowe-desktop

**Comment by jhenryRocket** [comment]
Pushed this fix to doc-staging branch
