### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/initialize-mvs-datasets/

### ISSUE THREAD

**Issue by alvaroandresgarayromero** [zowe/docs-site#2826]
## Description

- The Description section shows an example where authLoadlib is set to IBMUSER.ZWE.CUST.ZWESALL. However, in the Procedure section it shows authLoadlib set to IBMUSER.ZWEV2.SZWEAUTH.
- The example-zowe.yaml sets authoLoadLib to IBMUSER.ZWEV2.SZWEAUTH.

## Pages to Update
- Initializing Zowe custom data sets

## Expected behavior
- The first example should be updated to be consistent with all other examples where authoLoadLib is set to IBMUSER.ZWEV2.SZWEAUTH.

**Comment by samanthasusu** [comment]
Thank you for reporting this. Resolved now.
