### ISSUE TITLE
Restore "Tips for efficient configuration" in Zowe v2 docs

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/docs-site#2839]
In the Zowe v1 docs, we included "Tips for efficient configuration" in our article about team config (in technical preview at the time):
https://docs.zowe.org/v1.28.x/user-guide/cli-using-global-profile-configuration/#tips-for-efficient-configuration

These tips included "Command option order of precedence" and "Tips for using the base profile".

This information, particularly the list of the CLI's order of precedence, is still useful info for Zowe v2, but I can't find it in our docs anymore:
> 1. Explicit command-line option values
> 2. Environment variables
> 3. Service type profiles
> 4. Base type profiles
> 5. Default option value

**Comment by anaxceron** [comment]
@t1m0thyj -- There's a [How command preference works](https://docs.zowe.org/stable/user-guide/cli-using-command-precedence) article now. Is this what you're looking for? There's also [How Zowe CLI uses configurations](https://docs.zowe.org/stable/user-guide/cli-using-understand-profiles-configs), which seems to cover the same or similar topic.

Should we edit this content in any way? Add more content? Restore content? Please le me know.

**Comment by t1m0thyj** [comment]
Thanks, not sure why I had trouble finding this - maybe I was dumb or it was related to indexing problems we had with the docs-site until recently 😅 

The tips for "Command option order of precedence" are present in the article you linked 👍 Also I found similar content to "Tips for using the base profile" [here](https://docs.zowe.org/stable/user-guide/cli-using-using-team-profiles/#zowe-cli-profile-types) so I think this is good to close 😸
