### ISSUE TITLE
Search box overlaps Zowe 

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#285]
## Description
When you reduce the window size (not Tablet mode) the search box in the menu bar overlaps Zowe. 
## Pages to Update
NA

## Screenshots
See attached.

## Expected behavior
When i reduce the window, the menu bar should switch to Tablet view just as the search box is about to overlap Zowe. 

## Additional context
NA
![capture](https://user-images.githubusercontent.com/36677566/49663374-6f694b80-fa1c-11e8-8f2c-c713098e8205.PNG)

**Comment by jackjia-ibm** [comment]
@JamesBauman Is this still an issue?
