### ISSUE TITLE
Issue with docs.zowe.org/stable/extend/extend-apiml/certificate-management-in-zowe-apiml/

### ISSUE THREAD

**Issue by alvaroandresgarayromero** [zowe/docs-site#2853]
## Description

In section `Import the local CA certificate to your browser` the following path is described <RUNTIME_DIR>/bin/zowe-setup-certificates.env. However, is appears that `zowe-setup-certificates.env `has been deprecated per [work item](https://github.com/zowe/zowe-install-packaging/pull/2521) 

## Expected behavior

The description needs to be updated that the certificate path can be defined in the `zowe.setup.certificate` section in the zowe yaml configuration file.

**Comment by samanthasusu** [comment]
Thank you for reporting this. We will also update this part in next release.
cc @Joe-Winchester

**Comment by skurnevich** [comment]
The issue with mentioning v1 configuration file in v2 docs still there: 
https://docs.zowe.org/stable/user-guide/import-certificates/#manually-importing-a-certificate-authority-into-a-web-browser
also zowe-setup-certificates.env mentioned on that page 
https://docs.zowe.org/stable/troubleshoot/troubleshoot-apiml/#insecure-fix

**Comment by Joe-Winchester** [comment]
Thanks @skurnevich ,   I've created a small PR https://github.com/zowe/docs-site/pull/3817 and added you and @janan07  as reviewers.   
Put master as the merge branch as this content should go into v2 as well as v3.  
Cheers !
