### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-test-zosmf-connection/

### ISSUE THREAD

**Issue by alvaroandresgarayromero** [zowe/docs-site#2856]
## Description

There is a broken link that no longer works "`Working with Certificates`"

## Expected behavior

The documented link should route the reader to the target website successfully.

**Comment by sidharthbh8** [comment]
!assign

**Comment by samanthasusu** [comment]
Close because the fix branch is merged. Thanks.
