### ISSUE TITLE
Allow Users to adjust the size of the TOC frame in the browser 

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#286]
## Describe the solution you'd like
Lets allow users to have the capability to adjust the width of the frame that contains the TOC
Optionally, let users Show/Hide the TOC frame 

## Additional context
Usability enhancement
![capture4](https://user-images.githubusercontent.com/36677566/49663738-983e1080-fa1d-11e8-9dc6-2e71fd42839b.PNG)

**Comment by covalentbond** [comment]
Fixed in #1739.
