### ISSUE TITLE
Issue with docs.zowe.org/stable/extend/extend-apiml/api-mediation-sso

### ISSUE THREAD

**Issue by alvaroandresgarayromero** [zowe/docs-site#2867]
## Description

`User guide for SSO in Zowe CLI ` link is broken
 
## Expected behavior

`User guide for SSO in Zowe CLI ` link should route reader to target website.

**Comment by janan07** [comment]
The link is working properly. https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-sso/
