### ISSUE TITLE
Page Not Found: docs.zowe.org/latest/user-guide/cli-installcli.html

### ISSUE THREAD

**Issue by pfgdrupalas** [zowe/docs-site#2886]
## Description
On page - https://www.ibm.com/docs/en/zsms1/1.5.1?topic=configuring-roadmap-zowe-installation-configuration - and the 2 links on this page both go to page not found:
Verifying installation - https://www.ibm.com/links?url=https%3A%2F%2Fzowe.github.io%2Fdocs-site%2Flatest%2Fuser-guide%2Finstall-zos.html%23verifying-installation
Testing connection to z/OSMF - https://www.ibm.com/links?url=https%3A%2F%2Fzowe.github.io%2Fdocs-site%2Flatest%2Fuser-guide%2Fcli-installcli.html%23testing-zowe-cli-connection-to-z-osmf

## Pages to Update
[](https://www.ibm.com/docs/en/zsms1/1.5.1?topic=configuring-roadmap-zowe-installation-configuration)

## Screenshots
![image](https://github.com/zowe/docs-site/assets/13539212/7f21facf-684f-47a5-b691-dbd7eb747478)

**Comment by samanthasusu** [comment]
Thank you for reporting this issue. Will contact SMU team to fix that!
