### ISSUE TITLE
Add section to docs on how to determine the version of Zowe (including all component)

### ISSUE THREAD

**Issue by nkocsis** [zowe/docs-site#2903]
## Is your request for enhancement related to a problem? Please describe.
Describe how to determine what level of Zowe a system is on.

## Describe the solution you'd like
This should show the steps/commands to do this

**Comment by samanthasusu** [comment]
Thank you Nick for proposing this action. I'm wondering if any standards you have for users to determine the version. If there are some existing standards or conditions that we can follow, would you mind providing them here so that we could have some discussion? Thank you!

**Comment by nkocsis** [comment]
@Joe-Winchester Joe, is this something you can help with ?

**Comment by anaxceron** [comment]
@janan07 @samanthasusu @nellietan -- I have added my client-side content to [Checking your Zowe version release number](https://docs.zowe.org/stable/troubleshoot/troubleshoot-check-your-zowe-version). Please add the content for your server-side components so that we can close out this issue.

**Comment by anaxceron** [comment]
Closed as others have added/reviewed content.
