### ISSUE TITLE
The ZSS is a server side component of Zowe that should be listed alongside API ML and the Desktop

### ISSUE THREAD

**Issue by hogstrom** [zowe/docs-site#2905]
## Description
On the page in question the server-side elements of Zowe highlight the API ML as well as the Desktop.  More accurately, the ZSS (ZIS) should be included in this capability as the ZSS provides a rich set of API accessible interfaces to z/OS capabilities.   From the API doc we see "It contains services for essential z/OS abilities such as working with files, datasets, and ESMs, but is also extensible by REST and Websocket "Dataservices" which are optionally present in App Framework "Plugins"."

## Pages to Update
https://docs.zowe.org/stable/user-guide/zowe-getting-started-tutorial

## Screenshots
![image](https://github.com/zowe/docs-site/assets/2906023/4707b4d9-cb97-4fac-8147-842cbcdb7750)

Note the missing references to ZSS.  Also of note, API ML can run in a container environment off-platform so API ML is an on and off platform capability.

## Expected behavior
An additional paragraph about ZSS under the "Zowe server-side components"

**Comment by samanthasusu** [comment]
Thank you for pointing this out. Will add more clarification soon.

**Comment by janan07** [comment]
Addressed in P[R 2943](https://github.com/zowe/docs-site/pull/2943)
