### ISSUE TITLE
API layer github url points to gizafoundation

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/docs-site#292]
## Description

There are several documents under `docs/extend/extend-apiml` folder link back to https://github.com/gizafoundation/api-layer.

## Pages to Update

- docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
- docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
- docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
- docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
- docs/extend/extend-apiml/api-mediation-security.md

## Expected behavior

Should link back to https://github.com/zowe/api-layer.

**Comment by nannanli** [comment]
Checked the files and all occurrences are replaced now. Closing this issue.
