### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-using-profiles-v1

### ISSUE THREAD

**Issue by zFernand0** [zowe/docs-site#2946]
## Description

The order of precedence seems to be missing in Zowe V2 content.

## Pages to Update

We may need a new header/section under the Using CLI page
- https://docs.zowe.org/stable/user-guide/cli-using-usingcli

## Screenshots

![image](https://github.com/zowe/docs-site/assets/37381190/9a2b5c6d-4848-460f-9387-9efb77c34bbe)

## Expected behavior

To be directed to this sort of content:
- https://docs.zowe.org/v1.28.x/user-guide/cli-usingcli#how-command-precedence-works
- https://docs.zowe.org/v1.28.x/user-guide/cli-using-global-profile-configuration#command-option-order-of-precedence

## Additional context

This was discovered while trying to explain how the python SDK should behave when it comes to Environment Variables

**Comment by anaxceron** [comment]
After discussing w/ Fernando, the page that needs a link fix is this one: [Using V1 profiles](https://docs.zowe.org/stable/user-guide/cli-using-using-profiles-v1#profile-best-practices)

**Comment by anaxceron** [comment]
Fixed w/ [PR 2947](https://github.com/zowe/docs-site/pull/2947)
