### ISSUE TITLE
Installing Zowe z/OS Runtime - diagram not readable in dark mode 

### ISSUE THREAD

**Issue by pinpan** [zowe/docs-site#2957]
## Description
See the title. The user has to click on the diagram to see it in light mode.

## Screenshots
![image](https://github.com/zowe/docs-site/assets/3938398/72baecbb-b24f-4788-86d1-95132d8f6719)

**Comment by samanthasusu** [comment]
Thank you for pointing this out. 
@nellietan Would you please take a look at this and see if we could change the background color of each block? Thank you! Let me know if you need any help.
