### ISSUE TITLE
(Zowe Server Install Study) Create Scenario-Based Articles by Install Method

### ISSUE THREAD

**Issue by jalel01** [zowe/docs-site#2960]
## Is your request for enhancement related to a problem? Please describe.
Users find the install/config/verify flow difficult to follow as well as assuming too much user knowledge.

## Describe the solution you'd like
As the Sysprog responsible for Zowe, i need a linear installation/configuration/verify procedure so my team and I can easily manage and complete the process. Additionally, for each step and procedure, I want to understand what I am doing, why I am doing it, the expected outcome, and any validation steps or indications of success. This architecture and level of detail will help us understand tasks, troubleshoot errors, and know when it is acceptable to go to the next step or procedure.
Provide co-located, linear scenario-based articles for each installation/configuration method.

Document four linear, co-located installations scenarios by method:

Note: For all methods, include instructions to also install maintenance, which they may need on top of the SW file.

- Install Zowe via z/OSMF (from PSWI & SMP/E Workflow)
- Install Zowe via SMP/E
- Install Zowe via Convenience Build
- Install Zowe via Container

Each procedure addresses the following needs:

1. Each scenario: 

- leads with a workflow diagram identifying key tasks and the role who completes each one
- includes a prominent note named Roles & Responsibilities to ID the roles required in every single article

2. For all steps, ensure that we describe:

- the action
- the reason why we are taking the action
- the expected outcome
- any troubleshooting should the step fail OR pointers to existing troubleshooting topics

3. For all procedures, ensure that we describe:

- the indicator of success or failure
- a means to verify that the procedure was successful
- any troubleshooting steps OR pointers to existing troubleshooting topics
- For all commands, add multiple real-world examples

Note: In addition to this re-architecture, we need to apply SEO principles to the Troubleshooting content (https://docs.zowe.org/stable/troubleshoot/troubleshooting). Several installers did not realize we had comprehensive TS content and some who did still could not find what they needed from Google or from co-workers.

## Suggested revised architecture: Install Zowe Server-side Components

- Server-side Installation Overview
- Prepare for Installation 
      - Installation Checklist (only one)
      - Review Install/Config Best practices
      - Address z/OS Requirements
      - Address Security Requirements
      - Address USS Requirements
      - Address node.js Requirements
      - Address Storage Requirements
      - Address Network Requirements
- Install Zowe via z/OSMF (from PSWI & SMP/E Workflow)
- Install Zowe via SMP/E
- Install Zowe via Convenience Build
- Install Zowe via Container
- Verify Your Installation 

## Related doc pages
![image](https://github.com/zowe/docs-site/assets/47416452/32e70ee1-946f-4598-9bf3-5095acae2b1c)

## Additional context
This enhancement request comes directly from user feedback received during the Spring 2023 Zowe Server Installation Study which uncovered several common challenges for the Zowe install/config process.

**Comment by janan07** [comment]
After discussion, we decided that the installation section should be separated from the configuration section to prevent multiple duplications of all of the configuration steps.
SO the orginal:
Install and Configure Zowe via z/OSMF (from PSWI & SMP/E Workflow)
Install and Configure Zowe via SMP/E
Install and Configure Zowe via Convenience Build
Install and Configure Zowe via Container
Should be changed to:
Install  Zowe via z/OSMF (from PSWI & SMP/E Workflow)
Install  Zowe via SMP/E
Install  Zowe via Convenience Build
Install Zowe via Container
followed by:
Configure z/OS Components

**Comment by samanthasusu** [comment]
#3058 is for this issue.
