### ISSUE TITLE
(Zowe Server Install Study) Create Scenario-Based Article to Customize API ML

### ISSUE THREAD

**Issue by jalel01** [zowe/docs-site#2967]
## Is your request for enhancement related to a problem? Please describe.
Today some of the API ML configuration content appears after the install is completed & verified in the section Advanced Server-side configuration > API Mediation Layer. Organising this content by component, with long lists of optional configuration in a seemingly random order (see https://docs.zowe.org/stable/user-guide/api-mediation/api-gateway-configuration), makes it hard for the Zowe install team to decipher what and why to configure as an optional extra.

## Describe the solution you'd like
Organize this existing content into scenarios and rename it Customize Zowe API ML.

Consider linear scenarios that better explain [the six+ API ML configuration articles](https://docs.zowe.org/stable/user-guide/configure-data-sets-jobs-api) that today appear well after install is done (renamed as Customize API ML). These articles establish when and why to execute these options and by whom. 

## Related doc pages
![image](https://github.com/zowe/docs-site/assets/47416452/04dd0219-f3fc-4ab8-a1c7-64c4b690441d)

## Additional context
This enhancement request comes directly from user feedback received during the Spring 2023 Zowe Server Installation Study which uncovered several common challenges for the Zowe install/config process.

**Comment by janan07** [comment]
Closed with changes applied to the section [Advanced API ML Configuration](https://docs.zowe.org/stable/user-guide/advanced-apiml-configuration) which now focuses on use cases.
