### ISSUE TITLE
Issue with docs.zowe.org/stable/troubleshoot/ze/troubleshoot-ze

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/docs-site#2979]
## Description

The Zowe Explorer log path is missing a directory name: `C:\Users\userID\.vscode\extensions\logs`

## Pages to Update

https://docs.zowe.org/stable/troubleshoot/ze/troubleshoot-ze

## Screenshots

<img width="914" alt="image" src="https://github.com/zowe/docs-site/assets/22344007/6b98f701-d4a3-44c7-b4f7-f4d3f89a47c7">

## Expected behavior

The path should be updated to: `C:\Users\userID\.vscode\extensions\zowe.vscode-extension-for-zowe-X.Y.Z\logs`

## Additional context

The path may slightly vary on other operating systems, not sure if we want to mention this. For example on Linux or Mac:
`~/.vscode/extensions/zowe.vscode-extension-for-zowe-X.Y.Z/logs`

It could also vary if someone has a non-standard install of VSCode that stores extensions under a different directory.

**Comment by anaxceron** [comment]
Closing w/ [PR 2997](https://github.com/zowe/docs-site/pull/2997)
