### ISSUE TITLE
Document recommended / supported browsers for Zowe's API Catalog

### ISSUE THREAD

**Issue by pablocarle** [zowe/docs-site#2985]
## Is your request for enhancement related to a problem? Please describe.

There are known limitations and visual issues with API Catalog opened in Firefox.

## Describe the solution you'd like
Document a recommendation to use Google Chrome as the supported version

**Comment by 1000TurquoisePogs** [comment]
It would be shocking not to support firefox, and I've seen customers who have a policy against chrome for some reason. The rest of the browser code supports the 4 major browsers: https://docs.zowe.org/stable/user-guide/systemrequirements-zos#zowe-desktop-requirements-client-pc
