### ISSUE TITLE
Outdated v1 reference in docs.zowe.org/stable/user-guide/api-mediation/api-mediation-internal-configuration/

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#3019]
Within https://docs.zowe.org/stable/user-guide/api-mediation/api-mediation-internal-configuration/#environment-variables I see the section that says:

```
    Open the file <Zowe instance directory>/instance.env.

    Add a new line with the following property:

    apiml.security.auth.provider=saf. 
```

But, instance.env does not exist in v2.
It looks like that property suggested exists in zowe.yaml in v2, so that fix could be simple, but noting this in a ticket in case this page needs further review under the lense of if it contains v1 content that needs updating to v2.

**Comment by balhar-jakub** [comment]
Fixed, will be published with next version, as such I am closing the issue.
