### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/extend/extend-apiml/authentication-for-apiml-services

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/docs-site#3110]

**Comment by samanthasusu** [comment]
Hi Jakub, may I know where this broken link exists on doc site? Thank you.

**Comment by balhar-jakub** [comment]
Here: https://docs.zowe.org/stable/getting-started/zowe-security-authentication/#authentication-with-client-certificates

**Comment by janan07** [comment]
All links work properly.

**Comment by anaxceron** [comment]
Just tested link and it still does not work. @janan07  to create PR to fix on live site.

**Comment by anaxceron** [comment]
@janan07 Link is still broken :(
