### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/getting-started/user-guide/mvd-configuration

### ISSUE THREAD

**Issue by armstro** [zowe/docs-site#3133]

**Comment by anaxceron** [comment]
@armstro -- can you tell us what page the broken link is on?

**Comment by samanthasusu** [comment]
Hi Bruce @armstro Sorry about the delay due to the national holiday. I just tested the link and it works correctly. I saw the URL that you posted in the title docs.zowe.org/stable/getting-started/user-guide/mvd-configuration. It looks like the parse went wrong but currently it works. Could you please try it and let me know if it is still not working? Thank you!

**Comment by armstro** [comment]
Hmmmm

From this page https://docs.zowe.org/stable/getting-started/zowe-security-authentication/#multi-factor-authentication-mfa the link to the For details about multi-factor authentication, see the MFA documentation here<https://docs.zowe.org/stable/getting-started/user-guide/mvd-configuration#multi-factor-authentication-configuration>. Still takes me to Page Not Found ????

***@***.***

Bruce Armstrong
IBM Z Principal Product Manager assigned to  zowe.org<https://www.openmainframeproject.org/projects/zowe>
4205 S MIAMI BLVD, DURHAM NC 27703-9141
Email: ***@***.******@***.***>
Cell: 919-931-3132

From: Wen Ting Su (Sam) ***@***.***>
Sent: Saturday, October 7, 2023 10:24 PM
To: zowe/docs-site ***@***.***>
Cc: Bruce Armstrong ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [zowe/docs-site] Page Not Found: docs.zowe.org/stable/getting-started/user-guide/mvd-configuration (Issue #3133)

Hi Bruce @armstro Sorry about the delay due to the national holiday. I just tested the link and it works correctly. I saw the URL that you posted in the title docs. zowe. org/stable/getting-started/user-guide/mvd-configuration. It looks like
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2a-oiVaV6VMRUE3YcOptBBlh41GUqEAHFSIt4UcRBitlxDQf8WsTyZ_TPK4R35haoVKvg-U3R7px--Ju7caGOzEGE66sLYfWH2g$>   ‌
ZjQcmQRYFpfptBannerEnd

Hi Bruce @armstro<https://github.com/armstro> Sorry about the delay due to the national holiday. I just tested the link and it works correctly. I saw the URL that you posted in the title docs.zowe.org/stable/getting-started/user-guide/mvd-configuration. It looks like the parse went wrong but currently it works. Could you please try it and let me know if it is still not working? Thank you!

**Comment by anaxceron** [comment]
@armstro -- The page link should be fixed by now. It works for me -- can you check if the link works for you?

**Comment by armstro** [comment]
Great - yes - thanks - you can close the issue
