### ISSUE TITLE
Text for commands on .../extend/extend-apiml/api-mediation-security.html are white

### ISSUE THREAD

**Issue by hogstrom** [zowe/docs-site#322]
## Description
When accessing the [page](https://zowe.github.io/docs-site/latest/extend/extend-apiml/api-mediation-security.html#trust-zosmf-certificate) for the API Mediation layer there are commands in the text.  The problem is the page has a white background and the text is white as well.

## Pages to Update
https://zowe.github.io/docs-site/latest/extend/extend-apiml/api-mediation-security.html#trust-zosmf-certificate

Probably should review other pages as well if they are using the same class

## Expected behavior
Text should be in a dark color that contrasts strongly against the background color.

**Comment by JamesBauman** [comment]
@janan07   - I reviewed the source markdown...  the syntax for the code blocks is missing the three code block tags ( ``` ) before and after all of the code blocks.  the content looks OK in your tool, but does not publish as expected.   we should fix this asap....

thx,
jb

**Comment by janan07** [comment]
OK. The ''' has been added to the PR.

AJ

On Thu, Jan 10, 2019 at 3:54 PM JamesBauman <notifications@github.com>
wrote:

> *CAUTION: This email originated from outside of Broadcom. Do not click
> links or open attachments unless you recognize the sender and know the
> content is safe.*
>
> @janan07
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_janan07&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=eGZwJdHPqBMdM3BKjD-4Gg&m=KUFSOIBUUxnCoyIDVSZZAhrF3u0YmSSHUghPjJNJteQ&s=UGrKMvTMX6B2Zy6kw1T90dbPLcRPllJA8zHO69mM4GA&e=>
> - I reviewed the source markdown... the syntax for the code blocks is
> missing the three code block tags ( ``` ) before and after all of the code
> blocks. the content looks OK in your tool, but does not publish as
> expected. we should fix this asap....
>
> thx,
> jb
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zowe_docs-2Dsite_issues_322-23issuecomment-2D453123049&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=eGZwJdHPqBMdM3BKjD-4Gg&m=KUFSOIBUUxnCoyIDVSZZAhrF3u0YmSSHUghPjJNJteQ&s=ZS1oUJFxK7aDrfFEwbXX7_ujqqn-ta4k89IW37UK9kw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AkkiGxPYWJYt7TPDGAIm5mT4bPokjzxiks5vB1QcgaJpZM4Z5nIc&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=eGZwJdHPqBMdM3BKjD-4Gg&m=KUFSOIBUUxnCoyIDVSZZAhrF3u0YmSSHUghPjJNJteQ&s=HGzimxUQHpnTlJqRib2MhP91nreWAiBdFg57ZOUGu8w&e=>
> .
>


-- 

*Andrew Jandacek*
Information Engineer | Mainframe
Broadcom


office: CA CZ, s.r.o. | Prague | Chodov | V Parku 2316/12 | 148 00

phone: (+420) 226 207 674
andrew.jandacek@broadcom.com | broadcom.com

**Comment by nannanli** [comment]
@janan07 Another thing is that the API Mediation Layer Security topic is missing from the TOC. Can you add it to the TOC file as well? The TOC file is config.js which is located here: docs-site\docs\.vuepress. Thanks!

**Comment by nannanli** [comment]
This issue has been fixed. Check out the latest page. Closing this issue now.
