### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-installcli

### ISSUE THREAD

**Issue by pahlow** [zowe/docs-site#3260]
## Description
The installation instructions for CLI Version: v2.12.x LTS reference downloads and package names for vNext.

## Pages to Update
https://docs.zowe.org/stable/user-guide/cli-installcli#install-zowe-cli-from-a-local-package

## Screenshots
![image](https://github.com/zowe/docs-site/assets/95501618/050604ee-ddf2-4f62-b0c1-a07341dd0a06)

## Expected behavior
Names should specify v2.12-specific links and files.

## Additional context
None

**Comment by anaxceron** [comment]
We're changing **vNext** references to **X.X.X** to indicate that this is a variable to represent the latest version of Zowe.
