### ISSUE TITLE
Clean and restructure Using Zowe API Mediation Layer focused area within the Use docs tab

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/docs-site#3269]
## Is your request for enhancement related to a problem? Please describe.
The current Use section for the API Mediation Layer is a mixture of configuration, extending and using articles. THis makes it difficult for anyone to concisely learn about the usage of the API Mediation Layer

## Describe the solution you'd like
I want the structure to change as follows:
Using Zowe API Mediation Layer

- Single Sign On (The page directly describes login, validation and update password related endpoints)
  - JWT Token (Includes the usage of the refresh) 
  - Client Certificates (Includes the usage and how to validate)
  - Personal Access Tokens (Includes the specifically PAT related APIs)
- MFA
- Routing
  - Rest APIs - Includes information on HA
  - Websocket APIs
  - GraphQL APIs
  - Multi-tenancy routing
- Learn more about APIs
  - Service Information 
  - Try it out + Code Snippets    
- Administration of APIs
  - Static refresh
  - Onboarding via Wizard 
- Caching Service

## Related doc pages
Lots of the information are scattered around the different Zowe Docs pages. But in general I would expect that if there is any specific configuration needed for the functionality, the article would in the beginning link to the Configuration in the Install section and then it would go into details on usage and if it's relevant for extending then at the end there will be link to the specific extending part. 

## Additional context
It's linked to the changes needed in Extend for API Mediation Layer outlined in #3270

**Comment by janan07** [comment]
All items have been address with the exception of onboarding via wizard which is being addressed in issue [3396](https://github.com/zowe/docs-site/issues/3396)
