### ISSUE TITLE
Page Not Found: docs.zowe.org/404

### ISSUE THREAD

**Issue by SUNDONEcindy** [zowe/docs-site#3301]

**Comment by samanthasusu** [comment]
Hi would you please let me know the exact content that is not found? Thanks.

**Comment by RafaelQRafael** [comment]
Also found a similar 404 when accessing the 2.12 PDF link on the following link:
https://docs.zowe.org/zowe-docs-v2.12.x.pdf

<img width="953" alt="404 V2 12 PDF link Zowe" src="https://github.com/zowe/docs-site/assets/146972504/fc27822b-5ea6-41df-8f35-029cf9aafd6e">

Link should direct to Zowe v2.12 PDF

**Comment by anaxceron** [comment]
Closing as it's been a month and we've received no additional information to address this.
