### ISSUE TITLE
Link to 2.13 PDF is titled for 2.12

### ISSUE THREAD

**Issue by RafaelQRafael** [zowe/docs-site#3336]
## Description

PDF download link for Zowe Documentation 2.13 leads to a PDF titled 2.12

## Pages to Update

https://docs.zowe.org/
## Screenshots

<img width="425" alt="Zowe PDF issue" src="https://github.com/zowe/docs-site/assets/146972504/69331f0c-103f-4565-8a27-88b559ff78f2">

## Expected behavior
The web link should take me to a V2.13 PDF 

## Additional context
Documentation link (https://docs.zowe.org/v2.12.x/getting-started/overview) for V2.12 PDF redirects to a "Page Not Found" as well.

**Comment by Andrew-J-Metzger** [comment]
Hi Rafael,
I did some digging and it seems https://docs.zowe.org/zowe-docs-v2.12.x.pdf is a broken link. Interestingly, https://docs.zowe.org/zowe-docs.pdf points to the  Zowe v2.12 docs. Perhaps that link always points to docs for the previous version of Zowe.

I hope this helps you. Happy New Year!
Andrew

**Comment by anaxceron** [comment]
> Hi Rafael, I did some digging and it seems https://docs.zowe.org/zowe-docs-v2.12.x.pdf is a broken link. Interestingly, https://docs.zowe.org/zowe-docs.pdf points to the Zowe v2.12 docs. Perhaps that link always points to docs for the previous version of Zowe.
> 

@RafaelQRafael @Andrew-J-Metzger -- the zowe-docs.pdf link should point to the PDF for the latest Zowe release. Created a PR to update the PDF file to include the correct title.

Thank you for noticing!
