### ISSUE TITLE
Describe the steps to authorise a user to create the API ML Keyring

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#334]
## Is your request for enhancement related to a problem? Please describe.

The main install script runs `apiml_cm.sh` but this will fail if the installing user does not have enough authority.

## Describe the solution you'd like

We should set out the steps required for a user to obtain sufficient authority.  Note that the customer systems programmer might not have sufficient authority, even if they have `RACF SPECIAL`, so they may have to perform these steps before running `apiml_cm.sh`.  

To check the name of the ring you can issue `RACDCERT ID(IZUSVR) LISTRING(IZUKeyring.site)` where `IZUKeyring.site` is the name of the keyring as specified in 
the `/var/zosmf/configuration/servers/zosmfServer/bootstrap.properties` file for this keyword:
`izu.ssl.key.store.saf.keyring=IZUKeyring.site`
Note:  The user might need extra permission to issue the `RACDCERT ` command.
Note:  The `bootstrap.properties` file is protected so only IZUSVR can read and write it.  

To allow `apiml_cm.sh` to run, it should normally be sufficient to PERMIT CONTROL access for the user of IRR.DIGTCERT.LIST (needed for a SITE certificate) and UPDATE of IRR.DIGTCERT.LISTRING, but in some cases (for example if you have already created a certificate) you might have to PERMIT the user to have CONTROL access to IRR.DIGTCERT.** 

## Related doc pages

Related install problem issue:  API ML keyring certificate authorisation commands do not work #231
https://github.com/zowe/zowe-install-packaging/issues/231

**Comment by nannanli** [comment]
PR #331 for this issue has been updated and merged. Closing. Please reopen if any issue persists.
