### ISSUE TITLE
Inform about SDSF requirement for some installation steps

### ISSUE THREAD

**Issue by pablocarle** [zowe/docs-site#3363]
## Is your request for enhancement related to a problem? Please describe.
Related to https://github.com/zowe/zowe-install-packaging/issues/3704 and https://github.com/zowe/zowe-install-packaging/issues/3477

## Describe the solution you'd like
Identify and describe which of the automated steps of Zowe installation have a dependency on SDSF being available in the z/OS system.

**Comment by skurnevich** [comment]
Just to add more details, this is how the error may look on the customer side:
```
A zwe init certificate --update-config
...
IRX0043I Error running /Zowe/bin/utils/opercmd.rex, line 130: Routine not found
```
So we can document SDSF as a requirement in [Addressing z/OS requirements](https://docs.zowe.org/stable/user-guide/systemrequirements-zos) or in the [Configuring](https://docs.zowe.org/stable/user-guide/configuring-overview) section as it is related to `zwe` utility.

And we can document IRX0043I with opercmd.rex error in the troublesooting section as well
