### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/mvd-3270

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/docs-site#3386]
## Description
New page for [TN3270](https://github.com/zowe/docs-site/pull/3047) is missing in the menu.
The [page](https://docs.zowe.org/stable/user-guide/mvd-3270/) is accessible only via link or from search menu.

## Pages to Update
[docs.zowe.org/stable/user-guide](https://docs.zowe.org/stable/user-guide/mvd-using)

## Screenshots
![image](https://github.com/zowe/docs-site/assets/66114686/bc44d07b-ca4c-40e6-a20c-e68083f8d702)

## Expected behavior
![image](https://github.com/zowe/docs-site/assets/66114686/f27acb2f-0838-43d6-82c0-bf398a2b3290)

**Comment by janan07** [comment]
See PR: https://github.com/zowe/docs-site/pull/3611
