### ISSUE TITLE
vt terminal app - should close app/connection when exiting

### ISSUE THREAD

**Issue by neils-ibm** [zowe/docs-site#340]
When I am finished with my ssh session, after I enter exit, the session stays there, the window doesn't close or stop the connection like it does with the TN3270 terminal app.  It would be nice if we could be consistent.  Thanks.

**Comment by neils-ibm** [comment]
![image](https://user-images.githubusercontent.com/43242570/51631063-b4d4d000-1f19-11e9-8c55-88ee1ed20b9e.png)

**Comment by neils-ibm** [comment]
![image](https://user-images.githubusercontent.com/43242570/51631246-2f055480-1f1a-11e9-88d4-2d651e90d72f.png)

**Comment by stevenhorsman** [comment]
Migrated to: https://github.com/zowe/vt-ng2/issues/11
