### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/api-mediation/api-gateway-configuration

### ISSUE THREAD

**Issue by juergen-holtz** [zowe/docs-site#3427]
## Description

"Page not found" appears when linking from [here](https://docs.zowe.org/stable/getting-started/zowe-security-authentication)

## Pages to Update

https://docs.zowe.org/stable/getting-started/zowe-security-authentication

## Screenshots

n/a

## Expected behavior

Expect correct link in source html page.

## Additional context

n/a

**Comment by janan07** [comment]
Thank you for bring this to our attention. The link has been fixed. Please clear your cache and reload the page for the link to be functional.
