### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/api-mediation/api-mediation-personal-access-token

### ISSUE THREAD

**Issue by juergen-holtz** [zowe/docs-site#3428]
## Description

Page not found when navigating to this page from [here](https://docs.zowe.org/stable/getting-started/zowe-security-authentication)

## Pages to Update

Link "the Personal Access Token documentation" on page https://docs.zowe.org/stable/getting-started/zowe-security-authentication

## Screenshots

n/a

## Expected behavior

Expect corrected link on that page.

## Additional context

n/a

**Comment by janan07** [comment]
Thank you for bring this to our attention. The link has been fixed. Please clear your cache and reload the page for the link to be functional.
