### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/extend/extend-apiml/api-mediation-caching-service.md

### ISSUE THREAD

**Issue by juergen-holtz** [zowe/docs-site#3429]
## Description

Page not found appears when linking from [here](https://docs.zowe.org/stable/getting-started/zowe-architecture#caching-service)

## Pages to Update

Link "Caching service documentation" needs to be corrected to point to the caching service documentation

## Screenshots

n/a

## Expected behavior

Expect to navigate to the caching service documentation.

## Additional context

n/a

**Comment by janan07** [comment]
Thank you for bring this to our attention. The link has been fixed. Please clear your cache and reload the page for the link to be functional.
