### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/api-mediation/using-api-mediation-layer

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3450]
## Description

[Personal Access Tokens](https://docs.zowe.org/stable/user-guide/api-mediation/api-mediation-personal-access-token.md) leads to a "Page Not Found" link

## Pages to Update

https://docs.zowe.org/stable/user-guide/api-mediation/using-api-mediation-layer

**Comment by janan07** [comment]
Hi Dan, we have a new structure for using API ML beginning with the current version (v2.14). The sidebar has not been changed in the previous versions as this would cause various links to break as various topics have been moved. I'll discuss with Jakub if it makes sense to duplicate the sidebar for previous v2 versions. Until then, please see the current version 2.14.

**Comment by janan07** [comment]
All of the links on this page have been updated with the current structure. Please use the current release of the documentation. Currently, this version is v2.14.

 https://docs.zowe.org/stable/user-guide/api-mediation/using-api-mediation-layer
