### ISSUE TITLE
Preferred way of spelling of “key ring” or “keyring”

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#346]
I have a question about the preffered way of spelling words: “keystore” and “keyring”. In the most of the z/OS documentation, I see “key ring” and “keystore”. In Zowe, I see “keyring” and “keystore”. 
@JirkaAichler

**Comment by JamesBauman** [comment]
one word...  keyring/keystore

Neither term is listed in the official CA word list, so we have to default to what's accepted in the world of computing.  one word for both terms is most common.  This also applies to truststore.

**Comment by JamesBauman** [comment]
@plavjanik  and @nannanl

Does the response answer your question?  Can we close the issue?

thx,
jb

**Comment by plavjanik** [comment]
Yes, I am closing it
