### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/cli-using-integrating-apiml

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/docs-site#3492]
## Description
It would be helpful to add instructions for Zowe CLI users to authenticate to the APIML using client certificates.

Currently, the page does not mention certificates.

## Pages to Update
docs.zowe.org/stable/user-guide/cli-using-integrating-apiml

**Comment by balhar-jakub** [comment]
Do you need our help on this one?
