### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/configure-zos-system/

### ISSUE THREAD

**Issue by ghannington-Rocket** [zowe/docs-site#3521]
## Description

The page shows garbled markup (`:::notes` and `:::`):

> :::notesNotes

> in Zowe. :::

## Pages to Update

https://docs.zowe.org/stable/user-guide/configure-zos-system/

**Comment by anaxceron** [comment]
@ghannington-Rocket -- thanks for bringing this to our attention. Fixing with [PR 3556](https://github.com/zowe/docs-site/pull/3556).
