### ISSUE TITLE
JES Commands - Issue with docs.zowe.org/stable/user-guide/start-zowe-zos/

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3529]
## Description

There are 2 references in this doc that mention "JES commands".  JES commands typically start with `$` so I think we would refer to commands here as ["MVS system commands"](https://www.ibm.com/docs/en/zos/2.4.0?topic=commands-mvs-system-reference)

**Comment by janan07** [comment]
closed with https://github.com/zowe/docs-site/pull/3609
