### ISSUE TITLE
Personal Access Tokens Documentation Missing in 2.15

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3558]
## Description

Personal access tokens page does not appear to exist in the latest doc set.  

## Pages to Update

https://docs.zowe.org/v2.5.x/user-guide/api-mediation/api-mediation-personal-access-token/

## Additional context

also reported by @boris-bc

**Comment by janan07** [comment]
Fixed with https://github.com/zowe/docs-site/pull/3561
