### ISSUE TITLE
https://docs.zowe.org/stable/getting-started/zowe-security-authentication/#authentication-with-personal-access-token-pat 

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/docs-site#3562]
## Description
There are still 404 with these pages. 

- https://docs.zowe.org/stable/getting-started/user-guide/api-mediation/configuration-personal-access-token
- https://docs.zowe.org/stable/getting-started/user-guide/api-mediation/authenticating-with-personal-access-token

## Pages to Update
https://docs.zowe.org/stable/getting-started/zowe-security-authentication/#authentication-with-personal-access-token-pat

**Comment by janan07** [comment]
Addressed with https://github.com/zowe/docs-site/pull/3565
