### ISSUE TITLE
Missing imperative.ts file

### ISSUE THREAD

**Issue by rkeahey** [zowe/docs-site#3582]
URL: https://docs.zowe.org/v2.13.x/extend/extend-cli/cli-developing-a-plugin

In the step "**Adjusting Imperative CLI Framework configuration**" the instructions indicate to

"Change the src/imperative.ts file to contain the following configurations:"

However, there is no imperative.ts file in the src directory for the zip archive. Therefore one must be created from scratch.

**Comment by rkeahey** [comment]
Thanks!

I'm not sure how to report this (could be a problem on my end...), but when I follow the instructions as written I get an error when doing "zowe plugins install files-util" 

The message is:
Command Error:
Install Failed
Error Details:
Imperative requires configuration before it can be used. No configuration was passed to init(), and no configuration was present in package.json. Please provide configuration.

Have followed the steps several times with the same result. 

Sorry if I'm reporting this at the wrong place. I'm very new to the ZOWE/CLI environment. Any guidance would be appreciated!

**Comment by zFernand0** [comment]
Hey @rkeahey,

The command you want to use is `zowe plugins install <path/to/zowe-tutorial/files-util>` since you are developing a plugin which has not been published yet. Since you are likely inside (or `cd` into) the `files-util` directory on your terminal, the command may just be `zowe plugins install .` which indicates that you want to install from the current working directory.

There may be other small issues you might be running into, even after running the correct CLI command. We will be updating the steps to make sure the process is smoother going forward 😋

**Comment by rkeahey** [comment]
Thanks! I did all the steps you outlined above and then ran npm run build, then zowe plugins install .

I god a couple of "CmdErrors" shown in the following log snippet. Don't know if they will be useful for you, but thought I would pass them on. 

C:\Users\rhkea\Documents\QuickRef_Data\zowe-tutorial\files-util>zowe plugins install .
Plug-ins within the Imperative CLI Framework can legitimately gain
control of the zowe CLI application during the execution of every command.
Install 3rd party plug-ins at your own risk.

Registry = https://registry.npmjs.org/

_______________________________________________________________
[2024/04/03 14:15:44.784] [WARN] [LifeCycleForSample.js:63] Something weird happened in the sample plugin's postInstall function. However, things should still work ok.
Installed plugin name = '@zowe/files-util'

_____ Validation results for plugin '@zowe/files-util' _____

*** CmdError: The plugin named 'compare-files' attempted to add a group of command with the alias 'zcsp', which conflicts with another alias of the same name for group 'zowe-cli-sample'.     

*** CmdError: The plugin's profile type = 'sample' already exists within existing profiles.

This plugin has command errors. No plugin commands will be available.

**Comment by rkeahey** [comment]
If it helps, I ran the Developing for Zowe CLI steps in sequence (https://docs.zowe.org/v2.13.x/extend/extend-cli/cli-devtutorials/). I think this is causing some of the conflicts shown above. I changed the pluginDef: pluginAliases: to "zscp2" in pluginDef.ts and the first error went away. I changed the profiles:type to "sample2" in pluginDef.ts and the second error went away. I think the issue is that the samples are all using the same sample-plugin-master source files. 

After I made these changes and ran npm run build again and then zowe plugins install . again, the plugin worked!

**Comment by zFernand0** [comment]
Yeah, it's likely that you already have the sample plugin installed and it already reserved those profile types and aliases 😅 

You could uninstall the sample plug-in if you truly want to use the original aliases with your `files-util` package 😁 

Either way, I'm glad to hear you were able to get the plug-in working. 🎉 

And thanks for sharing the snippet, we might be able to include it as part of the Zowe Docs once we update it 😋 

We can close this issue after updating the steps to mention the few things that helped you get it to work. 🥳 

Cheers! 🥂

**Comment by anaxceron** [comment]
@rkeahey -- I'm updating the extending content in [PR 3606](https://github.com/zowe/docs-site/pull/3606). Please review and let me know if we're missing anything.
