### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/api-mediation/mvd-configuration/

### ISSUE THREAD

**Issue by skurnevich** [zowe/docs-site#3597]
[Using multi-factor authentication (MFA)](https://docs.zowe.org/stable/user-guide/api-mediation/using-multi-factor-authentication/) page -> "[Multi-factor authentication configuration](https://docs.zowe.org/stable/user-guide/api-mediation/mvd-configuration/#multi-factor-authentication-configuration) in Configuring Zowe Application Framework." link is broken, it contains extra "/api-mediation" part that should be removed

**Comment by janan07** [comment]
Fixed with https://github.com/zowe/docs-site/pull/3599
