### ISSUE TITLE
Include modify commands in the install guide for ZWESIS01

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#366]
## Is your request for enhancement related to a problem? Please describe.
Modify commands for the ZWESIS01 should be included for the commands to update.  Currently we only have the commands for install

## Describe the solution you'd like
A new section of the docs for modify that covers the steps when a user gets a new version of Zowe and they need to do modifies.  This was suggested by @ifakhrutdinov so we should have an issue to track/remind us.

**Comment by nannanli** [comment]
Assigning to @chentingcathy to handle the doc updates. 

This is an upgrade and migration topic. Please consider the following information:
- what version the user is upgrading or migrating from. Currently should be from 0.9.x to 1.0.x, right? How about the move from one patch level to another patch level of the same release, like from 1.0.0 to 1.0.1? 
- how to verify the current installed Zowe level? 
- what modifications are needed for the upgrade and migration? 
- how to verify that the upgrade is installed and working correctly.
- any troubleshooting tips?

@Joe-Winchester Hi Joe, as we move toward 1.0.1, do you think we can start working on this topic now?

**Comment by Joe-Winchester** [comment]
@ifakhrutdinov - with the new ZWESIS01 load module in 1.0.1 do we need to get the documentation in for the modify commands for the X-Memory server into this release ?  I am thinking we do but I wanted to check with you before making an update and creating a PR.  Tks

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester I think that'd be great to add them, but it's not high priority if there are more important tasks.

Do you have those commands? We didn't add any new ones in 1.0.1, so whatever I sent before should still be relevant.

**Comment by Joe-Winchester** [comment]
@ifakhrutdinov - I think I have the commands.  If I can't find them I'll reach out to you but I agree that this is low priority until it becomes necessary for a user to do a modify.
