### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/api-mediation/configuration-extender-passtickets/

### ISSUE THREAD

**Issue by codezfire** [zowe/docs-site#3665]
## Description

The setup process for configuring Zowe to utilize PassTickets requires thorough documentation.

## Pages to Update
https://docs.zowe.org/stable/user-guide/api-mediation/configuration-extender-passtickets/

## Expected behaviour
Additionally, the procedure steps should incorporate these commands and procedure.

1. Activate the PTKTDATA class, which encompasses all profiles containing PassTicket information, by executing the subsequent command:
     SETROPTS CLASSACT(PTKTDATA) RACLIST(PTKTDATA) 

2. Specify the application name requiring access through PassTicket for the ZOWE server with the following commands:
    RDEFINE APPL <applname> UACC(NONE) 
    SETROPTS CLASSACT(APPL) 
    SETROPTS GENERIC(PTKTDATA) 
Here, replace <applname> with a 1- to 8-character name designated for the application, usually provided by the site security administrator.

3. Define a profile for the application by inputting:

    RDEFINE PTKTDATA <applname>SSIGNON(<key_description>(<key>)) 
    This links a secured sign-on application key with the application. 
    Replace <applname> with the application name defined previously.

4. Grant a ZOWE user ID access to the application via:

    PERMIT APPLNAME CLASS(APPL) ID(<userid>) ACCESS(READ) 
    Replace <userid> with the permitted user ID.

5. Enable the Zowe STC ID to utilize the PassTicket generation service through:

    RDEFINE PTKTDATA IRRPTAUTH.<applname>.* UACC(NONE) 
    PERMIT IRRPTAUTH.<applname>.* CLASS(PTKTDATA) - ID(<Zowe_STC_User>) ACCESS(UPDATE) 
    Ensure to replace <applname> with the application name and <Zowe_STC_User> with the Zowe STC user ID.

6. Refresh the PTKTDATA class to activate the modifications by executing:

    SETROPTS RACLIST(APPL) REFRESH 
    SETROPTS RACLIST(PTKTDATA) REFRESH

7. Validate 

    RLIST APPL APPLNAME ALL
    RLIST PTKTDATA IRRPTAUTH.APPLNAME.* ALL

**Comment by anaxceron** [comment]
@balhar-jakub @janan07 -- please review

**Comment by janan07** [comment]
Closed with https://github.com/zowe/docs-site/pull/3673
