### ISSUE TITLE
Explicitly state infinispan as a requirement for PATs

### ISSUE THREAD

**Issue by pablocarle** [zowe/docs-site#3707]
## Is your request for enhancement related to a problem? Please describe.
The docs should explain that in order to enable the Personal Access tokens support, `infinispan` is required as the storage solution for the Caching Service.

## Describe the solution you'd like
Include infinispan mode as a requirement for Caching Service to work with PATs
The article should also describe for troubleshooting what would happen if attempting to use PATs with another storage solution.

## Related doc pages
https://docs.zowe.org/stable/user-guide/configure-caching-service-ha/
https://docs.zowe.org/stable/user-guide/api-mediation/configuration-personal-access-token/
https://docs.zowe.org/stable/user-guide/api-mediation/authenticating-with-personal-access-token/

**Comment by janan07** [comment]
Closed with https://github.com/zowe/docs-site/pull/3727
