### ISSUE TITLE
Every page on every version has the same 'last updated' date

### ISSUE THREAD

**Issue by ijmitch** [zowe/docs-site#3712]
## Description
As per title I'm seeing every page of every version of the docs with "Last updated: 11/06/2024" - so what's the point of having that if they're all the same?

## Pages to Update
Every single page!

## Screenshots

![image](https://github.com/zowe/docs-site/assets/1266441/40713766-1550-4361-9ce4-b4852df74a8e)

![image](https://github.com/zowe/docs-site/assets/1266441/6bafb03b-3506-4937-9930-9d6e1531059d)

And the same 'Architecture' page from an older version:

![image](https://github.com/zowe/docs-site/assets/1266441/02e2ab3e-b1a9-4e28-ad33-9c4c1d488774)

**Comment by ijmitch** [comment]
I must admit I'd not spotted the day on all the pages was actually yesterday's date - ie the day when I created this issue. Checking today, it's still saying the same thing (so it's not like this gets fixed as "today's date"). Did something happen yesterday to make all the pages appear changed?

**Comment by balhar-jakub** [comment]
Yes, we were publishing the 1.28.7 release yesterday, which means that all the pages were touched, but not necessarily changed. 

I believe it's relevant bug to look into. Make sure that the last updated changes only for pages where content actually changed.

**Comment by ijmitch** [comment]
@balhar-jakub ah, OK - so at least it can be associated with an action.

So is this implemented via the [`showLastUpdateTime`](https://github.com/zowe/docs-site/blob/f95f04d88b7f726ad5f87f1db9196538e8ffb90e/docusaurus.config.js#L210) option? That should work off commit history - was there a mass commit somewhere?

**Comment by ijmitch** [comment]
You probably suffered this https://github.com/facebook/docusaurus/discussions/9734.

>The problem is that the default depth for the actions/checkout@v4 action is 1 (latest commit only), and in this case git log cannot retrieve the dates of previous commits; instead it returns the date of the latest commit (the only one cloned), for all files, and all documentation pages appear to be updated at the same time.

Which boils down to the build process not having enough/any commit history.

**Comment by balhar-jakub** [comment]
I am trying fix to this in the PR - https://github.com/zowe/docs-site/pull/3715

**Comment by balhar-jakub** [comment]
The fix was merged and deployed. As such I am closing the issue.
