### ISSUE TITLE
Document Zowe CLI proxy configuration

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/docs-site#3731]
## Is your request for enhancement related to a problem? Please describe.
Proxy support was recently added to Zowe CLI (V2). Users must set either the HTTPS_PROXY, https_proxy, HTTP_proxy, or http_proxy environment variables to the host and port of the proxy server through which they want to route communication.

## Describe the solution you'd like
Add a section to https://docs.zowe.org/stable/getting-started/zowe_faq#zowe-cli-faq for "How can I use Zowe CLI with a proxy?"

Then we would suggest that they would set either the HTTPS_PROXY (if https is supported by their proxy server) or HTTP_PROXY environment variable to the host address and port of the proxy server. We would also want to tell them that they can set the NO_PROXY environment variable to a comma-separated list of host addresses to allow connections to these hosts without going through the proxy.

## Related doc pages
https://docs.zowe.org/stable/getting-started/zowe_faq

**Comment by anaxceron** [comment]
Closed w/ [PR 3983](https://github.com/zowe/docs-site/pull/3983)
