### ISSUE TITLE
Page Not Found: docs.zowe.org/stable/user-guide/user-guide/install-zowe-smpe/

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/docs-site#3742]
## Description
https://docs.zowe.org/stable/user-guide/user-guide/install-zowe-smpe#dasd-storage-requirements

The link from https://docs.zowe.org/stable/user-guide/address-storage-requirements/#installing-with-smpe doesn't lead anywhere.

**Comment by janan07** [comment]
See PR: https://github.com/zowe/docs-site/pull/3841
