### ISSUE TITLE
zowe-check-prereqs.sh should be run AFTER zowe-install.yaml is configured

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#376]
## Description

If you run `zowe-check-prereqs.sh` before `zowe-install.yaml` is configured, it checks based on the contents of `zowe-install.yaml` as it is supplied in the PAX file.  The intent is to verify that the product will install correctly when configured as directed by the `zowe-install.yaml` file.

So you need to tell the user to edit `zowe-install.yaml` first.

## Pages to Update

In the `Prerequisites` section

**Comment by nannanli** [comment]
Thanks John. The sequence is updated. Closing. Feel free to reopen if any issue persists.
