### ISSUE TITLE
[User Feedback] Produce short videos of install

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#38]
Detailed procedures have been documented in docs site to instruct users how to install Zowe (on z/OS or on PC). Producing some short videos to demo the install process and insert into our docs site can enhance the user experience. 

Collaborate with development to collect input.

**Comment by Tbr00ksy** [comment]
I just spoke with John Mertic and he said that we can use the OMP Youtube channel (https://www.youtube.com/channel/UC-WTXQQtz2m5iTflJLK59aw)  for any instructional or marketing material. To have Zowe content added contact Mae at maemalynn@linuxfoundation.org
