### ISSUE TITLE
Guide for AT-TLS setup of servers

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#383]
## Is your request for enhancement related to a problem? Please describe.
We allude to being able to use AT-TLS to add an additional layer of security to servers such as ZSS, but to not explain how it can be done.

## Describe the solution you'd like
Document the purpose (additional layer of security, possibility to connect to ZSS directly from outside of mainframe for remote API usage)
Document the configuration steps for AT-TLS that will give a server on z/os TLS 1.2 HTTPS security such that it can be connected to via HTTPS with a web browser
Document where to find logs that would help with troubleshooting AT-TLS

## Related doc pages
Probably a new one is needed

## Additional context
General outline:

    Get PAGENT running against your desired TCPIP stack (They need to determine which TCPIP stack they desire)
        Determine whether it’s already running
        Determine where its config files are
    Write AT-TLS rule(s) for the server port(s) you care about (server auth, rather than mutual auth, is the preferred default of this guide)
    Bounce (or issue REFRESH modify command) against the PAGENT task
    Try an HTTPS request from browser
        Didn’t work?  Check logs (default output location is the console) to determine whether your rule fired, and if so, what the errors were. 

page 25 (43) here may serve as an example that we can keep in mind https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3sc278447/$file/azfi100_v1r3.pdf

**Comment by nannanli** [comment]
@jasonenglish2039 Hi Jason, can we close this issue now? Thanks!
