### ISSUE TITLE
Clarify the use of the FACILITY class or the RDATALIB class when accessing the private key

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#384]
## Is your request for enhancement related to a problem? Please describe.
User reported problem on Slack: 
- I had both RDATALIB and IRR.DIGTCERT.LISTRING, but did not define any access profile in class RDATALIB. 
- login to https://host:7544/ui/v1/apicatalog kept failing until i was able to run apiml_cm.sh by defining the new RDATALIB RACF profiles. 
- Looks like there is a change in zowe 1.0.0 in that it no longer checks RACF profile IRR.DIGTCERT.LISTRING CL(FACILITY)  to access the private key in the KEYRING ! You must define and use the newer RDATALIB facility class.

## Describe the solution you'd like
**The doc should be updated to add the following warning:** 

To access the private key belonging to SITE or CERTAUTH in a keyring, you can use either the FACILITY class or the RDATALIB class.

A. using the FACILITY class, you need:

1) READ on IRR.DIGTCERT.LISTRING, and
2) CONTROL on IRR.DIGTCERT.GENCERT

B. using the RDATALIB class, you need:
CONTROL on `<keyring owner>.<ring name>.LST`

If you have both FACILITY and  RDATALIB active, the access check will use the RDATALIB class. If you don't have access to that specific profile, access is denied. It will not fall back to FACILITY class to check even it has set up correctly.

## Related doc pages
- https://zowe.github.io/docs-site/latest/extend/extend-apiml/api-mediation-security.html#zowe-runtime-on-z-os
- Aso mention the change in release notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-0-0-february-2019

## Additional context
This is the complete conversation on Slack channel: https://openmainframeproject.slack.com/archives/CC08782AG/p1550153076021300

**Comment by janan07** [comment]
Additional resource access information is now included within the section 'Add a service with an existing certificate to API ML on z/OS'. 
https://github.com/zowe/docs-site/blob/docs-staging/docs/extend/extend-apiml/api-mediation-security.md
