### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/sdks-using

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3851]
## Description

SDKs should be referred to consistently by the same names; however we have inconsistent [naming](https://docs.zowe.org/stable/user-guide/sdks-using):
* [Zowe Client Python SDK](https://zowe-client-python-sdk.readthedocs.io/en/latest/)
* Zowe Python Client SDK

**Comment by janan07** [comment]
Closed with PR https://github.com/zowe/docs-site/pull/3886
