### ISSUE TITLE
Users of z/OS V2R5 and later no longer need a ZOWE definition in the RACF Class Descriptor Table

### ISSUE THREAD

**Issue by Andrew-J-Metzger** [zowe/docs-site#3868]
## Description

According to the RACF support team, ZOWE is now in the static CDT starting in z/OS 2.5.. Perhaps there should be a note stating that users on z/OS V2R5 and later do not have to add the ZOWE class (or can remove it if previously defined) after all of the systems that share the RACF database are upgraded to z/OS V2R5 or later.

## Pages to Update

<https://docs.zowe.org/stable/user-guide/mvd-configuration/#defining-the-racf-zowe-class>

## Screenshots

![Screenshot, placement of the proposed note](https://github.com/user-attachments/assets/c214da39-c406-4f13-b19a-23e7556201f8)

## Expected behavior

Add a note to the "[Defining the RACF ZOWE class](https://docs.zowe.org/stable/user-guide/mvd-configuration/#defining-the-racf-zowe-class)" section, perhaps just above the steps. 

Suggested text:

> [!NOTE]
> Starting with z/OS V2R5, the ZOWE class has been predefined to RACF. If you have previously defined the ZOWE class manually, this class can be deleted after all of the systems that share the RACF database are upgraded to z/OS V2R5.

## Additional context

IBM's RACF team has published an APAR describing the CDT change and necessary actions: [zOS V2R5 Upgrade Workflow from zOS V2R4 - OA64212](https://www.ibm.com/docs/en/zos/2.5.0?topic=SSLTBW_2.5.0/com.ibm.zos.v2r5.e0zm100/Export_zOS_V2R4_to_V2R5_Upgrade_Workflow.htm)

**Comment by lparadkar-rocket** [comment]
Hi @Andrew-J-Metzger, based on the information provided in the ticket. We have updated the doc-site. Here is a screenshot for the same. 
<img width="957" alt="RACF_Zowe_Class_Doc Change" src="https://github.com/user-attachments/assets/55dccff8-50cd-4ecc-b94c-5ba27f9c8ee6">

Please let me know if I can close the issue now.

**Comment by Andrew-J-Metzger** [comment]
Hi @lparadkar-rocket, that looks good to me! Please close this; thanks for your review.
