### ISSUE TITLE
Wrong load module name in the Zowe architecture diagram

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/docs-site#388]
## Description

The diagram uses ZISSRV01 as the cross-memory load module name, whereas the correct one is ZWESIS01.

## Pages to Update

The bottom-right corner
https://github.com/zowe/docs-site/blob/master/docs/getting-started/zowe-architecture.md

**Comment by nannanli** [comment]
Thanks for reporting the issue! It is fixed now. Closing.
