### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/zwe-init-subcommand-overview/

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3880]
## Description

On this page
https://docs.zowe.org/stable/user-guide/zwe-init-subcommand-overview/

The "[Next steps](https://docs.zowe.org/stable/user-guide/zwe-init-subcommand-overview/#next-steps)" has a link that leads to a "Page not found"

**Comment by janan07** [comment]
The page loads properly.
