### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/configuring-security/

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3881]
## Description

On this page: https://docs.zowe.org/stable/user-guide/configuring-security/

Follow the "[Next step](https://docs.zowe.org/stable/user-guide/configuring-security/#next-step)" then on the target page, follow the "Next steps" which leads back to https://docs.zowe.org/stable/user-guide/configuring-security/ (cyclical links of "Next step(s)"

**Comment by janan07** [comment]
This issue has been resolved. Closed with https://github.com/zowe/docs-site/pull/3882
