### ISSUE TITLE
v2.18.0 missing

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#3907]
With the new v3.0 documentation being live at docs.zowe.org, I see that v3.0 and v2.17.0 exist, but v2.18.0 does not 
<img width="143" alt="image" src="https://github.com/user-attachments/assets/1c5fc469-ed60-46e4-9dae-0bbe353e2e0b">

**Comment by janan07** [comment]
Closed with https://github.com/zowe/docs-site/pull/3911
