### ISSUE TITLE
Add Zowe Overview PDF

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/docs-site#391]
## Is your request for enhancement related to a problem? Please describe.
Can we please add the Zowe Overview PPT [here](https://ibm.box.com/s/wwju07uvtwwhgf77lcalrsosy6oa2gnj) to the Zowe doc's site?

## Describe the solution you'd like
Can we add a table at the bottom on the homepage for slides? 

## Related doc pages
Home page

## Additional context
We want to provide interested Zowians a PPT to present to their management to help them make the case for their involvement in the community.

**Comment by nannanli** [comment]
Thanks Cathy, the Overview PDF is added now. See 
- Homepage: https://github.com/zowe/docs-site/tree/docs-staging/docs
- The PDF file: https://github.com/zowe/docs-site/blob/docs-staging/docs/.vuepress/public/Zowe_Overview.pdf

When 1.0.1 is published, the link will be live on the homepage. At this point, @Tbr00ksy can check the descriptions for the deck and let @chentingcathy know if any comments. Thanks!

**Comment by Tbr00ksy** [comment]
PDF description looks good. Thank you @chentingcathy.
