### ISSUE TITLE
Tech-Debt: Clean up old branches

### ISSUE THREAD

**Issue by zFernand0** [zowe/docs-site#3927]
zowe-robot created branches based on git commit hashes.

I believe that's done via automation.
Ideally it should clean up after itself : )

![image](https://github.com/user-attachments/assets/3351a06c-79b1-46de-b5fa-ea4f4df0d13f)

**Comment by balhar-jakub** [comment]
The branches are cleansed. 

I will look into the automation

**Comment by zFernand0** [comment]
is it fair to say that branches without any commits ahead pf the default branch can also be deleted?

<img width="410" alt="image" src="https://github.com/user-attachments/assets/c2b06232-ed52-4657-b9a3-8f1ba11211ff">

**Comment by balhar-jakub** [comment]
I am fine with that.

**Comment by janan07** [comment]
I would agree. I can't see why we should keep them.

**Comment by zFernand0** [comment]
I've removed all (30) non protected branches which didn't have newer commits.
