### ISSUE TITLE
Documentation on enabling and disabling Zowe components is confusing

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/docs-site#3932]
Putting aside that it's interesting that we have a page https://docs.zowe.org/stable/user-guide/api-mediation/configuration-api-mediation-standalone all about enabling only one part of Zowe, and no such pages for the other parts of Zowe, if my goal were to enable only APIML, I don't think this page has enough info to accomplish the task.

The page just says "Find or add the property components.*.enabled and set this property to false for all components that should not be started."

It doesnt really tell you what components those would be.

Then, on the page right under it on the sidebar, pretty much the same thing is said in a different way.

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/6454881d-2942-4be0-a7e1-2ad1a3678345">

What if we had just one page on the subject, and not APIML specific, but rather one that details all the parts of zowe, categorized, and explains how to enable just what you need?

# Limiting started Zowe services

Zowe's server installation contains groups of components that are useful to run together, but often you do not need to enable all parts of Zowe.
You can save system resources by disabling the parts of Zowe that you do not use.

Below is a list of the components of Zowe, their purpose, and their name within the Zowe YAML file.
To enable or disable each component, simply edit `components.<component-name>.enabled` to `true` or `false` in the YAML.
You must restart Zowe for the changes to take effect.

| Category | Component | Purpose |
|------|------|------|
| API Mediation Layer | api-catalog | Used to view API swagger / openAPI specifications for registered API services of the API Mediation Layer.
| API Mediation Layer | discovery | This server is used to register API services and track the health of them for use in the API Mediation Layer.
| API Mediation Layer | gateway | The gateway unifies all the services of Zowe under one proxied server for improved security, management, and high availability.
| API Mediation Layer | caching-service | The caching service is used to share state between different Zowe instances in a high availability topology.
| API Mediation Layer | zaas | ZAAS provides authentication services used by the API Mediation Layer.
| App Framework | app-server | The App server powers the Zowe Desktop accessible via web browsers.
| App Framework | zss | Z Secure Services (ZSS) provides REST API services for file, dataset, and other z/OS content. Its APIs are used by apps in the Desktop, such as the the File Editor.

**Comment by balhar-jakub** [comment]
Given how the API ML page looks like, it seems like some kind of strange relict. We probably should remove it. 

As for the enabling and disabling of the actual components. I would much rather have API Mediation Layer as one component from the point of view of enabling and disabling at least for V4.
