### ISSUE TITLE
Add note on Powershell execution policies to docs.zowe.org/stable/troubleshoot/cli/troubleshoot-cli

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/docs-site#3934]
## Description
Powershell users on Windows can encounter an error when they try to run Zowe CLI with certain execution policies in place.

An example of the error message:
```
PS C:\> zowe
zowe : File C:\Users\user\AppData\Roaming\npm\zowe.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ zowe
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

To resolve this issue, users will need to either:
1. Change a setting in "Developer Settings" in Windows 10 settings (I am not sure where they can find this setting in other versions of Windows) to enable running local scripts without signing:
![image](https://github.com/user-attachments/assets/9b0d84d6-474b-4ce0-9b85-7b18c89538c9)

2. **Or**, they can run Powershell as an administrator and use the `Set-ExecutionPolicy` command to change the execution policy to a less-restrictive setting, for example: `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`.

## Pages to Update
https://docs.zowe.org/stable/troubleshoot/cli/troubleshoot-cli

**Comment by 1000TurquoisePogs** [comment]
I believe this is what it looks like for windows 11
![image](https://github.com/user-attachments/assets/96573cfc-feb5-4acc-a585-5fe5168ac4fb)
