### ISSUE TITLE
Document ACF/2 and TSS steps for BPX.SERVER and BPX.DEAMON permissions for ZWESIS01 manual setup

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#401]
## Description
1.0.1 introduced the need for the user running ZWESIS01 (by default IZUSVR) to have UPDATE ability for the BPX.SERVER and BPX.DAEMON FACILITY class, so that the program can run commands on behalf of different users (also known as impersonation).  This is described in the "manual setup for the APF server" in step 7,  "Security Environment Switching"

The steps are described for RACF, and don't include ACF/2 and TSS.  

## Pages to Update
install-zos.md  section 7 "Security Environment Switching"

**Comment by nannanli** [comment]
Hi Mark @MarkAckert , I'm wondering if you know the steps to grant BPX.SERVER and BPX.DEAMON permissions for ACF/2 and TSS users that's mentioned in this issue. Could you advise? The section that talks about this for RACF users in the doc is https://zowe.github.io/docs-site/latest/user-guide/install-zos.html#manually-installing-the-zowe-cross-memory-server. 

Providing links to the ACF/2 and TSS documentation site is one option that is being considered. However, if any concrete commands or steps can be provided like what's done for RACF, that would be great. Thanks!

**Comment by Joe-Winchester** [comment]
@ifakhrutdinov and @MarkAckert  - If we need anyone else to help here I met Julie Bergh from Rocket software at Share Phoenix and who is a WW Lead Security Advisor and has a lot of ACF/@ and TSS experience.  I also met Sai from Broadcomm at Share and she volunteered help if we need to reach outisde and "phone a friend" ?  Let me know and I can make the introduction/connection

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester thank you.

@MarkAckert, I think someone from Broadcom has already installed the cross-memory server, would that be possible to share the right ACF2/TSS commands?

**Comment by MarkAckert** [comment]
I will work on a PR to add TSS/ACF2 commands. I suggest we also alter the documentation flow slightly. Right now the first thing users see are security commands to create the BPX facilities and grant UPDATE access, and they should probably first check if these facilities/permissions exist.

Sample Modified Flow:
<intro_bpx_description>:

To check if you have defined BPX.SERVER / BPX.DAEMON and IZUSVR (or STC user) has access, issue:
RACF:
TSS:
ACF2:

If the resources are not defined / user does not have access, follow these instructions to configure the facilities:
RACF:...
...

**Comment by nannanli** [comment]
The documentation has been updated by Mark using the proposed flow. See https://zowe.github.io/docs-site/latest/user-guide/install-zos.html#manually-installing-the-zowe-cross-memory-server. 

Closing this issue now and feel free to reopen if any issue persists.
