### ISSUE TITLE
Remove Troubleshooting (word) from the T/S menu and TOC

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#403]
The word Troubleshooting is repeated many times. 

We can remove it from the TOC:
![image](https://user-images.githubusercontent.com/36677566/53588739-a81c4b00-3b5b-11e9-81bd-031d271223d6.png)

We can remove it from the menu:
![image](https://user-images.githubusercontent.com/36677566/53588695-9175f400-3b5b-11e9-92f5-af7e9bf5e7c9.png)

Should be a quick update,  however, it can wait until the next refresh.

**Comment by JamesBauman** [comment]
FYI @BrandonJenkins14 @nannanli

**Comment by nannanli** [comment]
Great suggestion! As this is a quick fix, I just submitted the updates directly to the working branch. Thanks Jim!
