### ISSUE TITLE
gatewayHttpsPort still used in latest instruction

### ISSUE THREAD

**Issue by rjmaomao** [zowe/docs-site#407]
## Description

Some instruction not very clear
## Pages to Update

In verification section after installation. The doc said the basePort is set gatewayHttpsPort. But in current yaml file, this port was deleted already.

https://zowe.github.io/docs-site/latest/user-guide/install-zos.html#verifying-api-mediation-installation
=============paste from doc website====================
Verifying API Mediation installation
Use your preferred REST API client to review the value of the status variable of the API Catalog service that is routed through the API Gateway using the following URL:

https://hostName:basePort/api/v1/apicatalog/application/state
The hostName is set during install, and basePort is set as the gatewayHttpsPort parameter.

**Comment by nannanli** [comment]
Thanks for opening this issue! @janan07  This is related to APIML. Can you take a look at this issue and update doc? Thank you.

**Comment by janan07** [comment]
This doc fix is contained in PR #439. Brandon or Jim will review and merge.
