### ISSUE TITLE
Clarify juncture of BPX access

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#411]
Rectify the wording "During manual installation of the Zowe Cross Memory Server, the user ID IZUSVR must have UPDATE access to the BPX.SERVER and BPX.DAEMON FACILITY classes"

## Description

It's not about manual versus automatic installation, nor is it about access during install.  The stated access is required for *product operation*.  
## Expected behavior

Suggested alternative wording:
"During product operation of the Zowe Cross Memory Server (which is new with this release), the z/OSMF user ID IZUSVR or its equivalent must have UPDATE access to the BPX.SERVER and BPX.DAEMON FACILITY classes.  The install script will do this automatically if the installing user has enough authority, or provide the commands to be issued manually if not.  "

**Comment by John-A-Davies** [comment]
This relates to
 docs-site/docs/getting-started/summaryofchanges.md

**Comment by JamesBauman** [comment]
I'm not sure who owns this content...  @nannanli and @jackjia-ibm

**Comment by nannanli** [comment]
The owner of the content is me. Assigning to myself. It's part of the 1.0.1 release notes so should be fixed asap.

**Comment by nannanli** [comment]
Fixed. See https://github.com/zowe/docs-site/blob/docs-staging/docs/getting-started/summaryofchanges.md#whats-new-in-zowe-installation-on-zos.
