### ISSUE TITLE
Node.js installation instructions

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#426]
## Is your request for enhancement related to a problem? Please describe.

Several system programmers reported that they had to install Rocket tools. The current instructions point to https://developer.ibm.com/node/sdk/ztp/ which says that Make, Python, and Perl should be installed. They are optional but the Node.js can be confusing for people who install Zowe. The note in the Zowe documentation is after the link to Node.js instructions.

## Describe the solution you'd like

1. Clear instructions how to install Node.js without dependencies as a part of the Zowe installation documentation
2. or explaining that Make, Python, and Perl are not necessary before the link to Node.js installation

## Related doc pages

- https://zowe.github.io/docs-site/latest/contributing.html
- https://developer.ibm.com/node/sdk/ztp/

**Comment by nannanli** [comment]
Thanks Petr for the feedback! I agree we need to enhance this section. The first solution you proposed has long been considered. In that way, users don't have to read the Node.js doc and remember which they need to install and which not. Will work on this and update this issue.

**Comment by nannanli** [comment]
Hi Petr, @plavjanik 

The Node.js install instructions have been updated. Instead of referring users to the Node.js download site to read the instructions, now it consolidates the required Node.js install steps for Zowe on the Zowe doc site. Unnecessary steps like Make, Python, and Perl have been removed. See the draft here https://github.com/zowe/docs-site/blob/zosmf-updates/docs/user-guide/install-nodejs-zos.md. 

There is also a consolidated list of sysreqs here https://github.com/zowe/docs-site/blob/zosmf-updates/docs/user-guide/systemrequirements.md which points to the above topic. Wondering if you could take a look at the updates. 

@armstro @Joe-Winchester  Hi Joe, Bruce, this is a doc enhancement to the Node.js install on z/OS host. Could you let me know if you have any comments? 

Thanks all!

**Comment by plavjanik** [comment]
Hello Ashley,

this looks really great! 

There is a thing that I have realized now. Some z/OS systems do not have the `env` command at `/usr/bin/env` where Linux systems have it and where Node.js expects it. It is causing a failure when you need to start `npm` with the error message: `npm 2: FSUM7332 syntax error: got (), expecting Word`. More details and troubleshooting instructions are at https://www.ibm.com/support/knowledgecenter/en/SSTRRS_6.0.0/com.ibm.nodejs.zos.v6.doc/env.htm. `npm` is not required to run Zowe but https://github.com/zowe/docs-site/blob/zosmf-updates/docs/user-guide/install-nodejs-zos.md mentions it. 

When you type `node`, it starts Node.js in interactive mode and users who are not familiar with Node.js or z/OS UNIX can have troubles with terminating it. The verification can be done by issuing `node --version` will just display the version `v6.14.4` and quit.

Thank you!

**Comment by Joe-Winchester** [comment]
@nannanli - This is very much improved so thank you for doing the rewrite.  

I agree with Petr that in the section 4.

![image](https://user-images.githubusercontent.com/28100302/54748992-1d16f980-4bcb-11e9-928a-27a3d1c30808.png)

We should not ask users to run npm.  We should just ask them to run ```node --version``` and verify that the version number is returned.  

I recall from Bruce Armstrong that we may need to tell users about getting node from shop z but I'll e-mail him separately to check up on this.  

Thanks again for making the update.

**Comment by nannanli** [comment]
Thank you @plavjanik @joe for the comments! The doc has been updated to remove the description about running npm and added how to use the node command `node --version` to verify the install. See the latst file here: https://github.com/zowe/docs-site/blob/zosmf-updates/docs/user-guide/install-nodejs-zos.md. This will be published when 1.0.2 is released. 

I know Bruce has some incoming updates about the location to download Node.js. That would be tracked in another issue #253 . If you're ok with the updates, Petr could you please close this issue? Thanks!

**Comment by plavjanik** [comment]
I am ok and I will close the issue. Thank you!
