### ISSUE TITLE
CLI plug-in command error

### ISSUE THREAD

**Issue by PlutoZhang** [zowe/docs-site#427]
## Description

In Installing plug-ins section, the command examples marked in the following screenshot might be `zowe plugins install pluginName@^1.0.0`
`zowe plugins install plugin1 plugin2 plugin3`

## Pages to Update

https://zowe.github.io/docs-site/latest/user-guide/cli-installplugins.html#meeting-the-prerequisites
## Screenshots

![Snip20190318_5](https://user-images.githubusercontent.com/38718951/54532846-c25f8100-49c3-11e9-8ad5-13cc6e1a2412.png)

**Comment by JamesBauman** [comment]
this is done
