### ISSUE TITLE
System requirements calls out z/OS provisioning toolkit - this is not required for Zowe

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#435]
## Description
https://zowe.github.io/docs-site/latest/user-guide/systemrequirements.html#overview
This calls out z/OS provisioning toolkit as a pre-requisite for Zowe.
This is incorrect and the row in the table should be removed

## Pages to Update
https://zowe.github.io/docs-site/latest/user-guide/systemrequirements.html#overview

## Screenshots
![image](https://user-images.githubusercontent.com/28100302/54833151-74919400-4cb5-11e9-8b22-de84e38520cd.png)

## Additional context
This has been raised by a number of customers, and also was a pain point in a Share presentation by Dan Jast where he told customers how to install Zowe pre-reqs.
I believe z/OS PT was required at some point by an area of the CLI, however that isn't the case any more.  If there is a CLI plugin for PT then that should call out the pre-req rather than the base install docs

**Comment by nannanli** [comment]
Joe has removed this prereq from the documentation. Closing.
