### ISSUE TITLE
Move UI guidelines to the doc site

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#441]
## Is your request for enhancement related to a problem? Please describe.
Move the UI guidelines https://zowe.org/ui-guidelines-home/ from zowe.org to the doc site. 

## Describe the solution you'd like
UI guidelines are part of the extending process. The following work might be needed for the move: 
- [x] Convert the guidelines to Markdown format. 
- [x] Suggest creating a new section under Extending section and name it as "Guidelines". Then place UI guidelines as a child topic. More guidelines are expected to be moved here in the future. 
- [x] Review the guidelines (grammar, typo, etc) and if any questions/comments, contact Jason @jayenzi 
- [x] Publish the guideline to `master` branch.

**Comment by nannanli** [comment]
Fixed in #469 . Closing this issue. Thanks Cathy and Brandon for the updates!

**Comment by jelaplan** [comment]
It looks like the new location on the doc site is:
https://zowe.github.io/docs-site/latest/contribute/guidelines-ui/ui.html#clear
