### ISSUE TITLE
Troubleshooting AT-TLS for the Application Server

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#452]
## Is your request for enhancement related to a problem? Please describe.
When customers have AT-TLS if the zluxserver.json file is not updated correctly runtime errors occur

## Describe the solution you'd like
Add a section to troubleshooting for the App server

**Comment by nannanli** [comment]
The troubleshooting information for Zowe App Server has been improved and enriched over time. This issue has been covered in docs now. See [ZSS server unable to communicate with X-MEM](https://docs.zowe.org/stable/troubleshoot/app-framework/app-troubleshoot.html#zss-server-unable-to-communicate-with-x-mem). Closing but feel free to reopen if any problem persists. 
> If you are using AT/TLS, then the "attls" : true statement might be missing from the zluxserver.json file. For more information, see Configuring Zowe App Server for HTTPS communication with ZSS.
