### ISSUE TITLE
Update doc to cater for nodeCluster instead of nodeServer

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#502]
## Description

The doc currently describes the situation where `nodeServer` is used.  But from `nodeCluster` is used from now on.
## Pages to Update

Page 145 and others.

## Expected behavior

The doc describes the situation where `nodeCluster` is used.  
## Additional context

A defect was found ( https://github.com/zowe/zlux-server-framework/issues/88) by using AppScan.  The solution to this problem was to use `nodeCluster` instead of `nodeServer`.  

Any changes in Zowe runtime behaviour would best be confirmed by @1000TurquoisePogs

**Comment by nannanli** [comment]
PR #503 fixed this. Closing.
