### ISSUE TITLE
URLs that are not links at "Zowe API Mediation Layer Security" page

### ISSUE THREAD

**Issue by plavjanik** [zowe/docs-site#507]
## Description
URL in the section "Generate a certificate for a new service on localhost" and below are not links.

## Pages to Update
https://zowe.github.io/docs-site/latest/extend/extend-apiml/api-mediation-security.html#running-on-localhost

## Screenshots

![image](https://user-images.githubusercontent.com/7644758/57180049-f06e2700-6e84-11e9-812f-a58dc65923de.png)

## Expected behavior

I would expect links that I can click on.

**Comment by IgorCATech** [comment]
Let me take a look at these

**Comment by nannanli** [comment]
This has been fixed. Check out the doc site and feel free to reopen if any issue persists.
