### ISSUE TITLE
Update the Zowe installation doc

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#509]
## Describe the solution you'd like
Update a doc. Need to add more parameters to the Zowe on z/OS installation section. 

## Related doc pages
https://zowe.github.io/docs-site/latest/user-guide/install-zos.html#installing-the-zowe-runtime-on-z-os

## Additional context

For more information, see the issue https://github.com/zowe/zowe-install-packaging/issues/385

**Comment by nannanli** [comment]
I found the information has been live on the doc site here: https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#configuration-variables

Can we close this issue now? @IgorCATech

**Comment by IgorCATech** [comment]
That looks about right, Ashley. Let me close this issue.
