### ISSUE TITLE
List requiremets for the cross-memory PDSE dataset

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/docs-site#526]
## Is your request for enhancement related to a problem? Please describe.

@brooklynakos was deploying the cross-memory server's load library and[ found](https://github.com/zowe/zowe-common-c/issues/18#issuecomment-482128647) that the documentation did not provide all the reuiqrements for the PDSE dataset used by the cross-memory server.

## Describe the solution you'd like

The documentation needs to provide all PDSE requirements in the "Manually installing the Zowe Cross Memory Server" section.

**Comment by Joe-Winchester** [comment]
This should be address with the `SZWEAUTH` included with Zowe LTS and the doc for convenience and SMP/e includes the attributes required for the APF Auth PDSE
