### ISSUE TITLE
API ML - Java REST APIs with Spring Boot - Maven artifactory credentials

### ISSUE THREAD

**Issue by petr-galik** [zowe/docs-site#528]
## Description
As Zowe API ML contributor developing Java REST APIs with Spring Boot application  
I need up to date documentation on how to access artifactory using Maven. 
Currently the documentation is mentioning credentials _artifactoryUser_/_artifactoryPassword_.
The same credentials as for Gradle should be mentioned.

## Page to Update
https://zowe.github.io/docs-site/latest/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.html#prepare-an-existing-spring-boot-rest-api-for-onboarding

**Comment by IgorCATech** [comment]
I think this is an obsolete issue. Let me tag @janan07 who's refactored this particular bit of documentation. Andrew, can we close the issue?

**Comment by janan07** [comment]
Yes. No credentials are needed since the move to JFrog.
