### ISSUE TITLE
Document the region size issue during installtion

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#53]
An issue from Slack: https://ibm-systems-z.slack.com/archives/CA2PBRTEH/p1535074249000100

**Comment by John-A-Davies** [comment]
The Zowe User Guide already mentions `TSO region size` on page 11, although it does not tell you how to verify or change it.  

One version of the manual is here https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.ikjb400/ikj2h2_Limiting_the_size_of_each_user_s_address_space.htm

For reference this is:
z/OS 2.3.0->z/OS TSO/E->z/OS TSO/E Customization->Setting up and customizing the TSO/E environment->Setting up logon processing->Limiting the size of each user's address space

A user can set their own REGION size when they LOGON but for a system-wide value you might want to set the value in the JES2 initialization statements.  This is really a matter for the z/OS systems programmer on the customer's site.  

You can use the JES2 TSUCLASS initialization statement or modify it dynamically by issuing a JES2 command

```$T TSUCLASS,REGION=64M```

The manual is opaque and hard to use, so I'll need some more time to confirm all of the above.
