### ISSUE TITLE
Check for Broken Links

### ISSUE THREAD

**Issue by adambattenburg** [zowe/docs-site#54]
Ting UF Chen suggested checking for broken links in the build, and found this [python tool](http://wummel.github.io/linkchecker/). While I'd rather use something available in NPM for automatic builds, it's great as a desktop solution. In the short term we should be checking occasionally using that tool. 

As far as the automatic build, I will probably [use this tool](https://github.com/stevenvachon/broken-link-checker) and run it automatically in the deploy script. If it will stop the deploy from happening or just output broken links is yet to be determined.

**Comment by adambattenburg** [comment]
Fixed by @jackjia-ibm in PR #105.

**Comment by jackjia-ibm** [comment]
Fixed by PR #113.
