### ISSUE TITLE
Improve MVS Explorer Description

### ISSUE THREAD

**Issue by jelaplan** [zowe/docs-site#551]
The MVD explorer description could be improved with a few things. What does it look like? How do I use it? How do I access it? If I want to switch LPARs, how do I do that? The page where this occurs is:
https://zowe.github.io/docs-site/latest/user-guide/mvd-using.html#using-explorers-within-the-zowe-desktop

**Comment by nannanli** [comment]
Another update is required: Fix the out-of-date description in the cited section. For example: 
```
The explorer server provides a sample web client that can be used to view and manipulate the Job Entry Subsystem (JES), data sets, z/OS UNIX System Services (USS), and System log.

The following views are available from the explorer server Web UI and are accessible via the explorer server icon located in the application draw of Zowe Desktop (Navigation between views can be performed using the menu draw located in the top left corner of the explorer server Web UI):
```

There is no longer an explorer server web UI. Instead, the MVS Explorer, JES Explorer, and USS Explorer are all standalone apps on the Zowe desktop now. 

### Expected: 
- Move the descriptions for the three explorers to this section https://zowe.github.io/docs-site/latest/user-guide/mvd-using.html#zowe-desktop-application-plug-ins for they are just like the apps here now. 
- Then, delete this section https://zowe.github.io/docs-site/latest/user-guide/mvd-using.html#using-explorers-within-the-zowe-desktop.
