### ISSUE TITLE
Make PDF easier to be found

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#58]
This is a comment from the Slack channel. Besides adding link to the PDF file on the zowe.org website, we can consider add install/config PDF download as a section on the docs site home page so users can more easily locate it instead of hunting around. 

Current path to find the PDF file: 
zowe.org -> zowe.org/download/ (read documentation button) -> https://zowe.github.io/docs-site/user-guide/installandconfig.html -> “About this documentation” link -> Downloadable PDF file

Expected:
1. zowe.org -> zowe.org/download/ (read documentation button + **download user guide in PDF link**) 
2. zowe.org -> zowe.org/download/ (read documentation button) ->https://zowe.github.io/docs-site Home Page (**Download PDF button**)

**Comment by nannanli** [comment]
@adambattenburg Hi Adam, is there a way we can add another button on the Zowe docs site homepage to link to the PDF download page? I mean something like this: 
![zowe_docs-site](https://user-images.githubusercontent.com/14340789/45017353-00193f80-b05a-11e8-8ea3-055db54a75ed.png)

**Comment by JamesBauman** [comment]
This appears to be complete.  There is a link to DL the pdf on the docs-site home page.  Can we close this issue?

**Comment by nannanli** [comment]
Agree. The current method should resolve this issue. When we have the new doc site flow available and issue #45 resolved, we can re-evaluate if there is better method.
