### ISSUE TITLE
Add clarity on the ICSF requirement for the Cross Memory Server

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#595]
## Is your request for enhancement related to a problem? Please describe.
A customer asked for more detail on the requirement for ICSF access by the Cross Memory Server.    Currently we ask for
```The user IZUSVR who runs ZOWESVR will need READ access to CSFRNGL in the CSFSERV class.```

## Describe the solution you'd like
More detail on why this is needed and what function it provides, so that sysprogs and others giving the READ access are aware of the need and the requirement.

## Related doc pages
https://zowe.github.io/docs-site/latest/user-guide/install-zos.html#manually-installing-the-zowe-cross-memory-server

**Comment by ifakhrutdinov** [comment]
Hi @Joe-Winchester 

* ZSS (HTTP server) needs access to call the ICSF random number generator. It uses it to generate symmetric keys.
* The cross-memory server does **not** need access to CSFRNGL , so this is an error in the documentation.

I also noticed that BPX.SERVER and BPX.DAEMON are mentioned under the cross-memory section, which is wrong. The cross-memory server doesn't need access to those profiles. The USS process (ZSS) needs it for impersonation.

**Comment by Joe-Winchester** [comment]
Tks @ifakhrutdinov - does that mean that all references to CSFSERV can be removed ?  Is there any doc needed for steps to allow the RDEFINE CSFSERV and PERMIT commands ?

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester I think we should remove it from the cross-memory section (ZWESIS01), but keep it for the http server (ZSS).

**Comment by nannanli** [comment]
PR #598 clarified the requirement. Closing. Please reopen if any issue persists. Thanks!
