### ISSUE TITLE
More detail on where IZUTSSEC download location is

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#596]
## Is your request for enhancement related to a problem? Please describe.
The docs for z/OSMF lite/nucleus mentions IZUTSSEC.  For 2.2 or 2.3 users this needs to be downloaded.  The location of this download site/location isn't in the docs

```Procedure
If you run z/OS V2R2 and V2R3, download job IZUTSSEC and upload this Job to z/OS. If you run z/OS V2R4, locate job IZUTSSEC at SYS1.SAMPLIB.
Review and edit job IZUTSSEC before you submit. You can review the IZUTSSEC section below for more details.
Submit IZUTSSEC as a batch job on your z/OS system.
```   
## Describe the solution you'd like
Provide a link to where IZUTSSEC can be found

## Related doc pages
https://zowe.github.io/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html#enabling-the-z-osmf-job-rest-services

**Comment by Joe-Winchester** [comment]
@NayerNajafi - Do you know where IZUTSSEC is available for download for 2.2 and 2.3 customers ?

**Comment by NayerNajafi** [comment]
@Joe-Winchester You could find sample jobs in https://zowe.github.io/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html
(Downlod sample jobs)

**Comment by Joe-Winchester** [comment]
@NayerNajafi - I think the customer problem was that if you have 2.2 or 2.3 where do they go to get IZUTSSEC from as I think it is only shipped and included with 2.4.  I did a quick google and can't see where it is available for < 2.4 customers

**Comment by NayerNajafi** [comment]
@Joe-Winchester For z/OS V2R4, these samples will be shipped in SYS1.SAMPLIB.

**Comment by nannanli** [comment]
Just to follow up with this issue. Also adding @chentingcathy who worked on the z/OSMF Lite doc for Zowe. 

Based on the discussion, users can download the job IZUTSSEC directly from the link embedded in the z/OSMF Lite documentation. The link is provided here: https://zowe.github.io/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html#creating-a-z-osmf-nucleus-on-your-system. The link is not that obvious so perhaps we could do two things here to resolve the issue: 

1. Add this link to the following paragraph. 
> If you run z/OS V2R2 and V2R3, download job IZUTSSEC in the [sample jobs package](https://zowe.github.io/docs-site/latest/zosmf_lite_samples.zip) and upload this Job to z/OS. If you run z/OS V2R4, locate job IZUTSSEC at SYS1.SAMPLIB.

2. Make the **Download sample jobs** link more outstanding and add a sentence below the link to introduce what jobs are available in the package for download so when users search for the IZUTSSEC job name, they could find this download link. 

Does this make sense? @Joe-Winchester @NayerNajafi

**Comment by Joe-Winchester** [comment]
@nannanli - yes that would be great to add the link.  That's exactly what the customer would have wanted so it is a single click to get the .zip file.  The z/OSMF lite documentation looks really good with the embeded video so many thanks for writing it !
