### ISSUE TITLE
zowe install directory name inconsistent

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#606]
## Description

Sometimes the doc refers to `zowe_install_dir`, sometimes `/zowe_install_dir`, sometimes `$INSTALL_DIR`.  These are different names for the same directory, and so should be consistent.  To fit with other similar usage in the doc, I suggest you change them all to be `$INSTALL_DIR`.

**Comment by John-A-Davies** [comment]
Supplementary suggestion, unrelated:

This wording
```
For users who have sufficient authority under their user ID to the z/OS instance they are installing the Zowe cross memory server into, there is a convenience script provided in
```
would sound better like this
```
For users who have sufficient authority under their user ID on the z/OS instance where they are installing the Zowe cross memory server, a convenience script is provided in
```

**Comment by John-A-Davies** [comment]
Similarly;
`sctUser` should be `stcUser`
This occurs in several places.

**Comment by John-A-Davies** [comment]
Also, in the section:
8.  Configure Zowe as a started task.
 this directory seems wrong
```
cd /var/zowe/1.3.0
/zowe/builds/install/zowe-config-stc.sh
```
should be
```
cd /var/zowe/1.3.0
/zowe/builds/scripts/zowe-config-stc.sh
```
Note that `/zowe/builds` is the directory where you un-PAXed the PAX file, and it could be termed the install directory, but the path to `zowe-config-stc.sh` does not have `install` in its name.

**Comment by nannanli** [comment]
Thanks John for the suggestions! A PR has been created to address all the issues. See #609
