### ISSUE TITLE
Troubleshooting tip for Zowe Application Framework

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#610]
## Is your request for enhancement related to a problem? Please describe.
Users asked for help in the Slack channel. The following messages that SMEs provided could be documented as a troubleshooting tip on the doc site. 
The Slack messages are [here](https://openmainframeproject.slack.com/archives/CC08782AG/p1560869710012700?thread_ts=1560496424.006700&cid=CC08782AG)

## Describe the solution you'd like
Add a new troubleshooting section under Troubleshooting Application Framework and document the tips. Something like: 

### Server startup problem ret=1115

**Symptom**
When ZOWESVR is restarted, the following message is returned in the output of the ZSS server log: 
> server startup problem ret=1115

**Solution**
This message means that some other process is already listening on port 7542 either at add address 127.0.0.1 (localhost) or at 0.0.0.0 (all addresses). This prevents the zssServer from starting up. 
*Sometimes* it can be that the zssServer from a previous run did not shut down correctly, so either the the operating system has not released the socket after zssServer shut down, or the zssServer is still running.

## Related doc pages
https://zowe.github.io/docs-site/latest/troubleshoot/troubleshoot-app-framework.html

@rpenny125 provided the solution or answer so adding him here to review and provide more technical details if any. Thanks!

**Comment by jasonenglish2039** [comment]
@rpenny125 I committed this change to docs-staging (see above). Let me know if it needs tweaks.
