### ISSUE TITLE
Available versions should be updated under tab 'Versions'

### ISSUE THREAD

**Issue by chentingcathy** [zowe/docs-site#615]
## Description

In the drop down list of 'Versions', users can only select the latest version and the earlier versions. A full list of versions should be available  under 'Versions' tab.

## Pages to Update

https://zowe.github.io/docs-site/latest/

## Screenshots

![image](https://user-images.githubusercontent.com/34118963/60701802-8aa72580-9f2f-11e9-84b8-db7aac3ce4de.png)

## Expected behavior

All the available versions should be listed.

**Comment by nannanli** [comment]
Need to update previous versions of doc to add the new version numbers.

**Comment by nannanli** [comment]
Issue is resolved. Closing.
