### ISSUE TITLE
No definition for ZOWE class in RACF

### ISSUE THREAD

**Issue by maciekserafin** [zowe/docs-site#627]
## Is your request for enhancement related to a problem? Please describe.
In order to use RACF as a security for role-based access, RACF class ZOWE and related profiles need to be created. Documentation reads:

> To access dataservice endpoints when RBAC is enabled, users must have READ access to a corresponding System Authorization Facility (SAF) profile in the ZOWE class. SAF profiles have this format:"

There is no mention of parameters of ZOWE class: POSIT, RACLISTED, MAXLENGTH, DEFAULTUACC

## Describe the solution you'd like
There should be a very specific definition of ZOWE class provided. I stumbled upon it, while browsing google search (IBM Db2 DevOps Experience for z/OS V1.1 documentation):
https://www.ibm.com/support/knowledgecenter/en/SSGPWX_1.1.0/topics/devopstsk_RACF.html

> Define the RACF class that will contain all administration profiles. The default class name is ZOWE. Define the ZOWE class to the CDT class:
> 
> - Ensure that the CDT class is active and RACLISTed.
> 
> - Issue the following TSO command:
> 
>     RDEFINE CDT ZOWE UACC(NONE)
>      CDTINFO(
>         DEFAULTUACC(NONE)
>         FIRST(ALPHA) OTHER(ALPHA,NATIONAL,NUMERIC,SPECIAL)
>         MAXLENGTH(246)
>         POSIT(607)
>         RACLIST(DISALLOWED))
> 
> You might receive the following message when defining your new class : "Warning: The POSIT value is not within the recommended ranges for installation use. The valid ranges are 19-56 and 128-527." You can ignore this message.
> 
> - Refresh the CDT class using the TSO command : SETROPTS RACLIST(CDT) REFRESH
> - Ensure that the ZOWE class is active. Issue the following command to activate it: SETROPTS CLASSACT(ZOWE)

Why is it in documentation for IBM Db2 DevOps Experience for z/OS V1.1 documentation? Definition of class provided there looks valid and matches description in ZOWE documentation.
Especially that POSIT(607) is in reserved IBM range.

## Related doc pages
https://zowe.github.io/docs-site/latest/user-guide/mvd-configuration.html#applying-role-based-access-control-to-dataservices

**Comment by nannanli** [comment]
@jasonenglish2039 Hi Jason, I see you have submitted several PRs to address this issue. Wondering if we could close this issue now. Thanks!

**Comment by jasonenglish2039** [comment]
This issue has been addressed and will be resolved in 1.5.x.
