### ISSUE TITLE
Document Node.js V8 requirements

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#629]
Need to describe the following changes or point users to Node.js documentation that highlights this. 
```
I did the SMPE update for z/OS 2.3 to pull the following PTFs:
z/OS 2.3: PTFs UI61308, UI61376 and UI61747 (APARs PH07107, PH08353 and PH09543)

and now Node v8 is fully functioning on z/OS 2.3.

For z/OS 2.2, you need to get:
z/OS 2.2: PTFs UI62788, UI46658, UI62416 (APARs PH10606, PI79959, PH10740)
```

## Related page: 
https://zowe.github.io/docs-site/latest/user-guide/install-nodejs-zos.html

## Target release
v1.5.0. See comments blow.

**Comment by jasonenglish2039** [comment]
Added fix to docs-staging: https://github.com/zowe/docs-site/commit/488240b8f964e577b5bb3544c05767e536d94923

**Comment by nkocsis** [comment]
We are looking to accept Node.js V8 as a supported environment for Zowe v1.5.0 we will need to document or point users to these requirements.

**Comment by nannanli** [comment]
Re-open for we'll need to document Node.js V8 support in v1.5.0. The commented out text can be exposed then.
