### ISSUE TITLE
Option to Select Doc Version

### ISSUE THREAD

**Issue by adambattenburg** [zowe/docs-site#65]
Per @nannanli's discussion on slack, we need a way for users to select different versions of the doc site based on what version of Zowe is installed. 

Further considerations will be if we change tutorials, or just the user guide for each version.

**Comment by nannanli** [comment]
The docs squad discussed and thought that changing the version of the user guide will suffice. However, as we are reorganizing the docs site, there might be new folders/structures for the site in the near future, so not sure if changing the version of the whole site makes this work easier.

**Comment by adambattenburg** [comment]
@nannanli, I've added my thoughts on this issue and what we need to move forward with versioning. 

Blockers:
	- Adding subdomains to GitHub Pages doesn’t look like it is possible without using a custom domain name.
		- As referenced in issue [39](https://github.com/zowe/docs-site/issues/39), this provides many advantages.  
	- Using [kubernetes](https://v1-10.docs.kubernetes.io/) (and others) as an example, this is the cleanest way to do versioning. 

Temporary Solutions:
	- For now, keep old versions of the site in separate branches. We can add in versioning after. 


VuePress Next Steps:
	- Create dropdown component (in the vein of Kubernetes) linking to old versions. 
		- We will need input from design on where to put this, but I suggestion in the header like how vuepress [manages language selection](https://v0.vuepress.vuejs.org/).

**Comment by jackjia-ibm** [comment]
This has been done with pull request #181. We can run `docs-site-archive` build first to create a version and then update `docs/.vuepress/versions.json` on master branch to add the version to dropdown.
