### ISSUE TITLE
Add Home Button/Icon to the Toolbar/nav menus

### ISSUE THREAD

**Issue by JamesBauman** [zowe/docs-site#653]
**SUGGESTION**
Replace the phrase Zowe Docs in the top left corner of the screen with a home button/icon. 
I've been using zowe docs for over 1 yr. Today i was reviewing the 1.4 release notes and couldn't figure out how to open the home page without clicking back > back > back.  I was looking for a home button/icon!  

We have icons top right for Github and zowe.org.

So, perhaps we can replace Zowe Docs with a home button (as time avails itself).

![image](https://user-images.githubusercontent.com/36677566/62884344-495f1e00-bd04-11e9-8416-5743c2824edc.png)

**Comment by covalentbond** [comment]
Fixed in #1739.
