### ISSUE TITLE
download link return 404

### ISSUE THREAD

**Issue by rjmaomao** [zowe/docs-site#663]
## Description

https://zowe.org/docs-site/latest/user-guide/install-zos.html#obtaining-and-preparing-the-installation-file

In the installation guide, the link Zowe Download(https://zowe.org/download/) won't work, it returns 404 .

It worked before, but today it returns 404.
![image](https://user-images.githubusercontent.com/44960894/63313363-be4edb00-c336-11e9-9a6f-26c7af59b195.png)

**Comment by nannanli** [comment]
Hi Jing, @rjmaomao Thank you for catching this! The link is broken due to the zowe.org website update yesterday. The new link is https://zowe.org/#download now.  We just updated the download link on the Zowe doc site. It will be refreshed in a few minutes.
