### ISSUE TITLE
Document support for z/OSMF Lite in z/OS V2R4 

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#680]
When z/OSMF Lite in z/OS V2R4 goes GA, need to call it out in Zowe doc site. The following changes might be needed:

- Document the z/OSMF services that are required for Zowe to run on Zowe doc site.
- Point users to the new z/OSMF V2R4 configuration guide to set up their necessary scope of z/OSMF. 
- Need to do testing following the doc and capture any issues.

The following explanation from z/OSMF team would be helpful to understand the difference between z/OSMF Lite for Zowe and z/OSMF V2R4. 

```
"zOSMF Lite in 2.2 and 2.3" is designed for Zowe only which means:
1. We defined the minimum zOSMF configuration scope only based on what Zowe needs.
2. The output (customized zOSMF configuration guide as well as a few sample jobs) was delivered to Zowe and maintained by Zowe ID.  
3. The output (customized zOSMF configuration guide as well as a few sample jobs) doesn't touch any other z/OSMF services which Zowe does NOT use today.
 
"zOSMF Lite in V2R4" is designed for all z/OSMF customers including Zowe customers which means:
1. We defined the essential minimum zOSMF scope apply for all zOSMF customers no matter if they are using Zowe or not.
2. The output (including restructured z/OSMF Configuration Guide as well as a number of new sample jobs) is delivered to all z/OSMF customers and maintained by z/OSMF team.
3. The output covers all z/OSMF services/components.
```

### Related page
https://www.zowe.org/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html

**Comment by samanthasusu** [comment]
The documentation for z/OSMF Lite in z/OS has been discussed and will be modified with other issues. So this one will be closed.
