### ISSUE TITLE
Search box autocomplete links are not working 

### ISSUE THREAD

**Issue by ilkinabdullayev** [zowe/docs-site#682]
After typing some keyword in the search box, it shows properly the list by the search. But links aren't working.

<img width="700" alt="Screenshot 2019-08-27 at 09 48 03" src="https://user-images.githubusercontent.com/5362283/63751768-46416180-c8b0-11e9-859d-ea10f62f5422.png">

<img width="1036" alt="Screenshot 2019-08-27 at 09 51 07" src="https://user-images.githubusercontent.com/5362283/63751767-46416180-c8b0-11e9-8576-7e58bfedd6bb.png">

**Comment by nannanli** [comment]
Thank you @ilkinabdullayev for reporting this issue! Sorry there is an issue with Algolia now after the recent zowe.org change. We're actively working on this via PR https://github.com/zowe/docs-site/pull/681. Will broadcast the fix once it's complete.

**Comment by nannanli** [comment]
Verified that the issue has been fixed.
