### ISSUE TITLE
Zowe bill of materials needs updating to cater with the install and configure separation

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#696]
## Description
With the `zowe-install.sh -I` option that then allows `zowe-configure` from the runtime directory, the bill of materials needs updating as it is based on the pre 1.4 install and configure in a single step method.

## Pages to Update
https://docs.zowe.org/stable/appendix/bill-of-materials.html#zowe-pax

## Expected behavior
Update the bill of material page

**Comment by JamesBauman** [comment]
Hi @nannanli Ashley - 

Is this on our radar for the 1.5 docs?  I just published doc-staging to my local computer and the BoM content is the same as what is published in 1.4. (I used a compare tool.) Unless the updated file has not yet been merged into docs-staging, i dont think that we addressed updating the BoM....

**Comment by nannanli** [comment]
@JamesBauman No, there is no update to the BoM yet but you're right we should track this for the coming release. 

@Joe-Winchester @John-A-Davies Hi Joe, John, do you think we could cover the updates to the BoM in the 1.5 release?

**Comment by JamesBauman** [comment]
Thanks Ashley!  @nannanli - The way I read the issue i could not determine when we needed to update the BoM... thanks for checking!
