### ISSUE TITLE
ipAddresses field in zluxserver.json

### ISSUE THREAD

**Issue by UzverNumber47** [zowe/docs-site#699]
## Is your request for enhancement related to a problem? Please describe.
I think documentation should include any information on how to use ipAddresses

For example there was an issue when we had AT-TLS configured to listen to certain ipAddress and port. But we haven't changed ipAddresses field so "call" method of webapp.js sent requests to 127.0.0.1:port which resulted in ECONRESET

## Describe the solution you'd like
Any information on how to use ipAddresses

**Comment by nannanli** [comment]
@jasonenglish2039 Hi Jason, this seems an issue about the [Zowe Application framework configuration](https://docs.zowe.org/stable/user-guide/mvd-configuration.html#configuring-zss-for-https). Adding you as an assignee first but feel free to reassign as needed. Thanks!

**Comment by nannanli** [comment]
The use of `ipAddresses` has been clarified in docs. See the topic [ZSS configuration](https://docs.zowe.org/stable/user-guide/mvd-configuration.html#zss-configuration). Hope this is helpful to address the issue. If you need any further documentation around this, feel free to reopen this issue. Many thanks!
