### ISSUE TITLE
Doc for z/OSMF Lite

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#70]
The z/OSMF team are updating the z/OSMF configurations for Zowe. The documentation needs to be updated to integrate the new config doc. z/OSMF team expects to provide an early draft on Sep 14. 
This is the topic to be updated: https://zowe.github.io/docs-site/user-guide/systemrequirements.html#z-osmf-requirements

**Comment by wsobrien** [comment]
Hi -- I've been writing the z/OSMF information.  Right now, the GitHub doc is titled "z/OSMF Requirements," but it's really much more than that.  A better title would be "Creating a z/OSMF Lite configuration."  Can we make this change?

**Comment by wsobrien** [comment]
Also, do we have any more feedback from the Zowe team?  I need to know what questions people still have regarding z/OSMF set up.

**Comment by chentingcathy** [comment]
@wsobrien , regarding your first comment, yes, I agree. We will replace the title when the z/OSMF Lite configuration guide is ready.

**Comment by nannanli** [comment]
@John-A-Davies Hi John, do you have any more feedback regarding the z/OSMF Lite setup? 

@wsobrien Hi Wayne, from doc perspective, Cathy and I both reviewed the initial draft about z/OSMF Lite configuration and sent our edits to Li Zhi. Majority of our comments are editorial. The doc is not published yet on Zowe doc site because it's still a work in progress. However, you can view it in Markdown format here and provide your comments/edits: https://github.com/zowe/docs-site/blob/zosmf-lite/docs/user-guide/zosmf-lite.md

**Comment by Tbr00ksy** [comment]
It's my understanding that the z/OSMF Lite doc is ready to be pulled into the master branch. Is there anything still outstanding on this issue? It would be great if we could have this included in the next release.

**Comment by nannanli** [comment]
z/OSMF Lite doc was alive on the doc site in v1.1.1. See https://zowe.github.io/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html. Closing this issue.
