### ISSUE TITLE
Add description information about using default #csivol in sample installation job ZWE1SMPE

### ISSUE THREAD

**Issue by Harry-Jia** [zowe/docs-site#702]
## Is your request for enhancement related to a problem? Please describe.
In sample installation job ZWE1SMPE from ZOWE.ZWE001.F1, if users use the default #csivol, they confuse the description in this sample job about how to set #csivol 

## Describe the solution you'd like
Add the texts in Additional content section to given document link.

 
## Related doc pages
https://docs.zowe.org/stable/user-guide/install-zowe-smpe.html#create-smp-e-environment-optional

## Additional context
Note:  if you choose to use the default of letting your Automatic Class Selection (ACS) routines decide which volume to use,  comment out the following line in sample installation job - ZWE1SMPE.
//         SET CSIVOL=#csivol

**Comment by nannanli** [comment]
@Harry-Jia Thank you Harry for the suggestion! The note has been added in the documentation via PR #714. Closing this issue now and feel free to reopen if any issue persists.
