### ISSUE TITLE
Can't find zowe-configure.yaml in runtime directory.

### ISSUE THREAD

**Issue by rjmaomao** [zowe/docs-site#713]
## Description

I first installed Zowe SMP/E Alpha version. Then I tried to follow document to configure the zowe runtime. The following document was used. 
https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#configuration-variables

Under section Configuring the Zowe runtime directory
It said "You configure the Zowe runtime directory by running the script **_/scripts/zowe-configure.sh._**" But I didn't see the shell script under this location. 

_168:/zowe/bld140smpe/**scripts** $ ls
configure       internal        templates       zowe-verify.sh_

I saw it under  _**configure**_ which is a sub-directory of _**scritps**_. And there are also other files needed for configuring Zowe runtime. I'm not sure if my current layout of directory is correct? 
_174:/zowe/bld140smpe/**scripts/configure** $ ls -la
total 320
drwxr-xr-x   2 bpxroot  2611        8192 Aug 29 06:49 .
drwxr-xr-x   5 bpxroot  2611        8192 Aug 29 06:49 ..
-rwxr-xr-x   1 bpxroot  2611        4826 Aug 29 06:49 zowe-config-stc.sh
-rwxr-xr-x   1 bpxroot  2611        9940 Aug 29 06:49 zowe-configure-api-mediation.sh
-rwxr-xr-x   1 bpxroot  2611        2553 Aug 29 06:49 zowe-configure-explorer-api.sh
-rwxr-xr-x   1 bpxroot  2611        4515 Aug 29 06:49 zowe-configure-explorer-ui.sh
-rwxr-xr-x   1 bpxroot  2611         357 Aug 29 06:49 zowe-configure-proclib.sh
-rwxr-xr-x   1 bpxroot  2611         943 Aug 29 06:49 zowe-configure-scripts.sh
-rwxr-xr-x   1 bpxroot  2611        1600 Aug 29 06:49 zowe-configure-zlux-certificates.sh
-rwxr-xr-x   1 bpxroot  2611        2939 Aug 29 06:49 zowe-configure-zlux-ports.sh
-rwxr-xr-x   1 bpxroot  2611        5786 Aug 29 06:49 **zowe-configure.sh**
-rwxr-xr-x   1 bpxroot  2611        7647 Aug 29 06:49 zowe-copy-proc.sh
-rwxr-xr-x   1 bpxroot  2611       14635 Aug 29 06:49 zowe-init.sh
-rwxr-xr-x   1 bpxroot  2611        1420 Aug 29 06:49 zowe-install-existing-plugin.sh
-rwxr-xr-x   1 bpxroot  2611        3150 Aug 29 06:49 zowe-install-iframe-plugin.sh
-rwxr-xr-x   1 bpxroot  2611        1426 Aug 29 06:49 zowe-install.yaml
-rwxr-xr-x   1 bpxroot  2611       13582 Aug 29 06:49 zowe-parse-yaml.sh_

Under Port allocations and Certificates, the yaml file _**zowe-configure.yaml**_ was mentioned. But I didn't find this file. From the contents I think it should be the same as  _**zowe-install.yaml**_ file?

![image](https://user-images.githubusercontent.com/44960894/65407375-e5586b00-de14-11e9-9550-796466e8afe7.png)

Could you please let me know if there's anything wrong in my understanding ? Thanks in advance!

**Comment by nannanli** [comment]
@Joe-Winchester @John-A-Davies It seems some script directory paths in the docs are incorrectly documented. Could you confirm? Thanks!

- The directory path of `zowe-configure.sh`. Currently it's documented as `/scripts/zowe-configure.sh`. 
- The directory path of `zowe-configure.yaml`. Currently it's documented as `/config/zowe-configure.yaml`.

**Comment by John-A-Davies** [comment]
The file `install/zowe-install.yaml` is the only one I can see.  Here is a list of the `.yaml` files in my installed runtime directory:
```
zlux-app-server/doc/swagger/security-mgmt-api.yaml
zlux-app-server/doc/swagger/server-plugins-api.yaml
zlux-server-framework/plugins/config/doc/swagger/data.yaml
sample-angular-app/doc/swagger/hello.yaml
scripts/configure/zowe-install.yaml
xmem-server/zowe-install-apf-server.yaml
```
And here is the install directory
```
install/zowe-install-apf-server.yaml
install/zowe-install.yaml
```

**Comment by John-A-Davies** [comment]
Also, in the runtime I have `scripts/configure/zowe-configure.sh`, and the same in the install directory.

**Comment by nannanli** [comment]
@John-A-Davies Thanks John! I created a PR https://github.com/zowe/docs-site/pull/721 to update the incorrect file paths and requested your review. : )

**Comment by nannanli** [comment]
The fix is live on the doc site. Check it out: https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#configuring-the-zowe-runtime-directory. Closing this issue now and thanks for reporting and reviewing the issue!
