### ISSUE TITLE
AZWE001.read.me.txt incorrectly identified as EBCDIC, should be text

### ISSUE THREAD

**Issue by kathysychan** [zowe/docs-site#717]
## Description

In this page,

https://docs.zowe.org/stable/user-guide/install-zowe-smpe.html#overview-of-the-installation-steps

AZWE001.read.me.txt incorrectly identified as EBCDIC. It should be noted as text. Instruction later on the page does correctly say that the file should be transferred as text to zOS.

**Comment by nannanli** [comment]
This has been fixed. Thanks Kathy for reporting the issue!
