### ISSUE TITLE
Doc does not say when to run zowe-configure.sh

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#729]
## Description

The doc mentions `zowe-configure.sh` 4 times, but only to say "before you run `zowe-configure.sh`".  

## Expected behavior

It should say "Now run `zowe-configure.sh`" somewhere, possibly just before "Stopping the ZOWESVR PROC".

## Additional context

The whole install process is quite long and there's no checklist, so the user could easily forget to run this vital script.

**Comment by nannanli** [comment]
Docs now include an installation roadmap that guides users to complete a list of installation and configuration tasks as well as the scripts/JCLs that should be run. This should address this issue where users might forget to run the required script. Closing.
