### ISSUE TITLE
Document the datasetPrefix .yaml value

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#748]
## Is your request for enhancement related to a problem? Please describe.
Git issue https://github.com/zowe/zowe-install-packaging/issues/740
introduced a new parm for zowe-install.yaml
```
datasetPrefix={userid}.ZWE
```

## Describe the solution you'd like
Document the use of this parameter

## Related doc pages
installation of convenience build chapter

**Comment by nannanli** [comment]
PR #749 fixed this issue. Closing.
