### ISSUE TITLE
Zowe.org Contribute Page Refresh

### ISSUE THREAD

**Issue by hogstrom** [zowe/docs-site#76]
_From @Tbr00ksy on August 24, 2018 18:37_

The contribute page (https://zowe.org/contribute/) could be revamped in several ways:

- [x] Add links and descriptions on the slack channels
- [x] Add graphic for squads and brief description of how the interact? 
- [x] Add link to squad Waffle boards/backlog
- [x] Add link to groups.io for list of list of scheduled squad meetings

_Copied from original issue: zowe/zlc#5_

**Comment by hogstrom** [comment]
_From @Tbr00ksy on August 27, 2018 18:41_

Review issue #10

**Comment by hogstrom** [comment]
_From @Tbr00ksy on August 28, 2018 20:54_

Need to note that the only way to get calendar invites to community meetings is to be part of the zowe-dev mailing list.

**Comment by Tbr00ksy** [comment]
@jackjia-ibm can you please update the following to say:
![Screen Shot 2018-09-27 at 1.29.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a907c3157b1d800120a86d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f46b7191a379f110224f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ebfd9380d25ce3417a5bf844db601ba228d4b87bee98d4ed2f42f67b6d5db1063474f4dcbed5727a29841c95df543e14b5ca7143562e57f2431.png)
https://zowe.org/contribute/

"The community calendar shows all of the scheduled meetings. All meetings are an open invitation for any community member to join. To receive email invitations to meetings join the Zowe-dev@lists.openmainframeproject.org mailing list."

**Comment by jackjia-ibm** [comment]
@Tbr00ksy page updated.
