### ISSUE TITLE
Some STC suffixes are not documented

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#776]
## Description

The table of SS subcomponent values does not have entries for all the STCs I see on my system.  I've marked the missing ones below:
```
JOBNAME  
ZOWE1AC  
ZOWE1AD  
ZOWE1AG  
ZOWE1DS  missing
ZOWE1DT  
ZOWE1EF  missing
ZOWE1EJ  
ZOWE1SV  (master task)
ZOWE1SZ missing
ZOWE1UD  
ZOWE1UJ  
ZOWE1UU  
```
## Pages to Update

Under heading "Address space name"

## Expected behavior

The missing subcomponent values should be in the list.  The tasks starting with ZOWE1SV are master tasks, not subcomponents, but it is useful to mention them somewhere in this section.  
## Additional context

Perhaps the entry ED is wrong, and it should say EF, like I see in my real STC list on the test system.

**Comment by nannanli** [comment]
Currently the doc describes the STC names as follows: 

STC names have certain components and use the following format:

`pfxnSS`

where:

- `pfx` - Prefix that contains up to four characters, for example, ZOWE.
- `n` - Instance number
- `SS` - A subcomponent. SS can be one of the following values:

        AC - API ML Catalog
        AD - API ML Discovery Service
        AG - API ML Gateway
        **DS - ??？**
        DT - Zowe Desktop Application Server
        EF - Explorer API Data Sets
        EJ - Explorer API Jobs
        **SZ - ???**
        UD - Explorer UI Data Sets
        UJ - Explorer UI Jobs
        UU - Explorer UI USS

The questions are: 
- What do **DS** and **SZ** stand for? 
- Is there still a value of **ED**?  

Wondering if @John-A-Davies @Joe-Winchester @ifakhrutdinov @1000TurquoisePogs you know the meaning for them? Thanks!

**Comment by ifakhrutdinov** [comment]
I thought the official prefix was `ZWE` and the fourth letter is its sub-component. That's the pattern we've been using.

**Comment by John-A-Davies** [comment]
Component code SZ is for the zss Server a.k.a. zlux server.
DS is for the node.js instance for the zlux server.
There is no ED.

**Comment by nannanli** [comment]
Thank you both! This PR #801 updates the sub-component names.
