### ISSUE TITLE
Add doc for Zowe Cross Memory Server ZWESAUX

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#784]
## Description

The statement "Zowe Cross Memory Server consists of a single load module with the name ZWESIS01." on page 83 is no longer true.  There is now also a LOADLIB and PROCLIB member named ZWESAUX.  
## Pages to Update

All references to ZWESIS01.

## Expected behavior

Various places in the document should be updated to reflect the new ZWESAUX.

## Additional context

Perhaps Irek (ifakhrutdinov@rocketsoftware.com) is the right person to provide the extra doc for this.  @ifakhrutdinov

**Comment by ifakhrutdinov** [comment]
@John-A-Davies  I can make the changes.
CC: @jasonenglish2039

**Comment by jasonenglish2039** [comment]
Addressed this in PR #792
