### ISSUE TITLE
Document ZWESAUX startup more clearly

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#806]
# Description
ZWESAUX is described in the doc alongside ZWESIS01, however there is no mention of starting ZWESAUX which can lead to confusion

## Pages to Update
https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#manually-installing-the-zowe-cross-memory-server

## Expected behavior
ZWESAUX is described in https://github.com/zowe/zss/blob/master/zis-aux/README.md.  The install docs should cover more background for the program and also describe the fact that it is controlled by the master address space and doesn't need manual starting (similar to the ZOWESVR starting >1 address space).

**Comment by jasonenglish2039** [comment]
Addressed in #810
