### ISSUE TITLE
Tell users they must not try to start ZWESAUX

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/docs-site#808]
## Is your request for enhancement related to a problem? Please describe.

A couple of users have mistakenly tried to start the ZWESAUX STC manually, resulting in error messages.
## Describe the solution you'd like

The doc should explicitly state that ZWESAUX must not be started manually.  The ZWESIS01 cross-memory server must however be running for some Zowe components to work.  The ZWESIS01 task will start and stop ZWESAUX as and when required, and no user intervention is necessary.   
## Related doc pages

see section "Starting and stopping the Zowe Cross Memory Server on z/OS"

**Comment by nannanli** [comment]
@jasonenglish2039 Hi Jason, could you take a look at this issue and work with perhaps Irek @ifakhrutdinov ? Another issue that is closely related is #806 .
these two issues both require more clarification of the start/stop behavior of ZWESAUX. The related section is [https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#starting-and-stopping-the-zowe-runtime-on-z-os](https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#starting-and-stopping-the-zowe-runtime-on-z-os). Thanks!

**Comment by jasonenglish2039** [comment]
@nannanli I worked on it with Irek yesterday. The only reason it's not committed already is that I got a new laptop and have to figure out again how to sign my commits. It's a headache.

**Comment by jasonenglish2039** [comment]
Addressed in #810.
