### ISSUE TITLE
Update docs to reflect https://github.com/zowe/zowe-install-packaging/issues/864

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#879]
## Is your request for enhancement related to a problem? Please describe.
https://github.com/zowe/zowe-install-packaging/issues/864

## Describe the solution you'd like
Docs updated 

## Related doc pages
Zowe install and configure chapters

**Comment by nannanli** [comment]
@stevenhorsman had updated the doc for this issue via PR #852 . See details https://github.com/zowe/docs-site/pull/852/files
