### ISSUE TITLE
Consolidated System Requirements summary

### ISSUE THREAD

**Issue by ijmitch** [zowe/docs-site#89]
I see that https://zowe.github.io/docs-site/user-guide/systemrequirements.html has sections for each component, and each of those sections has its own list of requirements and mixes in bits of config.

Would a single consolidated list of pre-reqs be helpful/possible? For example, the mention of node.js seems like it deserves to be further up front.

**Comment by nannanli** [comment]
Hi @ijmitch , thank you for the good suggestion! We're working on improving this part and will definitely take your suggestion into consideration. We'll update you here when there are any progress.

**Comment by ijmitch** [comment]
Thanks @nannanli - this came up when someone asked me about whether node.js needed to be acquired and installed before installing/running Zowe. (He actually didn't mind either way - if it's a pre-req he'd be quite happy too as he wanted an excuse to get it to play with regardless of Zowe).

**Comment by nannanli** [comment]
There have been quite a lot enhancements to the system requirements section and Node.js install in the past releases. 
- There is now a brief consolidated system requirement summary which lists common system requirements as well as requirements for Zowe Application Framework and Zowe CLI. See [System Requirements](https://zowe.github.io/docs-site/latest/user-guide/systemrequirements.html).
- Node.js install was improved. The required install steps are documented on the Zowe doc site. See [Installing Node.js](https://zowe.github.io/docs-site/latest/user-guide/install-nodejs-zos.html). It's being further enhanced. See issue #253 . 
- z/OSMF Lite is alive for non-production use. See [Configuring z/OSMF Lite (for non-production use)](https://zowe.github.io/docs-site/latest/user-guide/systemrequirements-zosmf-lite.html)

Closing this issue. Feel free to open new issues if any problem persists. Thanks!
