### ISSUE TITLE
Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#890]
## Is your request for enhancement related to a problem? Please describe.
https://docs.zowe.org/v1-7-x/user-guide/install-nodejs-zos.html

![image](https://user-images.githubusercontent.com/28100302/71891027-8a395280-313d-11ea-8247-2126639cade4.png)

## Describe the solution you'd like
The node team have fixed the problem and released 8.16.2.  
We should update the docs to remove the "Known Issue" and "Workaround" para

## Related doc pages
user-guide/install-nodejs-zos.html

**Comment by nannanli** [comment]
Description has been updated to remove the ref to need 8.16.0. Instead, guide users to install 8.16.2. 
We'll need to open another issue to state support of v12 when it's complete or remove the limitation of v8.16.1 when the known issue is addressed.
