### ISSUE TITLE
Rework doc to include separate certificate configure and zowe-instance-dir

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#902]
## Description
For 1.8 there is a change in how Zowe is installed and configured
Certificates are configured outside the main install path

## Pages to Update
Multiple

**Comment by nannanli** [comment]
The configure-certificate topic for 1.8 is available at https://github.com/vit-tomica/docs-site/blob/d39a4303eb2aa4cda7e137ec0ba3401500b98e83/docs/user-guide/configure-certificates.md. When we rework the process, this topic could be linked or merged. See issue #875
