### ISSUE TITLE
Adding release notes to doc site

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/docs-site#91]
As part of CII Badge requirement:

The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes). Projects whose results are not intended for reuse in multiple locations (such as the software for a single website or service) AND employ continuous delivery MAY select "N/A". (URL required)

**Comment by jackjia-ibm** [comment]
The release notes MUST identify every publicly known vulnerability with a CVE assignment or similar that is fixed in each new release, unless users typically cannot practically update the software themselves. If there are no release notes or there have been no publicly known vulnerabilities, choose "not applicable" (N/A).

**Comment by nannanli** [comment]
Hi @jackjia-ibm , there is a release notes section on the docs site already. See https://zowe.github.io/docs-site/user-guide/summaryofchanges.html. It is what is requested as `a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be`. 
We're going to change the tile from `Summary of changes` to `Release notes` in next release.   For vulnerability issues, we're not aware that Zowe has such issues. If there are any in the future, we can also document in release notes. So does this meet the requirement of this issue?

**Comment by jackjia-ibm** [comment]
@nannanli It's perfect, and thanks for the details. I will mark this as closed and put the URL in CII Badge progress page.
