### ISSUE TITLE
Publish the 1.8 tech preview

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#921]
## Is your request for enhancement related to a problem? Please describe.
Publish Zowe 1.8.0 tech preview

## Describe the solution you'd like
Two new buttons on the zowe.org downloads section on the >pre-release-builds drop down

![image](https://user-images.githubusercontent.com/28100302/72458115-e5171d80-37bf-11ea-9ba9-e468315fb000.png)

## Additional context

URL for the 1.8 convenience build 
https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/nightly/zowe-1.8.0-staging-436-20200115051733.pax

URL for the 1.8 SMP/E build
https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/nightly/zowe-smpe-1.8.0-staging-436-20200115051733.tar

Update the existing button Zowe SMP/E alpha to be labelled "Zowe 1.7.1 SMP/E alpha"

**Comment by jackjia-ibm** [comment]
@Joe-Winchester if we publish this to zowe.org, do you still want the download go through legal page?

**Comment by nannanli** [comment]
Created a draft for the website changes. See https://github.com/zowe/zowe.github.io/pull/71. If legal pages are added, need to update the URL in the PR.

**Comment by Joe-Winchester** [comment]
> @Joe-Winchester if we publish this to zowe.org, do you still want the download go through legal page?

@jackjia-ibm - good question.  jfrog is opened up to be publicly available and I think there is a separate effort to make that visible from the zowe.org home page.  Would that link go through a legal page ?   If it's not much effort then it feels safest to put a legal page, but if it's a lot of work I am happy to bypass it for the 1.8 tech preview.

**Comment by jackjia-ibm** [comment]
Thanks @Joe-Winchester, then I think would like to bypass the legal page. I think after v1.8.0 formal release, this link will be removed, so it won't stay for long time.

**Comment by Joe-Winchester** [comment]
Awesome !  Tks for publishing the tech preview !
