### ISSUE TITLE
Issues with sample ZSS cert definition

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#925]
## Description

There are several issues with the sample commands (and description) to set up secure communication with the ZSS server.

## Pages to Update
https://docs.zowe.org/stable/user-guide/mvd-configuration.html#configuring-zss-for-https

## Expected behavior

I added 2 files with updates to this issue. One with change markers from current to new content, and one with the formatted new content.
[Zowe doc - ZSS cert - change markers.docx](https://github.com/zowe/docs-site/files/4081801/Zowe.doc.-.ZSS.cert.-.change.markers.docx)
[Zowe doc - ZSS cert - final.docx](https://github.com/zowe/docs-site/files/4081802/Zowe.doc.-.ZSS.cert.-.final.docx)

**Comment by OnnoVdT** [comment]
@ajinrocket At first glance no changes we done to the page. Why is this closed?

**Comment by ajinrocket** [comment]
I merged the changes to our docs-staging branch. It hasn't been updated on the page yet. Sorry, I'll reopen this issue and close it once the page has been updated.

**Comment by ajinrocket** [comment]
Changes are now implemented on site. Closing issue
