### ISSUE TITLE
Update the Zowe Explorer page

### ISSUE THREAD

**Issue by IgorCATech** [zowe/docs-site#944]
## Describe the solution you'd like

Update the page to include the embedded video "Getting started with Zowe Explorer"
## Related doc pages

https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html 
## Additional context

Release notes have to be updated, too. 
https://docs.zowe.org/stable/getting-started/summaryofchanges.html

**Comment by IgorCATech** [comment]
Updating the docs to include the Zowe Explorer video part 2

**Comment by nannanli** [comment]
@IgorCATech Seems the updates have been published. Can we close this issue now?
