### ISSUE TITLE
No ZWESIS01 in samplib

### ISSUE THREAD

**Issue by impervachris** [zowe/docs-site#948]
in the 1.8 doc, on page 94, the cp statements refer to copying ZWESIS01 and ZWESAUX from the samplib.  However, these members no longer exist.  They are ZWESISTC and ZWESAUX.

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, this is a comment on this section: https://github.com/zowe/docs-site/blob/docs-staging/docs/user-guide/configure-xmem-server.md#step-1-cross-memory-proclib-and-load-libary. 

Could you take a look? Thanks!

**Comment by Joe-Winchester** [comment]
@NayerNajafi.  I've created PR https://github.com/zowe/docs-site/pull/953 that should address this issue with the xmemory reference to zowe-install.yaml and also the verify pointing to the old parm name
@NayerNajafi  For the ZWESVSTC promotion to the proclib this is covered in https://github.com/zowe/docs-site/blob/docs/docs/user-guide/configure-zowe-server.md
@impervachris - I can't seem to find the section that you are referring to with the old cp statement, can you copy some of text before and after so I can do a find across the files to see which one is in error ?    Tks

**Comment by impervachris** [comment]
@Joe-Winchester - Here you go
Step 1: Cross memory load library and PROCLIB
Before you begin
• Load modules: The cross memory server has two load modules, ZWESIS01 and ZWESAUX, provided in the PDS
SZWEAUTH created during the installation of Zowe.
• Prob libraries: The cross memory server PROCLIB JCL is ZWESISTC and the auxiliary address space
PROCLIB JCL is ZWESASTC.
Follow these steps
1. Copy the load modules and add JCL to a PROCLIB.
a. To copy the files to a user-defined data set, issue the following commands:
**cp -X ZWESIS01 "//'<zwes_loadlib>(ZWESIS01)'"
cp -X ZWESAUX "//'<zwes_loadlib>(ZWESAUX)'"**
Where

**Comment by Joe-Winchester** [comment]
Tks @impervachris - I've updated the chapter in the PR https://github.com/zowe/docs-site/blob/zds-948/docs/user-guide/configure-xmem-server.md.  I couldn't quite match with the text you pasted so I maybe have a slightly later version but I think (hope) it reads better now and is a little clearer where I've separated out the manual from scripted techniques to promote the ZWESI and ZWESA artefacts

**Comment by Joe-Winchester** [comment]
Fixed in 1.8
