### ISSUE TITLE
Explorer server API review and clean up required

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#95]
Some APIs might have already been dropped (such as the following ones). Need to review the existing doc and make corrections.

-  https://zowe.github.io/docs-site/user-guide/usingapis.html#persistent-data-apis
-  https://zowe.github.io/docs-site/user-guide/usingapis.html#system-apis
-  Dataset - POST /Atlas/api/datasets/{dsn}/{basedsn}  
-  Z/os System - GET cpu

and also , from a documentation standpoint, are we missing this:
```
Jobs - get /Atlas/api/jobs/{jobName}/{jobIds}
```

**Comment by nannanli** [comment]
@jordanCain Hi Jordan, can we close this issue now?

**Comment by jordanCain** [comment]
@nannanli I'm happy with the changes we made, feel free to close this
