### ISSUE TITLE
Update mvd-installplugins.md to describe the new 1.8 technique

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/docs-site#971]
## Description
The docs chapter mvd-install-plugins.md is out of date and describes pre 1.8 techniques for adding apps to the desktop.
It should be updated to describe zowe-install-app.sh and also zowe-install-iframe.sh helper scripts

## Pages to Update
https://docs.zowe.org/stable/extend/extend-desktop/mvd-installplugins.html

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, 
I verified in [1.9 docs](https://docs.zowe.org/stable/extend/extend-desktop/mvd-installplugins.html) that the steps and scripts are now up-to-date. It now guides users to install new apps by running the `zlux-app-server/bin/install-app.sh` script. Closing this issue but feel free to reopen if any issue persists. Thanks!
