### ISSUE TITLE
Update the description about 3270 terminal

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#977]
## Is your request for enhancement related to a problem? Please describe.
From Timothy Sipples
> I’d like to request a Zowe documentation and feature labeling change since there’s a technical inaccuracy that’s causing confusion, specifically for the tn3270-ng2 plug-in.
Zowe describes this plug-in as “a TN3270 emulator written in Angular and Javascript.” And this is most confusing. TN3270 (now TN3270E) is a network protocol, primarily defined in IETC RFC 2355. Zowe is not emulating this network protocol — it’s using it! What it’s emulating is the 3270 family of terminals, no TN. TN means “Telnet.” The Zowe Application Server (ZLUX) establishes a TN3270E connection with the mainframe — with the TN3270E server in Communications Server for z/OS if z/OS, for example — on the backend, and then this plug-in and ZLUX convert the 3270 data stream to a Web (HTML/Javascript) presentation delivered to browsers via HTTPS, another network protocol that is not emulated but used.
> Zowe documentation and feature descriptions properly describes its VT emulation as VT emulation, not “Telnet VT emulation” or some other odd construction. VT (“Video Terminal”) refers to the family of terminals that Digital Equipment Corporation originally designed and marketed, such as the VT100.

## Describe the solution you'd like

So, in short, this request is to drop the “TN.” This is “a 3270 emulator.” In the parts of the documentation and feature descriptions that need to refer to network protocols, it’d be this way (as an example):
" The tn3270-ng2 plug-in provides end users with emulated 3270 terminal sessions that work in standard Web browsers without browser plug-ins, extensions, or add-ons. Basic 3270 terminal functions are emulated and supported, generally consistent with IBM 3278 and 3279 terminal data streams. Terminal features that are not supported include, as examples, 3179G Host Graphics, 3472G Vector Graphics, terminal-attached printers, and light pens." 

“This plug-in runs within the Zowe Application Server (based on the ZLUX framework) on any compatible platform, including on z/OS. The tn3270-ng2 plug-in and the Zowe Application Server use standard TN3270E network protocol for back end communications with the mainframe. Typically TN3270E sessions are established directly with the TN3270E server that’s part of Communications Server for z/OS, but other standard TN3270E servers are also compatible, such as the TN3270E servers included with z/VM, the OSA-Express Integrated Console Controller, IPv6/VSE, and TCP/IP for z/VSE. TLS-encrypted TN3270E is supported and recommended, especially when there is any internal or external physical network connection between the Zowe Application Server and the TN3270E server.

“The network protocol between the Zowe Application Server and Web browsers is standard HTTP or HTTPS. (HTTPS is recommended.) The plug-in and the Zowe Application Server convert between 3270 data streams and HTML/Javascript, and they also manage back end and front end network connections for each user.

## Related doc pages

- Description in Overview: https://docs.zowe.org/stable/getting-started/overview.html#zowe-application-framework
- Description in user Guide: https://docs.zowe.org/stable/user-guide/mvd-using.html#tn3270

**Comment by nannanli** [comment]
Hi @Joe-Winchester @1000TurquoisePogs, 
I wonder if you could evaluate this suggestion or doc enhancement request from a technical perspective. Basically, it is reported that the TN3270 naming for the TN3270 plug-in is confusing and the request is to drop the “TN.” Tim who made the suggestion has created some PRs (see the commits for this issue) to propose changes. 
If so, it seems not only documentation needs to be updated, the naming in the UI needs an update as well. I want to get your advice before we move forward. Thank you!

**Comment by Joe-Winchester** [comment]
@nannanli - I agree totally with the comments.  I saw a PR from Timothy that I think for the instance.env file description that looked like he had rewritten it to be more correct and approved that PR as-is.  For the UI change I'll defer to @1000TurquoisePogs but I agree from an end user having `TN3270` as a desktop app rather than calling it `3270 emulator` is confusing.

**Comment by nannanli** [comment]
This issue has been addressed. Closing.
