### ISSUE TITLE
many of the doc links are broken (404) https://github.com/zowe/docs-site/tree/master/docs

### ISSUE THREAD

**Issue by lbdyck** [zowe/docs-site#983]
## Description

Many of the links are broken and get a 404

## Pages to Update

https://github.com/zowe/docs-site/tree/master/docs

**Comment by nannanli** [comment]
Hi @lbdyck , thank you for reporting the issue! 

The link cited is the source file for the Zowe documentation where some links show as broken in the source file but actually work correctly on the documentation website [https://docs.zowe.org/stable/](https://docs.zowe.org/stable/). I guess you might Google the site to find this page. We encourage you to read the doc site instead which provides better reading experience without link issue. At the same time, we'll investigate how to code the links better so they also work in the source files to avoid confusion. 

Thanks again and any further findings and feedback on Zowe docs are welcome.
