### ISSUE TITLE
question: ICSF setup required?

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/docs-site#991]
## Description

1. For starters, this is not in ZWESECUR, so it belongs somewhere else. 
2. Where does Zowe use symmetric keys? As far as I know, or North and South-bound communication is all doen with asymetrical private/public keys.
 
## Pages to Update

https://docs.zowe.org/stable/user-guide/configure-zos-system.html#configure-an-icsf-cryptographic-services-environment

## Expected behavior

Move to correct location, and give more info on when this is needed.

**Comment by nannanli** [comment]
@NayerNajafi @Joe-Winchester Hi Nayer, Joe, 

There was a discussion about this previously and Nayer commented: 

> Generating symmetric keys (Symmetric Encryption) is required if we want to have cryptography services such as Data Confidentiality to protect data from disclosure to unauthorized parties, so it is not a requirement for Zowe. I would say the part related to generating symmetric keys (defining RACF profiles) should be removed  from Zowe document. We could only have the steps about defining or checking the ICSF configuration depending on whether ICSF is already installed. 

I'm wondering if we should remove the https://docs.zowe.org/stable/user-guide/configure-zos-system.html#configure-an-icsf-cryptographic-services-environment section or alternatively, clearly state that the steps are optional.

**Comment by Joe-Winchester** [comment]
@OnnoVdT - do you think we should do what @nannanli suggests and remove the section about generating ICSF ?  I'm in favor of removing it which is what @NayerNajafi is suggesting but I wanted to get your opinion as well before we pull the doc section.

**Comment by OnnoVdT** [comment]
I agree with removing. If it stays it has to be in a different section that properly frames the context, and the optional nature.

**Comment by nannanli** [comment]
@Joe-Winchester @OnnoVdT Thank you for confirming! I'll remove this section in the coming release.

**Comment by 1000TurquoisePogs** [comment]
I believe the description for why this was in the documentation was wrong, but it actually was a required step of running zss. 1.11 and 1.12 may be broken on new systems currently.

The real reason this section was in the documentation:
ZSS cookies require random number generation for security. ICSF is a secure way to do that, so https://github.com/zowe/zowe-common-c/blob/master/c/icsf.c#L533
CSNBRNGL is invoked.

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.csfb400/rng.htm

I'm not sure why ICSF has an RNG feature underneath symmetric keygen specifically, but that's where it gets confusing.

**Comment by 1000TurquoisePogs** [comment]
Also, the need for ZSS cookies becomes optional when SSO is in play, so new documentation could have the steps needed for SSO and the steps needed for ZSS cookies in a similar section so that it's easy to see the options. But, I'm unsure if SSO uses the same SAF resources anyway.
