### ISSUE TITLE
Documentation EXTERNAL_COMPONENTS

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/docs-site#998]
Add documentation for the feature added in https://github.com/zowe/zowe-install-packaging/issues/1022

**Comment by NakulManchanda** [comment]
Demo apps:

Demo Sample Trial App - iframe app plugin for Zowe Desktop
https://github.com/zowe/sample-trial-app/pull/5

Demo API registration behind API/ML
https://github.com/zowe/sample-node-api/pull/7

**Comment by NakulManchanda** [comment]
@stevenhorsman @Joe-Winchester 
Made EXTERNAL_COMPONENT scenario master branch so it can be easily shared, its first draft, feel free to verify readme, it can be improved.

https://github.com/zowe/sample-node-api
https://github.com/zowe/sample-trial-app
